### ISSUE TITLE
Render without DOM?

### ISSUE THREAD

**Issue by yanns** [MithrilJS/mithril.js#10]
It is possible to render a component without a DOM, in node.js for example?

React has the function [React.renderComponentToString](http://facebook.github.io/react/docs/top-level-api.html#react.rendercomponenttostring) for example to allow that.
Quite useful to pre-render the page on the server and for tests in node.js.

**Comment by StreetStrider** [comment]
@lhorie, @StephanHoyer, @Raynos 
Hello, everyone. Can you tell what's the status on this? Which soultion is preferred now?
@yanns, are you using some particular solution and if yes, which one?

**Comment by lhorie** [comment]
@StreetStrider I'd use @StephanHoyer's library

**Comment by tivac** [comment]
@StreetStrider we've been using @StephanHoyer's library for months, it's exactly what you'd want.

**Comment by StreetStrider** [comment]
@lhorie  @tivac, Thanks for help! I'll certainly investigate it.
Also, thanks for keeping mithril in way of modularity and composability.

**Comment by amireldor** [comment]
Hello persons. I've been trying out @StephanHoyer 's mithril-node-render. There's this issue with parameters to routes mentioned in his [article](https://gist.github.com/StephanHoyer/bddccd9e159828867d2a) (about his package). In order to get a parameter in your controller you have to do something like `var stuff = params ? params.stuff : m.route.param('stuff')`.

Quoting:
> This can be improved of cause. I simply did not come up with an elegant solution  for this. Any ideas?

So, did anyone did come up with an elegant solution?

**Comment by isiahmeadows** [comment]
For what it's worth, for this reason alone I'm considering resurrecting my [m-iso](https://github.com/isiahmeadows/m-iso). Mithril itself simply relies too much on the DOM to sufficiently be useful in isomorphic applications. That's how it can stay so small. You'd be effectively reimplementing Mithril along with half of the DOM if you were to try to shim it into working in Node, especially if you're doing more than just rendering simple views and controllers (no network).

It's not elegant to remove Mithril from the DOM, and matter of fact, its source code isn't very elegant to begin with. Imagine spaghetti logic that manipulates quantum references to improbability drives. That's Mithril at the moment, and that's why @lhorie is working on a rewrite (thankfully).

As for m.route.param, that's a pretty simple concept to implement. The biggest problem with routing currently is [Unicode](https://github.com/lhorie/mithril.js/pull/898). But to be honest, Unicode sucks. All it does is complicate things beyond all known recognition.

*(Well...that and make it possible to write an app that supports 15 different languages, but let's ignore that for now...:smile:)*

**Comment by ancmikesmullin** [comment]
i made this one in 35 lines if anyone is interested
https://gist.github.com/ancmikesmullin/102bcba5836362d46f4c0e7880e5a98f
