### ISSUE TITLE
Iframe reloads with each redraw when focused

### ISSUE THREAD

**Issue by Ryan-McMillan** [MithrilJS/mithril.js#1335]
Repro: https://jsbin.com/luvihepace/1/edit?html,js,output

When the iframe is focused, the src attribute gets set with each redraw and causes the iframe to reload.  This happens when the document.activeElement is the iframe which causes it to set the attrs even when there are no differences.

This happens in 0.2.5, but not 0.2.4.  It looks to have been introduced here: https://github.com/lhorie/mithril.js/commit/db17958f0b96204ee8d97c882323d93c32564be2

**Comment by Morklympious** [comment]
Yeah I see what you're talking about, the check here: `($document.activeElement === node)` is true because of the iframe focus. 

Seems simple enough to come up with a focus blacklist in the same way we declare [nodes that can't have children](https://github.com/lhorie/mithril.js/blob/next/mithril.js#L52). And then just add a check there to make sure that the element isn't blacklisted?

This is all off the cuff ideas though. 

`($document.activeElement === node && !blacklist[$document.activeElement])`?

**Comment by pygy** [comment]
Beside `iframe`, what should be on that list? Media elements, I suppose... There are other elements that may reload external resources like `script` and `link[rel=stylesheet]`, but I don't know if they can get focused...

Another thing to investigate: in #691, @lhorie says:
> IIRC the snippet in  db17958  used to exist to deal w/ this issue

I haven't looked further back, but in `v0.2.0` that snippet wasn't there. Was the checkbox thing dealt with elsewhere? Or had said snippet already been removed?

**Comment by isiahmeadows** [comment]
@pygy 

> > IIRC the snippet in  db17958  used to exist to deal w/ this issue
> I haven't looked further back, but in  v0.2.0  that snippet wasn't there. Was the checkbox thing dealt with elsewhere? Or had said snippet already been removed?

That commit is tagged 0.2.5, by the way. That might answer your question. 😄

**Comment by isiahmeadows** [comment]
Closing - last v0.2 release has been cut.
