### ISSUE TITLE
Make the wiki useful

### ISSUE THREAD

**Issue by dontwork** [MithrilJS/mithril.js#1572]
As of yesterday nearly all of the content on the Mithril wiki is outdated and I'm bringing this up here so we can discuss what to do with all the resources which point to 0.2.* projects.

**Comment by barney-spatialos** [comment]
We should make sure to preserve all current wiki content for posterity.

**Comment by barneycarroll** [comment]
cc @CarlMungazi who's been floating some good ideas on this subject for a while.

We should make sure to preserve current wiki content for posterity too.

**Comment by CarlMungazi** [comment]
Thanks @barneycarroll. My idea is related to the 'Who uses mithril' section. We could have mini-interviews/articles with people explaining how they use mithril in production. I think it would provide useful insight to mithril newcomers (and current developers) as well as helping us maintain the 'buzz' from yesterday's launch. I'm happy to look at this as interviewing people is something I enjoy!

On a more general note, is it better to create an 'archive' section for 0.2* material and then have a new section for 1.* stuff, or are we better off keeping it as it is and then updating it as new stuff is created?

**Comment by isiahmeadows** [comment]
I feel that, at the very least, it should be marked as 0.2. I like @CarlMungazi's suggestion of putting it in a dedicated archive, since many of those are highly specific to the 0.2 API (e.g. `config` work).

**Comment by balupton** [comment]
I'm new to Mithril, looking at due to the v1 release - came from many years of Backbone, and some recent React fiddling, which I'm not to happy about due to certain silly things - however, react and vue both have amazing ecosystems - which seems to be where Mithril is lacking - despite it seems with Mithril v1, it is super nice.

Would be nice for @isiahmeadows suggestion, of just cloning out the current repo, pushing it up to its own archive repo, and starting a new one (or iterating from the old) for v1.

Tying those two paragraphs together, it would be nice for the wiki to go a lot into sample projects, ecosystem libraries, and apps I can checkout - with one's currently active and maintained.

The current wiki also seems to have a lot of snippet pages. I'm not sure a wiki is the best place for snippets. Perhaps have links to codepen or runkit or the like instead.

**Comment by isiahmeadows** [comment]
@balupton 

> One of the silly thing in React are these errors [...]

Another reason why JSX sucks. IMHO, React should just know to drop them.

**Comment by isiahmeadows** [comment]
Closing, since this issue has not been updated in over a month, and typically, issues inactive for that long do not usually produce any action. If you feel something in Mithril needs added or changed, please file a new issue.

**Comment by balupton** [comment]
@isiahmeadows how would one act on this? it seems the proposal is to dump the current wiki in a repository on a 0.2 branch, and then set master as the current branch for the 1.0 series.

**Comment by isiahmeadows** [comment]
@balupton I closed it because the conversation pretty much died. And GH wikis aren't actually Git repos, so there is no `master` to set.

I'll reopen, but it's low priority. And to be honest, most of the frequented content within the wiki should really be in `docs`, like links to third party tools. In particular, many of them have already been updated to 1.x.

**Comment by balupton** [comment]
> And GH wikis aren't actually Git repos, so there is no master to set.

Not sure what you mean here, as:

```
git clone https://github.com/lhorie/mithril.js.wiki.git
```

Of course, no branch support.

---


> I'll reopen, but it's low priority. And to be honest, most of the frequented content within the wiki should really be in docs, like links to third party tools. In particular, many of them have already been updated to 1.x.

Good point.

**Comment by isiahmeadows** [comment]
@balupton All these days, and I never knew that... Interesting...
