### ISSUE TITLE
Mithril's Bundler overrides Ruby Bundler in 'npm run' scripts

### ISSUE THREAD

**Issue by illarionvk** [MithrilJS/mithril.js#1668]
I'm working on an app that will be hosted on Github Pages. I use [github-pages gem](https://github.com/github/pages-gem) to compile the static site with Jekyll locally.

I use npm scripts in `package.json` to run the build task:

```javascript
//...
  "scripts": {
    "build": "bundle exec jekyll build",
  }
//...
```

The `bundle exec` command should launch Ruby Bundler gem, but it launches Mithril's Bundler instead. This happens because npm scripts look up executables in `node_modules/.bin` folder first.

Ruby Bundler is far more popular than Mithril's Bundler. Would you consider renaming the executable in .bin folder from `bundle` to `mithril-bundle`?

**Comment by illarionvk** [comment]
For now I'm using a [postinstall script](https://docs.npmjs.com/misc/scripts) to remove Mithril's bundle symlink from `node_modules/.bin`:

```javascript
//…
  "scripts": {
    "postinstall": "rm -f node_modules/.bin/bundle",
    //…
  }
//…
```

**Comment by barneycarroll** [comment]
@illarionvk so installing Mithril as an NPM dependency adds Mithril's `bundle` NPM script to the node scripts of your dependent package? That seems like broken NPM behaviour, surely?

**Comment by illarionvk** [comment]
@barneycarroll Installing Mithril as an NPM dependency adds a symlink of Mithril's `bundle` executable to `./node_module/.bin/` folder:

![mithril-bundle-symlink](https://cloud.githubusercontent.com/assets/5012724/23456273/0e884ec0-fe73-11e6-86c9-dcd5817161b4.png)

**Comment by pygy** [comment]
@barneycarroll I think it is intentional in order to allow meta-packages of commands.

I'm surprised there's no way to bypass the `.bin` folder when calling commands...

**Comment by illarionvk** [comment]
@barneycarroll This is a standard NPM behavior:

> Any bin files are symlinked to ./node_modules/.bin/, so that they may be found by npm scripts when necessary.
[https://docs.npmjs.com/files/folders](https://docs.npmjs.com/files/folders)

**Comment by barneycarroll** [comment]
I'm extremely surprised by this behaviour. Apparently [it was introduced](https://github.com/npm/npm/issues/10095) in npm\@3 as a necessary measure to allow dependency scripts to function with a flattened dependency tree. But the notion that dependency scripts should affect *your* path really seems like an unacceptable oversight to that solution.

The change to Mithril you're proposing makes sense, but the underlying issue is an NPM bug AFAIC. What if a dependency has a `cd` script? Should all NPM packages ensure they have globally unique script keys? 🤔

**Comment by illarionvk** [comment]
Yarn doesn't symlink stuff to `.bin` folder and [a lot of people think breaks compatibility](https://github.com/yarnpkg/yarn/issues/2758).

You have control over the names of Mithril's binaries in `package.json`:

[https://github.com/lhorie/mithril.js/blob/next/package.json#L32](https://github.com/lhorie/mithril.js/blob/next/package.json#L32)

**Comment by isiahmeadows** [comment]
:-\

And this adds to the list of reasons why I feel it shouldn't be publicly exported. (I've noted this opinion of mine multiple times in the past.)

**Comment by barneycarroll** [comment]
OK I totally missed the point @illarionvk, thought you were talking about npm script references as opposed to bins. I don't see any reason why ospec and bundler can't be referenced by explicit path since they're only used in npm scripts anyway. What do we think?

**Comment by isiahmeadows** [comment]
@barneycarroll `ospec` is okay exporting a binary, since it's like Mocha and Tape, and is a more general purpose test utility. It shouldn't be published with the `mithril` package, as that's feature creep. `bundler` is very specific to Mithril, and is hardly useful anywhere else, as has been noted on several occasions by @tivac and I, so that should be relegated to explicit paths.

**Comment by lhorie** [comment]
^ agree
