### ISSUE TITLE
Module view is no constructor function

### ISSUE THREAD

**Issue by kay-is** [MithrilJS/mithril.js#167]
The API-documentation mentions 

> A module is an Object with two keys: controller and view. Each of those should point to a
> Javascript class constructor function.

But only the controller function is called with new.

**Comment by skyeagle** [comment]
@lhorie, what is the reason to make view as a function instead of a constructor? I suppose a view just represents object states. There are a few benefits to have a view as a constructor:

- it could prevent from storing objects inside a view itself
- it could be extended

So, my code looks like:

```coffeescript
modulejs.define 'base-view', ->
  class BaseView
    constructor: (ctrl) ->
      @ctrl = ctrl
      @helper = @constructor

    renderModal: (view) ->
...
```

```coffeescript
modulejs.define 'dashboard-view', ['base-view' ], (BaseView) ->
  class extends BaseView
    constructor: (ctrl) ->
      return new _Class(ctrl) unless @ instanceof _Class
      super
      return @content(ctrl)

    content: ->
      [...]
```

Am I doing something wrong? So, it feels like I have some misunderstanding here. Could someone explain that, please. Thanks.
