### ISSUE TITLE
m.route.link should work with dynamic onclick-handlers

### ISSUE THREAD

**Issue by StephanHoyer** [MithrilJS/mithril.js#1709]
works

```js
function onclick() {
  alert('huhu')
}

m('a', {
  href: '/foo',
  onclick: onclick,
  oncreate: m.route.link
})
```

does not work

```js
m('a', {
  href: '/foo',
  onclick: function() {
    alert('huhu')
  },
  oncreate: m.route.link
})
```

**Comment by StephanHoyer** [comment]
also works with 
```
m('a', {
  href: '/foo',
  onclick: function() {
    alert('huhu')
  },
  oncreate: m.route.link,
  onupdate: m.route.link
})
```

**Comment by pygy** [comment]
@StephanHoyer Do you think we can do other things beside #1712?

I don't think we could improve `m.route.link` to work for dynamic `href` attributes without `onupdate`.

**Comment by isiahmeadows** [comment]
@pygy Simply fixing [this](https://github.com/lhorie/mithril.js/blob/next/api/router.js#L50-L58) to use `addEventListener` instead (something not easily removable) would fix it.

**Comment by tivac** [comment]
It's weird that it doesn't already since [render uses `addEventListener`](https://github.com/lhorie/mithril.js/blob/74cbd4c17b938af6d0edfba96ab12b196ffee884/render/render.js#L572).

**Comment by pygy** [comment]
I don't think the engine strips the `onclick` handler, because it is registered on the DOM element directly, the `render` engine is not aware of it.

The event handler defined by `m.route.link(thisVeryVnode)` cannot AFAICT be universally made not to depend on `thisVeryVnode`.

Currently, `m.route.link` [mutates](https://github.com/lhorie/mithril.js/blob/683d85a9527dd98e81bc4b220ed5a75d26eb0f5d/api/router.js#L49) the `href` of `vnode.dom` to a prefixed verison of `thisVeryVnode.attrs.href` and the handler reads back from the DOM attribute. This works fine as long as the `vnode.attrs.href` doesn't change, but when it does, the prefixed version is replaced by a non-prefixed one. So it probably works with only `oncreate` for dynamic hrefs when the prefix is `""`.

What we should probably do is verify that when the handler fires, `vnode.DOM.href.slice(prefix.length) === thisVeryVnode.attrs.href`, and error out if it isn't the case.

**Comment by isiahmeadows** [comment]
@StephanHoyer Try to repro it *without* using `m.route.link`. Something like this should be adequate:

```js
function oncreate(vnode) {
    vnode.dom.onclick = function () {}
}

// In the rendering component
m('a', {
  href: '/foo',
  onclick: function() {
    alert('huhu')
  },
  oncreate: oncreate
})
```

I may have been wrong in my initial guess, now that I think about it. This sounds like a rendering bug either way.

@tivac I equally find [the use of `vnode.dom.setAttribute("href", ...)` over `vnode.dom.href = ...`](https://github.com/lhorie/mithril.js/blob/next/api/router.js#L49) odd, but that's independent of this issue.

**Comment by barneycarroll** [comment]
I think the problem with `m.rouite.link` as a lifecycle method is that the scope of a routed link is greater than any one lifecycle. If you want to extend it to meet the edge cases, you kinda need `onupdate` - you also need to mutate `href` after the fact and second guess what the author may be doing with `onclick`, which all feels very hacky because it's really out of keeping with the principles of the virtual DOM abstraction & hyperscript.

A more extensible solution, that would make it easy to consider things like #1731, would be to provide a route link component. This would avoid the ugly DOM thrashing in the present implementation. We could enable this without breaking backward compatibility by extending `m.route.link` with `oninit`, `onbeforeupdate` and `view` methods.

**Comment by isiahmeadows** [comment]
@barneycarroll I almost suggested it should've been a component, but I wasn't sure how people would react here, considering how boilerplatey many component-based routing systems are. (React Router is notably terrible for this. It takes ~30 lines of code for just setting up *basic* routing.)

**Comment by barneycarroll** [comment]
@isiahmeadows the reason I'm suggesting this is so we can reduce code in author land and core.

**Comment by isiahmeadows** [comment]
@barneycarroll I get that. I just had reservations about how well it'd be received, due to bad experiences with other component-based routing systems (like React's), so I was a bit jaded there. And the potential boilerplate I was referring to was on the user's side, not necessarily the implementor's side.

**Comment by isiahmeadows** [comment]
I'm not sure about `m.route.a` (the name of your component) though...

**Comment by barneycarroll** [comment]
> I'm not sure about m.route.a (the name of your component) though...

Me neither. Truth be told, I'd like this to replace the `m.route.link` reference and constitute a breaking change. Having both APIs is silly when one is simply the caveat-free version of the other using a completely different mechanism.

The other possibility is to extend the `m.route.link` function with the view property that allows it to be both. I think it's fair to say this is totally out of keeping with v1's API style, given how `m.route` has ditched all the overloads for separate properties.

**Comment by isiahmeadows** [comment]
@barneycarroll Here's how you could solve that (overloading `m.route.link` to be a component):

1. Make `m.route.link` a factory component.
2. Detect factory usage via `vnode.tag === m.route.link`
3. ???
4. Profit?

And although yes, overloading is generally avoided in Mithril's APIs, if we plan to deprecate current `m.route.link` usage for v2, this may be okay.

**Comment by pygy** [comment]
@isiahmeadows that's brilliant :-) :+1:

**Comment by barneycarroll** [comment]
@isiahmeadows the factory aspect is orthogonal, if anything it's easier to distinguish `m.route.link` used as a function (lifecycle invocation) from usage as a tag (`view` property) and avoid any kind of magic sniffing. No?

**Comment by pygy** [comment]
@barneycarroll The current component kind detection code will treat a function without a view on the prototype as a closure component.

**Comment by pygy** [comment]
So,

```JS

m.route.link = function(vnode) {
  if (vnode.tag === m.route.link && vnode.state == null) { // the `state` is null at this point in the closure
    return {
      view(vnode) {
        return m('a', vnode.attrs, vnode.children)
      },
      oncreate: _link, // without the `state` check above, this would return a component rather than linkify
      onupdate: _link
    }
  }
  } else {
    // current impl
  }
}
```

That being said @barneycarroll's assumption that a function with a `view` property would be considered a POJO component isn't misguided given the current semantics. Closure components as currently implemented may break existing code.

**Comment by pygy** [comment]
@barneycarroll I've modified the component kind detection code to treat functions with a `view` method as POJO components, not factories ( #1746).

**Comment by barneycarroll** [comment]
Great stuff @pygy :)

**Comment by isiahmeadows** [comment]
My event rework should fix this, since it now exclusively uses `addEventListener` and `removeEventListener`.
