### ISSUE TITLE
Access state from event handler

### ISSUE THREAD

**Issue by chebum** [MithrilJS/mithril.js#1739]
Tried searching the archive but failed. I'm sorry if this topic was already discussed.
This block of code is from current docs:
```
var BigComponent = {
  activate: function() {/*...*/},
  deactivate: function() {/*...*/},
  update: function() {/*...*/},
  view: function(vnode) {
    return [
      vnode.attrs.items.map(function(item) {
        return m("div", item.name)
      }),
      m("div", {
        ondragover: this.activate,
        ondragleave: this.deactivate,
        ondragend: this.deactivate,
        ondrop: this.update,
        onblur: this.deactivate,
      })
    ]
  }
}
```

How are we supposed to access `vnode.state` from event handlers activate/deactivate/update?

**Comment by volnei** [comment]
What about this?
```javascript
var BigComponent = {
  activate: function(vnode) {/*...*/},
  deactivate: function(vnode) {/*...*/},
  update: function(vnode) {/*...*/},
  view: function(vnode) {
    return [
      vnode.attrs.items.map(function(item) {
        return m("div", item.name)
      }),
      m("div", {
        ondragover: function(){this.activate(vnode)},
        ondragleave: function(){this.deactivate(vnode)},
        ondragend: function(){this.deactivate(vnode)},
        ondrop: function(){this.update(vnode)},
        onblur: function(){this.deactivate(vnode)}
      })
    ]
  }
}
```

**Comment by chebum** [comment]
@volnei thank you for the reply. After thinking about it a bit more, I came up with this variation:

var BigComponent = {
  activate: function() {/* *this* now points the state here */},
  view: function(vnode) {
    return [
      vnode.attrs.items.map(function(item) {
        return m("div", item.name)
      }),
      m("div", {
        ondragover: this.activate.bind(this)
      })
    ]
  }
}

Do you have any idea why Mithril doesn't pass vnode as a second argument to event handlers? I checked `function updateEvent(vnode, key2, value)` method that actually fires events and it is able to pass vnode as an event handler argument.

P.S. I'm surprised how lively this community is. I left 2 messages and got two replies in under 15 minutes. WOW. Thanks a lot to all of you.

**Comment by volnei** [comment]
@chebum Nice! It works too!

About yout second question, let's see what the experts say =D

Thanks!!

**Comment by isiahmeadows** [comment]
BTW, `handleEvent` from the `EventListener` DOM interface will be supported in v2. If you'd like to provide state, you can do one of a few different things:

1. Create a class with the data you need, and have it handle whatever in `handleEvent`.
2. Create a class that wraps the `vnode` and its event handler, and calls the event handler with the vnode on `handleEvent`.
3. Use `handler.bind(null, vnode)` or similar.

In the case of the second, you can just use this helper:

```js
class WrapEvent {
    constructor(vnode, listener) {
        this.vnode = vnode
        this.listener = listener
    }

    handleEvent(e) {
        this.listener.call(e.currentTarget, e, vnode)
    }
}
```

If you need to access the DOM node for the handler itself, it's `e.currentTarget` as usual. If you need to access the DOM node's corresponding vnode, you're probably better off just using `oncreate`, since that's getting into specialized territory.

Given that this is now workable in v2 (without requiring closures), I'm going to close this issue.
