### ISSUE TITLE
`config` fires on inner nodes first, then on parent nodes. `onupdate` does the opposite.

### ISSUE THREAD

**Issue by dwaltrip** [MithrilJS/mithril.js#1836]
Code demonstration (it runs with v0.2.5 and v1):

```js
var App = {
  view: function() {
    return m('.outer', {
      onupdate: function() { console.log('onupdate -- outer'); },
      config: function(el, isInitialized) {
        if (isInitialized) { console.log('is updating -- outer'); }
      }
    }, m('.inner', {
      onupdate: function() { console.log('onupdate -- inner'); },
      config: function(el, isInitialized) {
        if (isInitialized) { console.log('is updating -- inner'); }
      }
    }, m('button', { onclick: noop }, 'Button')));
  }
};
```

I think the `v0.2.5` behavior makes more sense? Not 100% sure. I was relying on it in one case, I've just learned, and on first glance it seems a fair bit trickier to make it work with the new ordering (I'm doing DOM height adjustments on nested components).

I searched, but didn't find any discussion of this change. There might not be any action needed, but I just wanted to bring it up.

**Comment by pygy** [comment]
Good catch, the change should probably be documented in the migration guide, if not improved.

In general, the v1 hooks run on the descending edge of a depth-first traversal of the tree.

We can't just flip the firing order of the post-view hooks, since it would cause the hooks to run on the last children before running on the first (in non-keyed scenarios, the order in keyed lists is undefined).

There are probably use cases for hooks running on both the descending and the ascending edge, but having both would duplicate the number of hooks...

**Comment by dwaltrip** [comment]
So after a bit of time trying to update my code, I realized the biggest difference is that it is inherently more difficult to know if you are the last node to have `onupdate` fire with descending order, as a node doesn't know if it is the final leaf node.

With ascending order, it's not difficult to know if you are the root node, and thus the last node to have `onupdate` fire for.

**Comment by dwaltrip** [comment]
I have no problems with it being closed. I haven't touched the code that inspired this issue in quite a while.
