### ISSUE TITLE
Time for a monorepo

### ISSUE THREAD

**Issue by tivac** [MithrilJS/mithril.js#1875]
We keep on running into issues with things not being published and the repo root is starting to get messy. I think it's time for a monorepo.

@pygy, @isiahmeadows, @lhorie, anyone feel strongly for or against this plan? 

Work has already started here: https://github.com/tivac/mithril.js/tree/monorepo

**Comment by pygy** [comment]
I'm for it, but I'd rather wait for #1592 to be merged in if you don't mind (unless git is smart enough to track moving files when rebasing).

**Comment by tivac** [comment]
I'm not in a huge rush, happy to manually merge stuff as it comes in.

**Comment by isiahmeadows** [comment]
I'm for it, since we're already half-way there now. Just a few nits on that repo:

1. Why is `mithril-querystring` separate from `mithril`? It's not already published independently, and it doesn't have much use case outside Mithril. (Most people looking for a querystring module would just use `qs`).
2. You forgot to list `mithril-stream` as a dependency of `mithril`.
3. The `tests` module seems pretty pointless IMHO. We should probably just move the lone test file to `mithril/api/tests`, where it would make more sense.

**Comment by tivac** [comment]
Both `mithril` and `test-utils` depend on `mithril-querystring`. I could introduce a bunch of graph cycles by making `test-utils` and `mithril` depend on each other but it makes file explorers and editors freak out. I'll probably just make `test-utils` depend on a 3rd party parser instead long-term, this was a quick pass to get tests running.

**Comment by pygy** [comment]
External dependencies will break the `tests/index.html` pages.

I thought that `mithril` did not depend on`mithril-stream`... does it?

**Comment by tivac** [comment]
It ships stream currently, at least.

https://unpkg.com/mithril@1.1.1/stream/stream

**Comment by isiahmeadows** [comment]
@tivac To clarify, [I'm referring to this file](https://github.com/tivac/mithril.js/blob/monorepo/packages/mithril/stream.js) pointing to a directory that doesn't exist. If we decide to unship it (I'm neutral on it, since I almost never use it personally), then my nit is moot.
