### ISSUE TITLE
(Edge case) Elements are not being removed when promise resolves in onbeforeremove

### ISSUE THREAD

**Issue by porsager** [MithrilJS/mithril.js#1881]
I can't really explain the series of events causing this, but here is a reproducible case which will leave elements in the dom if the button is doubleclicked while the red box is visible.

(Double click the toggle button)
[Repro setup](https://flems.io/#0=N4IgTgpgZpDOAWAhArgF1QewHYgFxQEMAbWCAGhFKIgGNUIATPEAOgCtYQKoBLaz3AG1QWAgFsIzFvFRiiXEDWz0sqZgB4ZcgHwAdLPvUB6LUW0gAvmRHjJuVhwVLVEVc2qoABAgwB3AAoEkKqeALyeqGDIEPoe3vB+AMLwfAxhEVExBljOsF40KURp4cD6np4AbjwQvrieABQAlGHanmL1AOQshAwQYB2NZGWe2DSQBPR1TS2eAA6dBakdZJ4do+P0A0NY5diQYhgVEFPNoa3zHYtFy6t7EAdHW8PYAEbQGJD7h8cNwJ4MGDEngsp1apR25U8kFQyDAOywNU8-jAgJ4pHqYBmpFQABUeBIMGgMSsAEwABgpKw6cAwRCODAGjRYqHgrnqs0awws+m52VyXlmQVcXhKzxyGx+0zOc06guCqBua3FEAmECeELuD0loJlHTlwsVmu+6vKVRqdQqWAwvRmgmG5Q6y3t8SShTSADJ3W16lcGJyIQBdHn6fRiFgHZCqeoAmjICSqFgva0ATxW4NN1VqDR17Q6DB4FSdBlknReaEwWBu6chuxyRB4NAA1icZtWa+UfL5kql0gBCTvdorOmvYvEEolSsEhrztjsJAJCkLhfvzwLy2c14ftsOQBhgAi+Jpb8pWTwARgpZP9s95NdPHUwAHNH9QTZDO2vhZ5Pd79apr54zQbpuWAgpY1ggKIEhSDQsCcBQzgqGo9j6N0BC9Ji1ZiEEj48FgdQXrMAAeADcwwvAQTaPiikYMHUu5kRCvg8AwLIERSxGMeUrI8I+MjsWSnE8pYAYUPWWCNgIwggLC8j2DIqCzLAuBGEYkazI2j4sEoYhGGIPAsmAfAKKgyazHYICOBYAYWEAA)

Maybe someone else with a clear set of eyes can spot / describe it better?

The real use case was a loading icon being animated inside a parent component and at certain timings would result in the parent component not being removed.

**Comment by pygy** [comment]
Thanks for the report @porsager 

Here's an [instrumented repro](https://flems.io/#0=N4IgTgpgZpDOAWAhArgF1QewHYgFxQEMAbWCAGhFKIgGNUIATPEAOgCtYQKoBLaz3AG1QWAgFsIzFvFRiiXEDWz0sqZgB4ZcgHwAdLPvUB6LUW0gAvmRHjJuVhwVLVEVc2qoABAgwB3TwC8nqhgyBD6Ht7wfgBMgcGh4QZYzrBehAwQYPHA+p6eAG48EL64ngAUAJSB2p5i5QDkLBlZDWSeDfAQbA2VZHme2ABG0BiQkGIYBRBl5cCeDBhinhbVAbW5WPn5kKjIYFtYJZ4ACmBLPKTl2eveEKgAKjwSGGjX7TEADN+VlQMW+gByVSXiUYgADthXF4gpt8kUSmUClgMJkap5BAN8g02liorFPAAyQl1cotMB-LaeAC6gP0+jELEmyFU5UWNGQElULCGqIAnu04YViqUKmtavUGgweAVcQZZI0hmhMFg2p4hdtBikiDwaABrWbi9V4zU+XxxIIAQjNMRN21Ij2eEFeqHKVXRm10Xk1+P8VrNPp9ds1jMgDDABF8VWDK3aAEZvp9KYGgZqrB1MABzTPUXr9Kn5APE0lgyFHVTJzzVQNBrCrSzWECiCRSGiwTgUZwqNT2fTNAiZbJCoYEfWZ84shhlMMAbgGvh4DFQ8DKCc+4IAHnOqV0eJmZKvvpvtxZLNSKDqsHqBMIQPt5PYZKhwbBcEYjCzwXrMywwUYxDwy5gHwCioHy4J2CAjgWNSFhAA)

The element that remains is an extra child that is added before the previous one has been removed... Not sure there's a lot we can do about it. Thinking needed.

**Comment by RodericDay** [comment]
Here's the bug reproduced in such a way that requires no clicks

[Bug](https://flems.io/#0=N4IgZglgNgpgziAXAbVAOwIYFsZJAOgAsAXLKEAGhAGMB7NYmBvEAXwvW10QICsEqdBk2J5YxAARxCtAO4AFDACcREgLwTiSgK4wAOmnFSZsgMKFoAE3Wad+tAaFxJ1C1GsbgBiT4kA3CBhZRAkACgBKdQA+CSxQgHJ8Vyt48IpvX3oAIxgwWhUVLFo-GBDQ4EtaLFZItRivNF8miUqsfGcAT1h8LIxqAGsAcyVabTRLU1oofJs9ECgIHDmM5okVYm0lRrQgiXkRrAg4GFClaKkYYgAVRZhR4lOKCQAmAAZ38PCViVYDX4c0E5JAAHZSqTwZAJBMq1GLIb5NOJzdoQLILNCDOZpBG+aRycxWCQAMiJsVCyXcX0avgAun8DAYMHAOoCJGAxtRiBB6BJqAsBhEJA0mnizG4PBIAISignub7Ha63e6hQV1IU4nyixQqBg2aUmbUiDWxfAqSxKDCyCLfdgSADsAFZXlT-gZ2YCuTzKto0TA+RABZFhRIAPQhtYwc2WiQ8-0DTS0KSLbRQDCMWIQYiEJTQeJwCQYbTEWgAWh1lhgZwwYEYZ2oGCgUF68fWmzQcHllxuOGVETqwDj-QiAG42maLVbwraAIwfTuKntFlXhfuDkdjyMTiK2t7O+kAtpFMYPSrUbQ4Bg9WiWDpPYNQ4JhWFk+KWCB+eLpak+JEgN9+OYnjmLJtExEA0lDcMIDACQOlGCMihKTQLHzdEYCeTNNAwfp4E0WRE0sLJBw7b9jDkQ1dRJMlQR1YgqR8F0qQMb1fTXcI2A4EBMBwPAkjgAQaHoRhmB4JJxXVUi3zgYFUw6EIIEMBSYBLNFaAGYdvmbIYRjGSwSzoaYlBCM0NNI2QIEsLMJEQWdXmBAAPUymkIGAIEGEgQlshzTP+FE0QUwYJKaKSZIwOSJAUtCVOmdTNL6bTRnGfSpnyEI0V0JzfHMyzCE895vO+Fy3I8iQvMcv42BpKh0X6BAUE4HieEOLMc3IKhNnIHgSGIYE4EQMMxmBIYkiqENmuzaAAAFp3wGaHTGzMJqgfB+EoEBiA6YFuBAVbWBpVggA)

**Comment by RodericDay** [comment]
So, in the context on my reproduction, it's interesting how sensitive the bug is to the nesting. if `parent` returns `m("div", children[])` instead of just `children[]`, there's no orphans

**Comment by isiahmeadows** [comment]
Here's what I suspect: it's a race condition between the promise resolution and the subsequent render adding the item, confusing the diff algorithm with inconsistent state. [Here's a more stripped-down, synchronous repro using `m.render` with `next`](https://flems.io/#0=N4IgZglgNgpgziAXAbVAOwIYFsZJAOgAsAXLKEAGhAGMB7NYmBvAHjmIE9YA+AHTXwAjWgA8ABMH5ixWDACcA5hDSIxARgAMABxEBuKWIDuEACbFCqzdr0HCMCApKWN1-WmmCM1ANYK5tAFc0E1U5GBM3aUYRYgBaDCgHFTFqJkY5SLFEtBhYuwcndRcdNwBffhYAenYuGD40Cq1uAGFEnzEAAwAVOQcFGDkOsXpU-DEAdUIMYjEIGZNaeFm4MXMIOEQqpv4K2ih66RZE7gBlGBmOuEJaQ2bCaBMh4lpOsAS4GCGMYLEwkzkMIZ8FVjgYjhBTudOlcbncHk8Xh1iHIAp8xN8TL9wgCgSCIWDjmcLjDDAAFeRpBGvd5ojFY-6A4GVUHuMTgyHE65kikMKlIlG0n5-HFMlmHY4AJXgewAbjB0VAoGItEwTMoFJ16IIYGBaGEwlhaHKvkLsYy8fUqnt6o0DmIAJLzdZaKAYDgrczy9jTeW6uRiGBeQhidgwLQUdErQwwRWR1Z2EOMLQGOYAchW9AjcBeHECKW+w0EHzkcqMU2I6bEClo6uGAjEJyTYg0y3jMBTaDmEASiZ9EbpnpDASLMAAjqiGImwys6HIwnAtPRMc82wYMMI5fgKpVtg00Cxd9IAIJQbMRwcdEZhH0mzGXtAGo1oxJgGDUDjUWABuUMFYUgxQLQCj9MuLyDnQaDZrAWYvC6gYfGICxiK+MbIWE8orjAIgunq7asuY0xbvuO42vuggBMQzzuKYAC8vAgMifQDPR3A9ExchVORlH0JaXFUbMJh0SA87nCxUofMQnEUVRpEsGqMqnEmqhsFoBa0fRobJiA3BVAu3w6ZU8mWkZlxcuSYS8spenUYJGlcrEqkWcQLG6apaAGUZFQmSScJQI8VluQJQkkrE1D3H5LnVG5HkQApXmxdwHTjjAqL4LAaAKOYHQBWptkgMlqKxOlmWEJF1kxXFe5ybFQX0cIJgcJFRkgKUFDoNguCIAQABWCBUBBjDMF1lSVGIXT3Cs6xtikuFYlo-ghjACg4AwRH8CNY0Jt6jD8LAMwkuZaRiDRqwCrtUI+eFmInciqLnTMBXyidyAALr3QJx3NjsaAbeN8oyhAMCGFiwQDOE-BgEE1DEBA9AgyYAwABQAJQSAYWD4BZCNyIj9UcBGWCI6m8mphGyAGNIB08jMAD8Mj4GAALLWkiOSKy0jSFegaMCjEjKkTjlHVzPqpqjrUUxz9CPnKvPAPzqaC5OUswIacqi2I4vsxrZMS9Iqak2IG1SuOEB-LrIZcr5mJ0xjjMYMzDCs+bnNoNQ1486jctaETYUPHWbvczA6uaxzod1tLMCy-Lvt+eHKtPsHFDO3W2p+mDqswKovM0dwYis56yT+jnYiPfgWgBFciNyMjpTI0nWvSK1Yjkw3HOE8TsVCKIBts2HYfCzzwALFgtd88P+DRMQzT0INMwnaYADUC-a8ntf133L2o6oQQI5AOQmOvHOb2I2+g3v4SH5vyP8OUe6-VtSYrCi7ip7NgZhfDzGu-Q7Cnexn0t2kNnXOl0-YnTeKeGAh9gEW1hFdT6t0oEGBgVTJyn0IEfGgajYuqCjo3QFFg46uc5aGHCvKRGpdirmFRqXK4EAwDEBRrzTWb076jT+ghCkColQUWgHMDgyEoYwx-hGNAtAZheGIAEBIUABGORmLQMAq4fqjVnPKMI81aBjD+gI7qFcZiLmjP6QchgARaBVMY8sMgMDeCWHMAMGA4CNRUasWCroBHGHMGtNAe0sQYAaggs6PioQiUorWcBNJ3p40+gAEiJnjUW31Iau2Ee4UJssDC4MnPgu6rJQGxxyXhaQlCmAlU+hoFM10vqslIdAcheMGam3YFbVGDSI5W1xrQBqjS5DNKutfVkDSZRiIRisE6O8dTKHCIbUaJwXgAFk5iEF6EqD4SwMBoXgMGZQ3pXZFLEAELQJgfSIw0AM2+EMhGw3cHAWAYYMmsjCFIuQ7gcjA1JP4LA6xI5FxAecLoEAcCBEYXICMVgznnKSVcuGcTTCewME8gILzEK0GoAEFaxB8D9GIAAUVgBigAQhwe0JhEZwpvlClJ1yDlHJOWgeFrI4npiTKLCeWEp4zzwWIPc0gmUhUVhWZGbKYjTwYFyrJzlGVExCjHEwrLJ6itnp9fJJgDBMsekVUp5h5XssVVykpGVzAItVEjSFe4mWMWAgMVlIw2jeE+o4jgrs87YOISmJRiMACE14AkAB9fVYgkjDDKqNEUvONf4gRETIEGAMMiARvcObpIGaHQEGB7G3JgPclNYgJZ+jzr4iA5TdCzDZH-K1cg0pasICWiAS8GV93oXnUJwaFCtOvN4c2lr+hyGQBAF6KNzaHOOTzIty81A5tTYYdN+07ne0nRrAwpRkLKBkQmiWPqo2nVyaHFt4TkKRNZLfC5aAmWhJta7O1n0YGJr3RlT63rAwNQjQEwpxqJKDrQCe5NLUXpUGyN4BAKB2o4DwF88wKz8C9UoCAJF5AuokGIFoDYI0cRKExXQLAlRFkQegAAKROJUcDyzoBQbgJUHIMQiNLMg9BqgnAVR4Gg6UF6pQgA).

Here's what I am observing:

1. The initial remove doesn't unlink the fragment from the real DOM nor the virtual tree, thanks to its `onbeforeremove`.
2. The new fragment is being immediately added to the DOM, appended past the old fragment.
3. The parent fragment, when removed removes the new fragment, but not the old one.
4. The parent fragment is restored after the old fragment.
5. When the continuation is resolved, the old fragment is never removed.

**Comment by isiahmeadows** [comment]
Short-listing this for a v2 fix. [The repro still works](https://flems.io/#0=N4Igxg9gdgzhA2BTEAucD4EMAONEBMQAaEAMwEskZUBtUKTAW2TQDoALAF0fmPSk6IBqEAB4YnAJ5IAfAB0orAEYQAHgAJgC9esaYATgHNyUFOoCMABmyqA3NvUB3cvk7szV63YftE5Q1well72UDpKmGAA1ob6EACuUPhm+gShOoKqnAC0mPD+pupgQoL66er5UIjZvv6BFsE2oQC+CqIA9BLSiPJQbdgyAML50eoABgAq+v6GiPpj6tDFrOoA6uyYnOrkW-gQiDDbh27kMCgdAwptCL06ovkyAMqIW2Mw7BCOg+yU+AucEHGpDyeAWmCS6lS+H0mEcrA6Dwc93ITxe43en2+v3+gLGnH08UQYIhUJhcIRKKRD2erwxjgACgYSjigSCiepwfhIQQyfD2oiwupkajaR8GUyBCy8QT2ZzudDYXyBXcHgAlA4IABuiA58Hg6mwQnwJkM42gSkQpAgqVSjAg2uJXNJiopvQ6NyuUFEl0FAEldqdsFhJMdfOoJJsdVb9OpEJF2OHBNgiBzDo5EHrU+o3DqJIhsA4dgByQ7QFNwdSSBJFcGLJR4fTapwbTgl9SGCAmxaKdSPJPqSxHbO+QtQHbkPKJyMpuU58PxeuIACOhIEifzh0g+lSMGw0C5AOHiAcmBU2tYbXaPv6t3UAEF4HAU3OxktUpHHWaoLb7ez8qREDASQwCQWNtQEQ4mQceAIEMWYD0BOdIFgBBEHLQEgzjPB1D2dQAIzPDUh1Q9EFUINrWPQU3E2C8vSvXo2iUeJOABMIXAAXjkEB8RmOYuJkKZeP0DomJY6A3VE1jtnwTiQB3F5+PVPBOBE5jWIYr1jU1J4kzMcRsFrDiuLzAsQBkDpd3Bcz2i0t1bLeMVGVSSU9MstiZOMsVsgM5zOH4iyDKgazbLaey6SxeA-lcwLpNkulsjAH5Iv8zpAuC8htNCjKZDGFdEEJVgkCgQw3DGaLDI8kA8sJbIipK9gUrc9LMr6TSMtiriVHwSQUtskBmiIegmBYEBWAAK2oEhkMEYQ0Hadp1AmH5DlOI8igo7lsDicNEEMZgBFohR5sWsMI0EBQkC2OknJKdR2OzGULrRcKkq5e78UJJ6tmqnV7poABdL7pLugdPWOpadU1chEEcbkkjmAgFFIRIwE4choDh-A5gACgASk0BxGFYZysf0bGuskFNGGxostKLFMaAcHRrolLYAH5dFYUgYT2kpsa0QUdB0N840EPHNANGmfNukXIyLfGBqZoXoB-bVxeASWi2ltcVcQO1tXl9RFcFo2GaVnQi3p9RjvVFdyChc3wzFCKuQ5onucwXmBH5x3hagMB3zF-GNewGnEt+bsA9FxBDeNoX4+7VXEHVzXw8ixO9d-WOiF97sLWjBH9cQMxxfYmR1H5nNChjMv1B+1hsHid5sf0XHmlxnOTZ0Ab1EZruhep2mMuUNQrYFhOE9lsXgD2Rh24l2fWEyThBmgGatnulwAGot9N3P287if-vxsxEixigqnwQ+heP9RT-hi+CGv4-cYUVpWvB06k0OAkwnzja4yJUxnxf20AJAPSEiDPuOhS7lxehHe6wJHxoQcLAp2mJXogw+igwUaCWa+RBkgvA188GOVZlgmUJD8a1w1o4JKOpsb1zqm4fG9d3jkFIJwPG4tjaAw-gtCG2EmS6n1MxSgOxJB4RRmjMBKYoAQC2JETg8Q8jwEkT5LYEBSBHiOgtLcOpUhbQgCsCGkixpNy2HudMMY5yOBhNgQ0NiWy6EwFEA42wthYR6lAY6h4gyYEkc4Nwh0oCXW5JgbqFDPqhLRPJFiXZEFsiBhTEGAASGmFN5aemRv7GRYQ4nqwcPg2671HqCngenUp0SdBMKEPVEGlhCxvVBoKOhlAGEUy5vbCQLt8adKTi7cmEBupdP0D016r9BSdM1PIrGhx7pn0tCYAg1sFqPEBAAWR2OwaY+o8DuMwIRA4CYTARn9pRHQ8RsD4EjNjSwkz35I2kejMIMAkD5kKYKVIyj9BhCqLDekcRGCnGTjXOBLwJjkGYAkLh+gUyeHuQ87JzyMbpJcMHBw3z4i-JwhAMA8R9qcFYLMTgABRJAhKABCkhfT4Gxuit+yLckvPUFcm5YsoAYsFOkksSZ5ZL1IivNeJT1CtR0Dy+K2tWy4wFVkVeAgRXFIEA4CVXk074H5cveV68QYVPwCqmmP1ap1LcJqwV2qRW1OKm4TFRocZItajynicE5j8qWCMKIINMAwEkP7Cu1Dy7j22No7GABCd8kSAA+kbuTKTRsVfGWLfm2oiZIxJyCHAOHxJIoNOgCmTPjrCTAOxwzvNDgW9QStowVzCeQBpththCggS6-QhUTXsAbeQHeXKJ4cIrnE+Nhg+nviiI7Z1sx9A0HIP9PGjs2W3LrbvcwFbC2OGLVdMts6Tbv27nhEwqic1KwjWmh61ShYDoSXhJJgp36PKgDyuJbr-YepBmgoNF7iog3DXGbqKbIlVIubGl4W6735r4HgJAqMXnUDQFYFA5gADs-V-okEqFEGDdAQAMGYCIYFbhdkAAEqhZD4Ni3gaAuCcFwCgeaiRsAxFYJARg7Q8M7MoARgATKwSw3Hsj6DAKwcwLHtm7PGpNbikhDQiBgAHcg2BODIeaEAA)

**Comment by isiahmeadows** [comment]
Found the issue, and it's two-part: [Mithril's throwing an exception](https://flems.io/#0=N4Igxg9gdgzhA2BTEAucD4EMAONEBMQAaETAVwBcIAlReCTQlAM03jxOYEskZUBtUFEwBbZGgB0ACwoj4xdFAqIlqECAC+RIaPEgJAKz4lISlRTUB6SwAIAKlK4wbTmxSmIbkAE6ff2bwgbPABzMSUJAB0oaOt7D2CKTGVopApgqQgAdwAFTF8lGwBeN28yRFTEdJhMrIBhR3h8YtLyyvTfOHgANwqYqDiHT26uRCybAvxEX3xo5jIoMAouaAmVKe8ACi58AEobYGibGxEJSenN-AgwMnCKCQAjCHwATyIbfiPjg6SQlBtIiB8FxuoD3mBGvgCv9PlBvt8atk8gV0gB+H6YP4AkCfYheSHQj5feHHYC-f6AgDEYPxPChKgpIEBWhscVoAEcyFwZsSSYj6pCbOiyZjGbj3skKN4YP9DnCSfDoA9EMwIL5fCIIL1-vNFstVpt9nKFQrfBQyN44WSPFAdQslis4ZtvEa1l1ei1vDYNBpeQqtH7viyIXTCbCTd8RVjAcDQXjlAAPCj-HYB+UKgC6Ghs-wWU24UAIREDWZzNjzKq4hfwxfTNizXwzu2ivv65y2gIAjIDm7Bag06S1WOw+u3NoCAEw96L8gdNFpStpQMeAgDM077SPy5iHbDw0RXIAALBv+cidyVF6P1hdAQBWDdcZg2Z2Id2IfadBC9Q0Hm8dkAADYewUPAkAdaA+DQO8UE7TtNAzEh4CrABrKDBBAYQxDUEQuHcbweAAAULJMFAteQ0BkChcBQawFmwFCQgkSAREsXD8KIicJAABh4gBabwwAkTs2LwqQCPgQxjBACgXmwPQYDAAjsAsDQsyAA) because of a race condition, and Mithril incorrectly relies on its `domSize`.

It boils down to this:

1. First, the first vnode's `onbeforeremove` is called as expected.
2. Then, a new vnode is added, "replacing" the existing one. Mithril loses track of the first vnode here.
3. Then, the vnodes' parent is removed. This results in clearing the first `vnode.domSize` vnodes from the parent starting from `vnode.dom`, but because it's unaware the first vnode is still there, it clears *it*, but not the child vnode.
4. Then, when the first vnode's `onbeforeremove` resolves, the callback assumes the element has a parent (it doesn't), and you'll end up with an `Uncaught TypeError: Cannot read property 'removeChild' of null`.

What this means is that we need to remove `vnode.domSize + elementsAwaitingOnbeforeremove` elements rather than just `vnode.domSize` elements whenever we're removing a fragment, and we need to not assume the parent still exists when we remove it. This means we'll need a parent reference in every awaited `onbeforeremove` resolver and a new vnode field to track this delta.

**Comment by isiahmeadows** [comment]
I'm kind of leaning towards doing this to fix it:

1. When removing a vnode:
    1. I'll compute the list of vnodes to remove.
        - This will recurse through components and subtrees, but it will *not* recurse through element boundaries.
        - This list will include every vnode with a `vnode.dom` property, which conveniently includes pretty much every element type.
        - This list will include the contents of all such lists in child vnodes.
        - This will be stored on the parent vnode as a single list for all children with such hooks.
        - I'll have to benchmark this heavily.

    1. I'll call `onbeforeremove` on the parent vnode and await its result.
        - When I await this, I'll store the parent vnode in the array along with its children.
        - When the parent vnode itself is being removed as a child, it's just relocated.
        - I'll fix it to correctly await and unwrap its result if it has a `.then` method, since that needs fixed, too.

    1. I'll go through the array and invoke each found `onremove` hook on it. I'll remove the component or fragment vnodes in this pass as I encounter them.

    1. I'll go through the array and remove each child in it.
        - These might not necessarily be contiguous.

1. v2-specific break: I'll move the `vnode.domSize` count for trusted vnodes to `vnode.children` and kill the field entirely, now that we don't need it.
    - I'll need to fix all uses of [`toFragment`](https://github.com/MithrilJS/mithril.js/blob/next/render/render.js#L591-L603) to recursively add the vnodes, but it would work similarly, so it's pretty straightforward. It'd also fix a similar bug.
    - While I'm going through, I'll also drop [this function](https://github.com/MithrilJS/mithril.js/blob/next/render/render.js#L611), since it's equivalent to `parent.insertBefore(dom, nextSibling)`.
    - In general, most uses of `vnode.domSize` would make better sense just using a wrapper element's raw children. The property mainly exists for our own bookkeeping, so it doesn't make nearly as much sense to keep as, say, `vnode.dom`.

All this would be limited to the removal logic, but it'd mean I'd have to pretty much rewrite the whole thing.

This should help avoid a few potential issues with a naïve solution:

1. Since I'm going based on what the framework is aware of, what Mithril's current state forgets doesn't affect what its previous state does later.

1. I'm creating an intermediate array to avoid having to do a tree traversal three times in a row. It's a little extra memory, but it's generally not retained and it saves a lot of computation. The array is also usually pretty small, so it's not really a major allocation concern.

1. Since I'm going based on what the framework is aware of *at the time I start* when I remove a fragment, I don't need to account for potential new elements. This removes the issue of race conditions, since I know what elements I'm removing.

**Comment by isiahmeadows** [comment]
Does this continue to repro with v2?

**Comment by porsager** [comment]
Unfortunately yes.

**Comment by porsager** [comment]
Wow.. Good job @isiahmeadows !

**Comment by isiahmeadows** [comment]
@porsager It was a bit involved trying to figure out why the fuzzer suddenly started failing. Tried to do it in a way that didn't create a bunch of perf issues, too.

Sadly, the bundle is now about 9.7kB. Stupid bug fixes... 😉😄

**Comment by isiahmeadows** [comment]
Reopening because my fix for this caused [other](https://github.com/MithrilJS/mithril.js/issues/2498) [breakage](https://github.com/MithrilJS/mithril.js/issues/2502) and I need to figure out how to fix this *without* breaking `m.trust`. Here's my plan:

1. Revert my fix for this and add tests for those two bugs.
1. Release a new hotfix with this broken again and those fixed. (This can at least be reasonably worked around.)
1. Attempt to fix this without breaking `m.trust`.
1. Release a new hotfix with this fixed and hopefully those *not* broken.

**Comment by isiahmeadows** [comment]
Re-closing. Issue appears unrelated.
