### ISSUE TITLE
docs/support.md should exist

### ISSUE THREAD

**Issue by tivac** [MithrilJS/mithril.js#1914]
https://github.com/blog/2400-support-file-support

![image](https://user-images.githubusercontent.com/49545/28510287-0d29012e-7037-11e7-9e08-102d3f1731a8.png)

If we create a `docs/support.md` file it should start showing up alongside `docs/contributing.md`. It should also exist in the mithril.js.org sidebar.

Could probably start out as simple as https://github.com/MithrilJS/mithril.js#getting-help and then expand from there once we know what we want.

**Comment by thepriefy** [comment]
I wanna do this one.

However, I think that both support and contributing file name should be all capital (SUPPORT.md and CONTRIBUTING.md) in order to make it displayed to the user.

![capture 2](https://user-images.githubusercontent.com/10849586/33523126-f90a4000-d831-11e7-85f2-e9e41ac93e5f.PNG)
See: https://help.github.com/articles/adding-support-resources-to-your-project/

Do you still want both files to be in the docs/ folder or be in the root folder?

**Comment by tivac** [comment]
> To direct people to specific support resources, you can add a SUPPORT file to your repository's root, docs, or .github folder. Then, whenever someone creates an issue in your repository, they will see a link to your project's SUPPORT file.

Looks like `./docs/SUPPORT.md` should be fine. I'd prefer it to not be all-caps like that, but we're kinda at the mercy of github here. Maybe `./github/SUPPORT.md` would be better so I don't have to look at it ever.

**Comment by thepriefy** [comment]
@tivac 
So I will put both support and contribution files in ./github folder. :)

**Comment by barneycarroll** [comment]
This was fixed in #2045
