### ISSUE TITLE
Support for camelCase in the API

### ISSUE THREAD

**Issue by haggen** [MithrilJS/mithril.js#1920]
First of all Mithril is an absolute marvelous project!

So the generally adopted coding style in JavaScript dictates that composite names (such as "on create") should use _camelCase_, and I think the second most used approach is to use _snake_case_.

Now, for some reason, Mithril has adopted the odd style of writing composite names in all lower case: `oncreate`, `onmatch`, etc. I'd would be okay with this if it was optional, but it's not.

Now coding style is admittedly not the most urging issue, but it's important nonetheless so I must ask: would Mithril authors and collaborators be willing to support _camelCase_ style in its API? If not now or soon, in the future?

Thanks again!

**Comment by pygy** [comment]
Hi @haggen, thanks for the kind words, and the suggestion.

IIRC @lhorie used lower cased names to mimic the way event handlers are defined on DOM nodes (`element.onmouseover`, etc...).

I personally would be against having two sets of method names for the same functionality, and I don't think changing the names would bring enough to make it worthwhile (there are breaking changes in the works for v2.0, but for major functional improvements)

**Comment by haggen** [comment]
@pygy You're welcome! :) 

I totally agree with you about having different names for the same thing, and although `oncreate` and `onCreate` are technically different names I don't think this case would cause confusion or collisions.

Perhaps a mixin/plugin/add-on or even a hack to help with this? Totally optional of course. It's really tough when you have the habit of writing in a style and suddenly you have to change, especially when it's in just one of the modules in your code, I mean, you usually have more libraries and frameworks in place in a project and this makes it even more jarring.

**Comment by ArthurClemens** [comment]
I do experience a minor nuisance with the way Mithril names events versus React. For my "universal" library I need to create a conversion table:

```js
export const keys = {
  onclick:      "onClick",
  onfocus:      "onFocus",
  oninput:      "onInput",
  onkeydown:    "onKeyDown",
  ...
```

and then in components:

```js
{
  [keys.onclick]: e => ...
}
```

So although not a serious problem, it would be easier for me if events could be written in camel case.

**Comment by spacejack** [comment]
My case for having Mithril use lowercase only is that I use camelCase for my application component attrs callbacks. This way I'm sure not to conflict with the built-in ones. (I adopted this habit after finding a bug due to naming one of my component's callbacks `onremove`.) It's a consistent hint that this is an application callback, not a DOM or Mithril event handler.

Supporting both would definitely not be a good idea IMO because it increases the chances of accidental collisions.

**Comment by haggen** [comment]
@spacejack You really like to live dangerously don't you? :stuck_out_tongue_closed_eyes:  I mean if you have an object that responds to `onremove` **and** `onRemove` and they do different things you're playing a regretful game.

Anyways, I understand your point. But perhaps an in the future, on a major version bump this could happend. For now an additional file, kinda like a plugin, that you could load to _fix_ the API would be great.

**Comment by lhorie** [comment]
What @pygy said is basically correct. We do lowercase `onclick` because historically, the implementation did `element[attr] = someFunc` (where `attr = 'onclick'`)

Based on what @spacejack said, this would technically become a breaking change.

There is one argument in favor of supporting camel case that goes back to the original intent of having views mimic HTML: HTML is case-insensitive, so `<DIV ONCLICK=""></DIV>` is valid HTML. IMHO, if `onClick` should be supported, then all upper/lower case permutations should also be supported for that reason.
