### ISSUE TITLE
Export bundler in other repository

### ISSUE THREAD

**Issue by accessibleweb** [MithrilJS/mithril.js#1972]
Hi all,
I would like to use your bundler in my project.
I suggest to move mithril bundler into an other repository and also create a npm package for it.

If you think is not a good idea, i plan to extract the bundler in my repositorywithout changing the credits of Mithril TEAM.

What do you think?

**Comment by isiahmeadows** [comment]
We're considering migrating to Rollup (ES5 + modules), actually. Also,
because the bundler has been incredibly specific to Mithril and due to
numerous complications others had with it (like interfering with others'
Travis builds - one of the Ruby binaries on Travis is also named
`bundler`), we elected a few months ago to stop shipping the bundler
altogether with the library. It was never documented, anyways.

You're best using something else, like Rollup, Webpack, Browserify, or
similar. Rollup produces the smallest bundles, Webpack is the most
flexible/powerful, and Browserify is the simplest to set up.

**Comment by accessibleweb** [comment]
Ok thanks you, i was looking for a solution to evoid webpack and browserify.
I will have  look to Rollup :)
Or maybe keep the bundler ;)

**Comment by tivac** [comment]
You're more than welcome to use the bundler.  You can use a github repo as a NPM dependency to get it w/o needing it published on NPM.

Which is good, because I don't want the bundler published on NPM either.

**Comment by accessibleweb** [comment]
Finally rollup was not a good solution, i keep the bundler because it just perfect for me and produce tiny bundles.
I will add some new feature.
For now this is what i did : https://github.com/brickifys/brickjs-tool-bundler

I just have to import the bundler as a dev dependy and i am done :)
