### ISSUE TITLE
Why onupdate lifecycle excute twice in my example ?

### ISSUE THREAD

**Issue by justb** [MithrilJS/mithril.js#1975]
https://jsfiddle.net/lewiswei/xbw8oqaa/11/

**Comment by pygy** [comment]
The app is redrawn once because both the `onclick` handler and `m.route.set()` trigger a redraw, and the sometimes sync nature of `m.redraw()` in v1 causes one immediate redraw an one on the next frame.

With the upcoming 
 v2, m.redraw is always async and [both calls are fused](https://flems.io/#0=N4IgZglgNgpgziAXAbVAOwIYFsZJAOgAsAXLKEAGhAGMB7NYmBvEAXwvW10QICsEqdBk2J4AbhgBOAAgDCtLAAcAjNIC804AB009AK6KAJhkaJpYPWmrEI9ABQBKbWi3EhcWrHxRaAcztY+JK0eoz4ilLYdgDkEIbRDg467DquYhAwAO5mFlY29mIOmjrS0q6SMMR6kmjSWDGGEGLRFNLR8krKCSXSrMmpaBIyAOqSGIqKMDIazmkZ2eaW1rZodoXFtWXEFVU10nY9paX10Y3NFIdHpWL41ITQhhVoF5tXxw1NLXVBIWG+lY4HC83kcTgAjULEehfZwgq7RejUKAQagAa2iOSW+VWRVhcKugWCoRg+DgAOiAHoIv9lBTogBqACyJkIQQwaEMCkBlxBfVebxS-KurmiAAUMDTojyjkDpe9ohDiFC0DC5UcEVZkWiMYs8itHBt8Vd7nAoZIAJ74MEYNGONWlPn4wX4kUAIRt6LVSSF0m9Vz9vX6LkGUmk4pp6g2cyymL19lxPXKlWqtXqo3Gk0krXqHRUiR6fL5OkJvxgdk51D0OAYVtohnNrS0ICpEpgtOUTdas2ITZbNIpiDiTbM4bbL1YDjYHBAmBweFucAENHojGYPDYAF0qMi0KiEChOHOeFgIMRCJJoPh+JQQNVyDwSMRFHBEBSKWNMr5T7cFBTGafz2gAApABlCkTzPC8oCvOAKTQGAAA9iHAgCoJgm9iHNSY8GvVgN1YIA).

If you want to avoid spurious redraw when setting the route from an event handler, you can set `e.redraw` to false:

```JS
          'onclick': function(e) {
            e.redraw = false
            m.route.set('/page1/'+Math.random())
          }
```

**Comment by justb** [comment]
@pygy Thank you for your answer, I hava a related question, when the route changes from "detail/1" to "detail/2", the function in oninit lifecycle will not execute, if I put the function in onupdate lifecycle, m.request() and the function in onupdate lifecycle will call each other, and it will not stop, is there any ways to solve it?
here is my example https://jsfiddle.net/xbw8oqaa/13/

**Comment by pygy** [comment]
@justb if you want the component to be re-initialized on route change, you can [add a key](https://flems.io/#0=N4IgZglgNgpgziAXAbVAOwIYFsZJAOgAsAXLKEAGhAGMB7NYmBvEAXwvW10QICsEqdBk2J4AbhgBOAAgDCtLAAcAjNIC804AB00AEwzEMiLSBMUd9CGgjFE0sAFc01YhHoAKAJTa0W4kLhaWHwoWgBzdxMrGxNPHWlpYkIIOHx9QzUAWQNCfEkMPQUveOk4GGIAFQgcWgdidyw8mF18gHc4tASAei6IMETCGEkYaRTpDGlG4YBHB3hiCgLdaVbBzpt7aLhCCg3W6ChpagwoQ6nmqVavCnG9AZHHZ1d6Uc76B0V0kag+mGoAT2osBWB2kMAAHn86jAdOwLGgPl87I8XG40F4fH4AkEYCFwu4AOTvT4GGAEm5TWqMfCKKTYQkQXQEzwdBJJFJpAwYLI5PJLIqs6Q9UrlKo1OoNJotDDtEo9Pr3YajODjSZNWbzRZ3VZMUbETbWba7fX7U5HE5nKWXa63ZZJB5OVEvKzSYlfaQ-MB-QHA02HCFQxiw8y+YhiCAwVrIx3PdFiTyaEp+YbEBySTpYQm6CBicnSAnpIwEgDU7NShcFrFhOh0EhkAHV8opFEN1InQ+HI9Gnmj3PH2wlk+U051Ip0EhPMwWc+SShOJ2J8NRklAWkwQ-P51Ps7mKXkqbiwuUvJ4N5uElOAEZ1Yj0PM+c-zonOH7UADWBO7TvRCYfj63+7QvgZT1ASXS0keyhdCW2RJHyhSZiyc6PlW47nnCaGbn4BIAAoYJBBLIfOp5EZOhLXsQt5oPepFPvQQIQO+n72DGva-rRm7JHAt6SP8+CXhg77FJh6EcRh-7YQAQoJH4cYKxHIZW1a+GgdbSHhkFtpiYYRlGLE9h4YhoLQugwOx45Dqm6aTO4jYYM2QwUu48hKMoNzAG+MD-HYRkmbiBjEJIqSMqwSHjqhqE6JS0LuLotDUA4OAMPxJn-DcJjgfhMBQcoZjtn4GUQdlXSIIyJh2Bp2UhqFbAcCAmA4HgS5wAIND0IwzA8GwAC6VA-Ggb4ICgnCNTwWA2IQkjQJQIBpuQPAkMQihwIgPROIob5hEuChdONSRTVAAACyj4CdAAsu0TQd+D8DNxD-C2eC3aw3WsEAA) to Comp1:

```JS
var Page1 = {
  view: function(vnode) {
    return m(Wrapper, m(Comp1, {key: vnode.attrs.id}))
  }
}
```

The `:id` paramerter of the route is passed in the attrs of the top level component.

Also, you shouldn't call `m.redraw()` synchronously in the hooks in Mithril v1, `setTimeout(m.redraw)` is fine.

But even calling it that way in a `onupdate` hook is not a good idea since it leads to infinite redraw loops (as you just saw).

**Comment by justb** [comment]
@pygy Indeed, I want to implement this effect [simulate m.request](https://flems.io/#0=N4IgZglgNgpgziAXAbVAOwIYFsZJAOgAsAXLKEAGhAGMB7NYmBvEAXwvW10QICsEqdBk2J4AbhgBOAAgDCtLAAcAjNIC804AB00AEwzEMiLSBMUd9CGgjFE0sAFc01YhHoAKAJTa0W4kLhaWHwoWgBzdxMrGxNPHWlpeOk4GGIAFQgcWgdid0dnVw9vYkIIOHx9QzUAWQNCfEkMPQUvAG4sBphdRoB3L3YAJgAGEbi0BIB6CYgwaRKYSRhpMukMaQ7FgEcHeGIKJt1pHsImZeJ7aLhCChsj6ChpagwoB42uqT7PClW9OZP7JwuNzjKzSegORSVJZQGYwagAT2osDuL2kMAAHnCcjAdOwLGgIVC7PkgUUfEkpslUhksjl3G9uhgemNJtNZvNFss4Kt1p1trt9r9jqdbpBrFcbucevdHs9Xp19JJPt8Dn8liTCiDxuDIQZobCEUiltLURisYxceZfMQxBAYD1iYDNe4xJ5NEk-ItiA5JOMsO4AOS6CBiAPfIMGIwBgDUJTKFUjLOkrFxOh0EhkAHVGopFAt1O7rbb7Y6CsCXW6fAlPakfeNIuMEk3-UGQ2Gkk2m2J8NRSlBukwrZ3Oy3g6Hvhtsox8GFUl4vh3hy2AEY5Yj0MOF4fDgP0JEQagAawDpdJaC8W+3S4aU5g+BSuQDE0UGFnygmMdqJQaBxaniTV7JounZ4o225+AGAAKr4wMoAbAU2C5gUugarsQ65oJuVaAdIu7ODCR4ngCZZFJeOHSKUcDrpI8L4MuGBHl4CEgcxyZDleEEAEIMcerEAYhi5JimaDCemUjSNBb4FuSNp2g6xFni6aC0LoMCVouARBHeoQRGIymqfgBjEJIcBJjW3q+us7jZhguYLBO7jyEoyjfMAh4wPCdh6Spd5GSZ+AQLorD-kkwmiWgk7Yu4ui0NQDg4AwdEqfC3wmM+MHvsoZiFn4aUvm+EyIIFJh2JJsFWsFbAcCAmA4HgPZwAIND0IwzA8GwAC6VAwmgh4ICgnB1TwWA2IQkjQPg-CUCAPrkDwJDEIocCIFM1C6GgSW0P4jU9goEwjSU41QBMyj4KdADM+2jUdk1NcQ8J5ngU2sB1rBAA) and line 6 doesn't work

**Comment by pygy** [comment]
@justb on line 6, you can either use  an arrow function (to get a lexical `this`), define `var self = this` in `oninint` then  use `self.data` in the callback, or [use `vnode.state` instead of `this`](https://flems.io/#0=N4IgZglgNgpgziAXAbVAOwIYFsZJAOgAsAXLKEAGhAGMB7NYmBvEAXwvW10QICsEqdBk2J4AbhgBOAAgDCtLAAcAjNIC804AB00AEwzEMiLSBMUd9CGgjFE0sAFc01YhHoAKMWlq6YASm00LWIhOFpYfChaAHN3EysbEz8daWkU6TgYYgAVCBxaB2J3R2dXDwCvHxh8OENGfH1DNQBZA0J8SQw9BXc-AG4sDphdToB3XvYAJgAGWeS0VIB6RYgwaWJCGEkYaQg4aQxpQe2ARwd4Ygou3WlRzYWbewS4QgpH0egoaWoMKC-j4ZScZ+CgHPTrTb2JwuNwPBb0ByKRo7KCrGDUACe1Fgt0+0hgAA90YUYDp2BY0IjkXYSjDyoFUqFwtUorEAORUgwwNnzJaLDJZXL5QruAEjDCjXnSZarCFbHZ7A5HIZnC5XcF3Ji7YhPawvN46j5-b6-f5DfSSYGg65yqGlWG7eGUpFc6SosDorE4o1fQnExhk8xBYhiCAwUY06FlNCePyadLBbbEBySBZYdxs3QQMRs0GZgxGNkAag2ewaBalrDJOh0EhkAHVOopFFt1PHg6Hw5H7R4xHGGWliEmUws4gtUhP05ns7n0hOJ2J8NRCNARkwg-P51OsznQccCvVolleiC55upwAjQrEei59ubzds+jYiDUADWbO7dJj-bPD9S+4kjUx5sosigYEeyiLMWrQbB01w9H4Ur-tIVbjg+5LoZuwRsgAChBMDKGyf4TqeWFbhmV7EDeaB3gOKFPs4qLvp+drfr094oROK61LQkgYvgF4YO+vQkfOaEoZhKE4QAQsJH5idIyGkWelbVkEaB1tI+GQW2gTBJ2EZsdGnjeL4v5YUyESsqZVT4AYQ5wFKiZZCORzuI2GDNlse7uPISjKKCwBvjAGJ2JUvj2dRkhwPgEC6KwSHpGhaE6IBjDuLotDUA4OAMIJPgYqCJhgQRUHKGY7bBCV4GQYsiDxSYdg6YRQaJWwHAgJgOB4EucACDQ9CMMwPBsAAulQqJoG+CAoJwPU8FgNiEJI0D4PwlAgCm5A8CQxCKHAiDLNQuhoAVtAhP1S4KIsS0bKtUCLMo+DPQAzLdy0PetA3EBiLZ4BtrBjawQA).

**Comment by justb** [comment]
@pygy OK, thanks. So the "key" is the symbol that distinguish between two vnodes?

**Comment by tivac** [comment]
@justb Yep! There are docs on the mithril site all about keys.

[https://mithril.js.org/keys.html#what-are-keys](https://mithril.js.org/keys.html#what-are-keys)

**Comment by justb** [comment]
There is a question about the combination of components. In [example 1](https://flems.io/#0=N4Igxg9gdgzhA2BTEAucD4EMAONEBMQAaEAMwEskZUBtUKTAW2TQDoALAF0fmPSk6IBqECAC+RekxYhWAK2olIAoZxEA3TACcABAGEIjbAEYdAXh3AAOlHyZOmFFZDOiN6OSjlOKHaQCuUGCc5NAAFOpQEPiIAJTWUFacynBIrPAQAOZhzp7ezrE2Ojp4nAAq5MwQ-pxhAUEh4fGR0YisMA6CrHYOZgCy9uysWpi2hmGxANyMwwQjAO4TEsYADGuFUBLuUP7YPYi+9cGhUBMJxSkIbRnZAOS7+7cbW4mc6uSI84eBx+HqsZYijoklpEJx-FooDpGGFbvhyOpbkQdHD7I5bgBqTjscgwbpojbFMQ2YmJKCaXQGIwAJnMgNe70+3waJwiAPOwM4oPBkOhsPhiORt2xuJ0osgRmgqmpTyBpNJNgpOgA6iNsNhELoLAkkoyvn4fo1Tv96cUQWCIVCclDiraYXCEUigbbbepWGAcfB8KCoG4bS7ivaBUjocNql1MmCJrE-QG7bCAEY1TjQEMcuPFW7QMDwchgADWt2Zv1O7OdGcDYZqbVKsIA9NhMJHjHXMQNscNRvhxrFCRWdKSKy8K0lbgAFJuIYy3csumOz+O3JOcFNQNMLl1ZoK5gtFg0spqm-vFHEdCBaACerATmALEw3tsHGeHGdHACFb4WH325+W+-KbEVbQdAnZs6R1N4Pn1I4jQiKIYjLf0dEuNIbjg1pWHsLkYD7c0eShGFVRwDUtGRGgYSpExkWAfNEAvXwWhiTCVy0PFyHwMQYwowxsGpWIAF1YjrOsRRgHRcygRA5RJQCoBmLRw0QMJuzAfxmAEa9ogvZFnAbScW2MVx6SSXTG2bOsUHY5xfFAqc-U48RJBABhmBEd0YEUfhBGENBxH4kgJPzagUDoZzpBERhvHYLRKHkTyIV4NAuE4XAUGEsB8CgTSIGSDz3UMOtIuxGL4DrYxWHKgBmQqopKuK+E4C8NREBQ-LEIA), no problem, but in [example 2](https://flems.io/#0=N4Igxg9gdgzhA2BTEAucD4EMAONEBMQAaEAMwEskZUBtUKTAW2TQDoALAF0fmPSk6IBqECAC+RekxYhWAK2olIAoZxEA3TACcABAGEIjbAEYdAXh3AAOlHyZOmFFZDOiN6OSjlOKHaQCuUGCc5NAAFOpQEPiIAJTWUFacynBIrPAQAOZhzp7ezrE2Ojp4nAAq5MwQ-pxhAUEh4fGR0YisMA6CrHYOZgCy9uysWpi2hmGxANyMwwQjAO4TEsYADGuFUBLuUP7YPYi+9cGhUBMJxSkIbRnZAOS7+7cbW4mc6uSI84eBx+HqsZYijoklpEJx-FooDpGGFbvhyOpbkQdHD7I5bgBqTjscgwbpojbFMQ2YmJKCaXQGIwAJnMgNe70+3waJwiAPOwM4oPBkOhsPhiORt2xuJ0osgRmgqmpTyBpNJNgpOgA6iNsNhELoLAkkoyvn4fo1Tv96cUQWCIVCclDiraYXCEUigbbbepWGAcfB8KCoG4bS7ivaBUjocNql1MmCJrE-QG7bCAEY1TjQEMcuPFW7QMDwchgADWt2Zv1O7OdGcDYZqbVKsIA9NhMJHjHXMQNscNRvhxrFCRWdKSKy8K0lbgAFJuIYy3csumOz+O3JOcFNQNMLl1ZoK5gtFg0spqm-vFHEdCBaACerATmALEw3tsHGeHGdHACFb4WH325+W+-KbEVbQdAnZs6R1N4Pn1I4jQiKIYjLf0dEuNIbjg1pWHsLkYD7c0eShGFVRwDUtGRGgYSpbBqRjCjDBMZFgHzRAL18FoYkwlctDxch8DEWIAF1YjrOsRRgHRcygRA5RJQCoBmLRw0QMJuzAfxmAEa9ogvZFnAbScW2MVx6SSXTG2bOsUB45xfFAqc-T48RJBABhmBEd0YEUfhBGENBxH4kgJPzagUDoZzpBERhvHYLRKHkTyIV4NAuE4XAUGEsB8CgTSIGSDz3UMOtIuxGL4DrYxWHKgBmQqopKuK+E4C8NREBQ-LEIA), it doesn't work. I just switched the sequence of two components, what is the reason for this?

**Comment by barneycarroll** [comment]
Hi @justb, I appreciate this issue is really old - answering here for posterity. The problem is with how Mithril works with `key` attributes. `key`s can be used to reinitialise components like you're doing here, or move them about relative to each other and keep their identities discrete. Mithril can handle sequences of nodes without keys and sequences with keys, but it can't handle mixtures.

In your first example, the first node in the sequence has a key, and everything works as expected; but in the second example, the first node has no key - Mithril assumes an unkeyed sequence and fails to deal with `Comp1`'s changing `key` as expected.

The solution is to start a new sequence whenever you want to shift between keyed and unkeyed sequences: by wrapping your `Comp1` invocation in an array, Mithril now sees 2 sequences: one unkeyed wrapping sequence containing 2 items - `Comp2` and another fragment; and the latter fragment, containing only `Comp1`.

Before:
```js
m(Wrapper, 
  [                             // Single sequence...
    m(Comp2),                   // ...determined to be unkeyed...
    m(Comp1, {key: v.attrs.id}) // ...and now we have a problem!
  ]
)
```

After:
```js
m(Wrapper, 
  [                               // Sequence 1...
    m(Comp2),                     // ...determined to be unkeyed...
    [                             // Sequence 2 (an unkeyed item in sequence 1)
      m(Comp1, {key: v.attrs.id}) // ...determined to be keyed, problem solved!
    ]
  ]
)
```

[Here's the fixed version of your second example](https://flems.io/#0=N4IgZglgNgpgziAXAbVAOwIYFsZJAOgAsAXLKEAGhAGMB7NYmBvEAXwvW10QICsEqdBk2J4AbhgBOAAgDCtLAAcAjNIC804AB00AEwzEMiLSBMUd9CGgjFE0sAFc01YhHoAKMWlq6YASm00LWIhOFpYfChaAHN3EysbEz8daWk4GGIAFQgcWgdid0dnVw8Arx8YfDhDRnx9QzUAWQNCfEkMPQV3PwBuLDaYXXaAd272ZQAGKeS0dgs0B0V6mDsilzc0bsDU0PDKqNiAckXlw5m5oOIxCBhh1ad1jzE-TRTpYMkMh0k0aSx3Q66CBiQ4UaSAgxGQ4AamIhAgcDqkJmqVYOjRQTQEhk8iUACZ1K9LtdbvdihtPC9tu9iJ9iN9fv9AcDQeC4QjpBy6Ep6CI8Wc3hiMTpsdIAOrtRSKGAyDSBYIku72B4lTbPImpD5fH7SOK-VIGplAkHmfUGg1ifDUeFQIZMU3m81Gllg-qSPK1aIZbp+B2O1JMgBG+WI9FZ1P9qUO9GoUAg1AA1ocyY9NlS3pHDW0PZV0gVDgB6RQYL3KAsw5pwtodXRdPwozPSDGZi6Z4KHAAKJZgykOGcdvv7ToBweIobQ4aHjujzjjieTyvJpQ1jdS8OqtEkAE98IGMInulPzc3I63I+2AEL7pNH6QN833u+C9E6EVSaRd0uE+VXG5Ktaqp43i+OmZrSLsEQHEBFT4AYtJwA2Wr0jq-wShgUoymCyD-Liih4r62HuLhyhgsACYwFudjlL4sFjpIiIQLorB+AAuixfgFgW7JwNIcZoDAz6zK+aBujm7i1tQDg4Awu4+FuYImEW3ZlsoZhEsEinFqWBaIIxJh2J+PamsxlAgOksCpggPAACwAByIAAbAArGwHAgJgOB4FacACDQ9CMMwPBsCxVB8QmVmoO5XB4FgNiEJI0D4PwpnfOQPAkMQihwIgnHULoaCybQIQ+VaCgFrFcIJVABbKPgtUAMzlXFVVJb5xBbtKeDJawLGsEAA).
