### ISSUE TITLE
`onremove` called multiple times for elements taken from recycle pool

### ISSUE THREAD

**Issue by purplecode** [MithrilJS/mithril.js#1990]
## Expected Behavior
`onremove` should be called only once after every `oncreate`

## Current Behavior
`onremove` can be called multiple times for recycled elements. Every time when element is withdrawn from recycle pool: https://github.com/MithrilJS/mithril.js/blob/next/render/render.js#L188-L190
it is added to old list of elements without any special treatment. In case when it is not used for the second time, the `onremove` is fired again.

```html
<!DOCTYPE html>
<html>
<script src="https://cdnjs.cloudflare.com/ajax/libs/mithril/1.1.4/mithril.js"></script>
<body>
<div id="root"></div>
<script>

const Item = (id) => {
  const oncreate = () => console.log(`oncreate: ${id}`);
  const onremove = () => console.log(`onremove: ${id}`);
  return m('div', m('div', {oncreate, onremove}, `${id}`));
}

console.log('rendering:', [1,2,3]);
m.render(window.root, m('div', Item(1), Item(2), Item(3)));
// oncreate: 1
// oncreate: 2
// oncreate: 3

console.log('rendering:', [1,2]);
m.render(window.root, m('div', Item(1), Item(2)));
// onremove: 3

console.log('rendering:', [1]);
m.render(window.root, m('div', Item(1)));
// onremove: 2
// onremove: 3 -> fired second time

console.log('rendering:', []);
m.render(window.root, m('div'));
// onremove: 1

</script>
</body>
</html>

```

## Possible Solution
Add a flag to recycled elements, that would allow for special treatment in case when they were taken from recycle pool, but not used.

## Steps to Reproduce (for bugs)
As in the code snippet.

## Context
I have to set in `state` a flag that indicates that the element is removed for the first time after `oncreate`. I'd rather see that as a part of library.

## Your Environment
* Version used: master
* Browser Name and version: all
* Operating System and version (desktop or mobile): all

**Comment by pygy** [comment]
@purplecode thanks for the report, I need to think about this a bit more (and it's getting late here). I have a pending patch that fixes other issues with the pool and that introduces a boolean flag (`vnode.reuse` if memory serves well), to determine whether a vnode is eligible for the pool when it is removed.

That flag is `true` by default and set to `false` before the hooks are called (except `oninit`).

Not sure if we can also use it for that purpose... I don't know the intricacies of `updateNodes` by heart and it's too late now for me to dig in.

**Comment by pygy** [comment]
@purplecode I think we can solve this by adding `var oldLength = old.length` before the pool is concatenated, and pass `Math.min(oldEnd + 1, oldLength)` to `removeNodes` instead of `oldEnd + 1`.

It [fixes your repro](https://flems.io/#0=N4IgtglgJlA2CmIBcBGADGgNCAzvBAxgC7xTIgAWRRADjkgPQMCuAdjQNYDmAdAQPZgGkIhQBOEWAAEUPWQFZhEURNg8AVjhDYAZpPhakAbVCsAhmERIQPKmFjaQA1iRfkAPFAgA3AATQAXjF+fiIAPncGL28wkABfTFMLKxtNR2dXInJnHCJfAEkSMF8A3wAKaABKErDfYAAdVl9fHLz+VgIxeDMSEvLqgNqc-gQeWH4uMoADds7ukiRfABJgaDipyoBuRubW33ausH5veD6ygaH2nBH4MYnpg-gjk8WVtY3tpt8uomYxJrAZQA5NEgZhfICQT4wXVZl0evBwY9nvAEr4pm8oOtKltGnFGo1hqNxpMgV1WFB4BJWFwkDCjChMAAmTAAZgAurjWGAeOTKWIygB3CAU-iC3khIjgyGg8GFJ5lFCVOVFMpM5UFVWsnFcpj7Drwha+FCNPVw+bwRZM00MfVzBGLVm+AkdK43O6kvlUkW0+mMpmcz48r0C4Wi8XBULS4GyzUKpUqhXqnGfM2sQ7HS2+Vkuom3EnAkM+unghmBxrB+AUqlCkVQMUSqMQmPQxOApUpm36jMvXzW1hpntZp0AWlqei6UF8eGcU6IEEsubdxPuZKr-OL9PL3N565rYfrEcl0ah3iBnYHtuRmcWKHiiRA5ks5D4OC02AyVay1ni7OwsBFDhDBMR9knIERxEkRw-gcawqFoegmDYTheAEIQINUGQ5B4RQMMkDR3xAIgAE8aBSNJsBoHoCAoAxkCMBisBAeBfn+AkiHqDiuPxVgQD-IwR0ZEBOJEog4j4zAGWwZoZN8HjZOabwzDEfZYCgAAZKsuFEPoRigMYtNECSjCY9jRK6AhiIIADeL-JkAA5MAANgAFkwFAAE4XNZLBPO8tB+JM7AoAAZSIZSpV8YyhIAWR6CgeEgVgymMpi9IAUQpXwAGoJJQJzmXkZkmSZJyWRK0qA0koKQDKDKsuy41sH4oTVI0wyKGVVLpO8Vh+EpHBKjMsSJKZNzWQKiqAHZHOm+z2XZOJFqAA) (I've patched Mithril accordingly in that Flems), but I'll have to review the various branches to make sure it covers all bases.
