### ISSUE TITLE
Make old documentation less visible

### ISSUE THREAD

**Issue by cjh9** [MithrilJS/mithril.js#2028]
I'm currently learning Mithril, and I always end up in the old documentation site. Perhaps we should make it less visible to google?

![screen shot 2017-11-27 at 3 04 35 pm](https://user-images.githubusercontent.com/18718330/33270512-9b9c5054-d384-11e7-8133-8651b6e15657.png)

**Comment by pygy** [comment]
Hi @cjh9 Looking for props will off course lead you to the old docs, that API has been deprected in v1+ and is only mentioned in the migration guide now...

I tried a few other Mithril-related searches and always go the new docs as first result...

That being said, as suggested in @2013, we could add a banner in the old docs alerting users of their obsolescence.

We didn't do anything for the old docs to rank high, AFAIK, we even broke old links when v1 was published, killing some of the google juice. All we could do would be to add a `rel=nofollow` to the archives link in the new docs, but it would not be a good idea IMO.

**Comment by jeanrajotte** [comment]
Expanding a little, here, what would make most sense to me is if all pages were clear about their contexts and there be links to the others, as simply as possible:

eg.

Head:  This is the latest stable Mithril, vX.X.X.  Archives `here`.

Others:  For the latest version of Mithril (vX.X.X) go `here`.

I'm still on 0.2... and do need ready access to those docs.  I end up tripping all over the new stuff in Searchland.  :)

Also, there's [an article that was easy to find](https://www.codefellows.org/blog/introducing-mithril-js-a-new-javascript-mvc-framework/) which points to Leo's github for Mithril and to his //todo: blog, which too points to the old mithril site  (http://lhorie.github.io/mithril/)-  which is no more (404), so that's a bit of a thud when you're trying to make your way to the good stuff.  Could http://lhorie.github.io/mithril/ be made to redirect, somehow?

**Comment by isiahmeadows** [comment]
@jeanrajotte For the "others", it's already being addressed in #2029.

**Comment by jeanrajotte** [comment]
Thanks.  

Additionally, I for one would appreciate if there were a link to archives like https://mithril.js.org/archive/v0.2.2-rc.1/index.html in README.md .
