### ISSUE TITLE
Allow children to be specified as a single function returning a vnode tree

### ISSUE THREAD

**Issue by isiahmeadows** [MithrilJS/mithril.js#2050]
## Expected Behavior

This came up on Gitter in a discussion there.

Basically, I'd like to see this to happen:

- If a child is a function, it should *not* be normalized.
- Only one child is allowed in this special case, as it replaces `.children` altogether.
- DOM vnodes do *not* support children as functions

## Current Behavior

Currently, functions are just `toString()`'d, which is hardly helpful ever.

## Possible Solution

A few small changes to `Vnode.normalize`, `Vnode.normalizeChildren`, and `m`.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Context

This is to support reuse of child vnodes without actually requiring identity (which we all know is unsafe). It also allows children to be parameterized in cases like with [React's `react-motion`](https://github.com/chenglou/react-motion), and it'd make Mithril a little more useful for cases where you have to deal with animations/etc. (and other changing data independent of the global model state).

A couple other examples where this could've improved or otherwise affected API design:

- [`mithril-infinite`](https://github.com/ArthurClemens/mithril-infinite/tree/master/packages/mithril-infinite) could've opted to use children as a function instead of `before`/`after`.
- My [`mithril-helpers/self-sufficient`](https://github.com/isiahmeadows/mithril-helpers/blob/3de07dfb2f91e049ec6d17923d25855bcacb28d8/README.md#mithril-helpersself-sufficient) could've opted to use children as a function instead of relying brittily on inheritance and unsafely overriding hooks. **Edit:** [It currently does similar now](https://github.com/isiahmeadows/mithril-helpers/blob/05c14c2190ea0b28f71bfade09949c112e2b7ca3/README.md#mithril-helpersself-sufficient), but does so in a way that's slightly awkward.

Also, if you've ever used a pattern like this, this feature requests aims to reify and partially replace it:

```js
// Now
var List = {
    view({attrs}) {
        items = transform(attrs.items)
        return m("div", [attrs.view ? attrs.view(items) : items])
    }
}

m(List, {
    items: [...],
    view(items) {
        return items.map(item => m("div", ...))
    },
})

// Proposed
var List = {
    view({attrs, children = items => items + ""}) {
        items = transform(vnode.attrs.items)
        return m("div", [children(items)])
    }
}

m(List, {items: [...]}, items => {
    return items.map(item => m("div", ...))
})
```

## Your Environment

* Version used:
* Browser Name and version:
* Operating System and version (desktop or mobile):
* Link to your project:

**Comment by isiahmeadows** [comment]
Yes, if you follow React at all, this sounds a *lot* like their new "render props" fad. But it's not something Mithril users haven't been doing for a while through attributes instead. I just wanted to make a common pattern easier.

**Comment by pygy** [comment]
@isiahmeadows This would be a -0.1 from me, in that it doesn't add any functionality. `children` in components are mostly there to support JSX, overloading them doesn't seem that useful and adds complexity (more things to document, another thing to know about the framework when discovering a new codebase)...

This seems as clear as your proposal.

```JS
var List = {
    view({attrs: {items, render = items => items + ""}}) {
        return m("div", render(transform(items)))
    }
}

m(List, {
  items: [...]
  render: items => items.map(item => m("div", ...))
})
```

**Comment by isiahmeadows** [comment]
Okay. That's basically what I did with my `SelfSufficient` helper when I redid it. It's just awkward when it's a fairly frequently used utility. I'm considering moving it back behind a helper, though, to hide some of the nastiness. (I'll have better timings control, too.)

**Comment by cavemansspa** [comment]
this is a somewhat contrived [example](https://flems.io/#0=N4Igxg9gdgzhA2BTEAucD4EMAONEBMQAaEAMwEskZUBtUKTAW2TQDoALAF0fmPSk6IBqECAC+RekxYhWAK2olIAoZxEA3TACcABAGEIjbNFUB1cp3YAZcjE46AvDuAAdKDo87oYLYkyCUHQAKdSgIfEQASkcAPmdlOCRWeAgAcyCAcgMjEwFzSxs7FBRvX39EDKIdUPCoiTcXTmgAV2x8csCQsIjohzjgBIREZLTM7OMoMwtrW05ilrbyyuruuqIGqEb1ckQAd06antjnBs5GwaSU9KzDCamC2eLtveXDqNPG305mrXdGTPw5HUy1cmzO4Ma3ng5DAAGtOoh1Kpev0LsMrmNbrlOPkZkUSlAwNC4ctEcixB9OBIdDRKY1-hlAcCqsBYYgAJ6BACM1IyJgykXWYMa9IBQJBbM5OgATLzOLsIAKhSLwQymRKOYEAMxy9i+CqCuncMXM5ySwIAFl5pAgPyVRrV4pZ5p0AFZrUCDcrwQBdSKnClQQNuUjNQmccjQHQRSBacpBSA5SZ5aaFTjRUGUr4-dyZ8GeLyEsoBYJvFEnYUQzhokbXGMQOMBAk+PyCV6rf2VlV2dlIPTsSj4XxQLq1Tsqxr1SsFhbtEujo59CsT8E1jGMxCxjoE1pzipVMtGxo9vsD+BDoQL95dqnelXPfaljvHPMrtejDdbpsP9tjo+cbNfh0f5EzuFMHjsccq2DcFgzBUNw0jdwT0QftB2HK8M3-TRdDAM8L3cJw3lYfBDFYABHZpEC0dkAGVECQMAmi0ABBeB4BNAV-xYrQ43ZVhSC0QwE3w4dIgEhsAFFMDwoIggsKpyCgCIAA9y1fKtzmgRJ0VGCxWBQqCV2PThe0QeTOEU5TEDUnR-zEKCYIQpikJ0FCLKs1SMx0chSHk6yVJ0ABSGVon0lDWAAIxk2FUiEsN8AMFJdCcDI4o5DIdEDOC3BwnQABFNwbcpEqxZMcVTWZHGjIrG3M8ZsVxNNO0YVhGFtAQglIsBmmYAQovCdkWTcAsH0CZyI2gTCKwLAtAL+TiqlpdxZtW-5Cq-AgGvKprZiMzg-RGzxssicRJBABhmBEVgwBgRR+EEYQ0HEH0SGhKBYWoFA6Au6QREYaYtEoPgfl4NAuE4XAUAAemhsNsFim7DGhgHLCB+AAAEuVYbGADYUcByh5Hu0zsBkBQXrEIA), but is there a recommended decorator pattern to augment a component that has children?

the use case is to let a user defined component be left intact, but let's say we want to provide a way decorate a component with functionality via a 3rd party util.

**Comment by isiahmeadows** [comment]
@cavemansspa There's a `view`/`render` attribute, and there's higher order components. Note that higher order components don't compose very well without issues (something the React community learned the hard way).

**Comment by pygy** [comment]
Re-opening this following #2106. cc/ @barneycarroll.

**Comment by barneycarroll** [comment]
I missed this when it was first raised and wished I hadn't. Since then I've put a lot of work in exploring 'function-children' components. I last left #2106 with the thought that this was an acceptable contrivance for authors of a very specific kind of component. 

But the more I think about it, the more I get @pygy's uneasy change of mood, and I'm more inclined to frame this as a case of the current vnode normalisation implementation being dangerously eager (as in WTF) on principle rather than the proposed use case necessarily deserving first class treatment (why shouldn't it?).

I've been racking my brain over a few avenues for resolving this ambiguity, and I think a couple actions should be taken:
1. Remove `.toString()` & `.valueOf()` from stream. I remember asking Leo to implement this feature, thinking "wouldn't it be nice to avoid typing those parentheses". In hindsight that was an example of very short-sighted enthusiasm for a clever hack. I've never used it and I don't think anybody has (or ever should!) document it.
2. Vnode normalisation should hold off on normalising the children of components. The children passed in to a component are fundamentally different to the children of any other kind of node in that the latter need to be interpolated immediately to get a recursive static representation of the virtual node in question: there is no other opportunity. In contrast, a component's children are a very different matter in that they may never be rendered. It's assumed they will be, but if when where and how is a matter for the component's view function. The decision to render whatever 'children' were passed in is deferred, and the contents of the view need to be normalised anyway — therefore, let's create an exception in vnode normalisation for the case of components that leaves children untouched.

I think that would also go some way to addressing Isiah's previously stated gripes with the contradictions of the documentation's advice on how to treat children. All in all we might all have been a bit guilty of condensingly paternalistism. The kids are alright.

**Comment by pygy** [comment]
I need to think 2) through, but at a glance, it looks like a good plan (for v2).

How is 1) related to this?

**Comment by barneycarroll** [comment]
Sorry @pygy I missed this response. I am about to file an issue regarding the specifics of point 1, which has since been revealed to be a bug in its own right.

It relates to this issue inasmuch as Mithril's vnode type is very tolerant of what input can constitute a vnode in part because it leaves the door open to complex types with `toString` or `valueOf` to be treated as text nodes without coercing them to text nodes in the intermediary representation. It is essentially a very generous fall-through which spreads reasoning about what the entity being normalized actually *is* through various different steps, none of which really take responsibility.

**Comment by isiahmeadows** [comment]
In light of some recent discussion on #2275, I'm resurrecting this.

**Comment by barneycarroll** [comment]
@isiahmeadows I think current v2 behaviour is good enough, personally. [Check it out: we can event do the neat-o React array destructuring thing](https://flems.io/#0=N4IgZglgNgpgziAXAbVAOwIYFsZJAOgCsEAaEAYwHs0AXGWvKtOGgAgAUAnSrCOGTqwC8rAG7CAfK2AAdNK1ZMWrCGxGz5C1gAd6AEwhoA5q0SsanAK4wScra340asPadZgMUfrc0BfO6wBXDx8MPic8JRQojAAFKL4GE6ccPja3Lz8AJQBCvg0ABb0sblaEXCWUGpSGvb2APIARoQw5DSJcHAQRmixqiTSpXWs5ZU0PsP2FeTk8HBuFtYTk745mva+y-ZDIzAtbRDUkoPrdU377Rid3b39J5Nle600h2hbkxEXMK5mizY7ClWO02pTW9nwkEwUCgAE9YrEssdamdms8Ol0en1xvdJro0AZjG4PF5-qcpjAnC4FlZScMgWTAgyIGB4olkqlyJ4oI0MOQANZgyYJJIWDlcnn82LAVj4WWqVj04Y7GAkgGsLDhb6cDAAdwRpUVjIUERolk48mRClEEBgOrMUvIBWgegiaDMyGttoAuqtJDtPXrpbL8PLVst-GgI3INVhKJZaLE9JRyJYcLR8I1KHoYQNkQH7YihFJSlhYsFMgJczt0iF+AXjmhbRwMqF4TD4AM0JRCzU1Y4ACoQHBxmixACySQK4Qw+J4CNYUnwAFZWAB+Vjt+ZmLsDACMMAATIKNll3iCGVK8QSjANprNOr6i2rSwBybQvgZq+xXwwmL9ro0Hi0F8ABlKAwa9gxff9EH-BQ7zmf9Vzg1gXwAZUsGY5gAQmghl7Fg-C6hfAAxDBoDNGBTFiPCHlPUEfFWEAyH4WADmoBBEBAABmAA2RAAAYAFpuIAdkEkBfC9MgoEMPlONQEBMBwPBeEKThoAAAUbAAPGhmJAM0oDwAonG0OBEAAeks+NtD5Ix8CoLBLLUgoNKgTSD3wATvKEzhyHwXcXNUNzoCIUgQBoGFdDwOByA07R9Kk3wgA)!

```js
const ViewComponent = {
  view: ({children: [view]}) =>
    view('Hello!'),
}
```

**Comment by isiahmeadows** [comment]
Yeah, since that works, I'm closing it for now. I've got ideas in #2279/https://github.com/MithrilJS/mithril.js/issues/2295#issuecomment-439846375, but I'm closing this in favor of what turns of that.
