### ISSUE TITLE
Some attributes need quoting for IE9

### ISSUE THREAD

**Issue by gi-john** [MithrilJS/mithril.js#2056]
Mithril says it supports IE9, but there are some keywords that need quoting; for instance:

https://github.com/MithrilJS/mithril.js/blob/0ae9bc1ea35fdef616f43a451ddbdd632bbebf5a/mithril.js#L43

Happy to dig in a bit, but I have a feeling this would be a really quick fix for someone familiar with the codebase.

**Comment by pygy** [comment]
Are you sure this applies here?

IIRC, and according to kangax.github.io/compat-table/es5/, this is only true for IE8- (you must *"show obsolete platforms"* and expand the *"Object/array literal extensions"* section to reveal *"Reserved words as property names"* entry.

**Comment by gi-john** [comment]
Yep, unless I'm doing something totally bone-headed. That line I linked above fails in IE9 with the error "expected identifier". Typing `{default:1}` into the js console in IE9 gives the same error (at least the IE9 provided by browserstack).

**Comment by pygy** [comment]
@gi-john are you using it in standards mode? 

`<!doctype html>` should be the first thing in the document.

**Comment by pygy** [comment]
@gi-john it works in standards mode:

```HTML
<!doctype html>
<meta charset=utf-8>
<title>hello</title>
<script>
  document.write(JSON.stringify({if: 5, class: 6}))
</script>
```

http://bl.ocks.org/pygy/raw/7a0b3f282fa547da0bb0fcdc2024d644/, which is [valid HTML](https://validator.w3.org/nu/?doc=http%3A%2F%2Fbl.ocks.org%2Fpygy%2Fraw%2F7a0b3f282fa547da0bb0fcdc2024d644%2F) shows up propery in IE9 (via saucelabs)

![IE9 screenshot](https://screenshots.firefoxusercontent.com/images/88974bf4-e641-433d-9f32-94b0a880e1b9.png)

Stringified JSON is printed, but the source has bare keywords.

You're likely to get other issues anyways in quirks mode. Mithril v1+ is written in ES5, and I'm pretty sure that other features will be missing in IE9+quirks.

I hope this helps. Closing now, since it isn't a Mithril issue, but feel free to comment if you need more help.

**Comment by gi-john** [comment]
Ah, thanks much! Sorry to be a bother. This is what happens when they drag the backend developers out of the closet to pick up slack on the frontend.

**Comment by pygy** [comment]
No worries, the frontend is full of compatibility gotchas like this. You'll be eschewing quite a few by using a framework like Mithril though.

**Comment by pygy** [comment]
@gi-john also, feel free to ask for help in the [gitter room](https://gitter.im/mithriljs/mithril.js) it is full of people ready to help.

**Comment by gi-john** [comment]
Ah cool, thanks, good to know!
