### ISSUE TITLE
Turn m.trust into a component?

### ISSUE THREAD

**Issue by pygy** [MithrilJS/mithril.js#2099]
We could turn `m.trust(str)` into a component `m(m.Trust, {ns?: namespace}, str)` and remove the corresponding logic from the core renderer. This may or may not be a good idea...

```JS
m.Trust = function() {
  view() { return ""},
  oncreate(vnode){
    // replace the textNode with actual DOM (see createHTML in render/render.js).
  },
  onbeforeupdate(vnode, previous) {
    return !(vnode.children === previous.children && vnode.attrs.ns === previous.attrs.ns)
  },
  onupdate(vnode){
    removeTheOldElements()
    this.oncreate(vnode)
  }
}
```

**Comment by isiahmeadows** [comment]
@pygy Here's my thoughts:

1. How do you plan to handle the case of multiple nodes at once?

This comes up pretty regularly when parsing Markdown, for example.

This *could* be solved (completely?) by returning a fragment to the text node that 1. you immediately replace, and 2. you have `onbeforeupdate: function () { return false }` to keep Mithril from erroneously "updating" it. Mithril fires parent `onremove` hooks before child ones, so that helps dodge *that* problem. We could also compute the previous sibling when we go to update/remove, so we don't get too tied to Mithril's diff algorithm. However, this incredibly hacky mess leads to another question:

2. Is this level of side-stepping Mithril's algorithm okay?

This is more philosophical than technical. Mithril has in the past made it incredibly inconvenient to do some low-level things like rendering subtrees, but I'd say this is lower-level than even *that*, which raises a few questions. Should we be okay with something *this* low level, or should we be more careful and restrictive than that?\* If we are okay with it, we should probably also fix our node removal handling to properly handle fragments opaquely like this.\*\* (They should compute their first node before calling `onbeforeremove` in this case.)

3. How would non-string children work?

Making it a component would open the possibility of allowing child components to be used within it. Should we keep that door open and allow it (we *should*, in this case, provide an extra primitive to resolve and diff a tree *without* rendering it to DOM), or should we shut that down from day 1?

-----

\* Currently, for similar reasons, [I have to lock my `SelfSufficient` helper to just DOM nodes](https://github.com/isiahmeadows/mithril-helpers/blob/master/docs/self-sufficient.md), but this + a new option to render with a start node nodes would enable me to start supporting things like text nodes, fragments, and other similarly dynamic stuff.

\*\* [The relevant function is already broken](https://github.com/MithrilJS/mithril.js/blob/next/render/render.js#L566-L605) in the case where both `attrs.onbeforeremove` and `state.onbeforeremove` return a thenable and one of them calls `resolve` or `reject` twice, both synchronously. This could be exploited via `m(Foo, {onbeforeremove: () => ({then(resolve) { resolve(); resolve() })})`, where it would end up calling the component's `onremove` both before and after `onbeforeremove` and trying both times to remove the component's DOM.

**Comment by pygy** [comment]
@isiahmeadows these are good points. 1 and 2 can be addressed, but a trusted node in a larger list could be problematic (because `vnode.domsize` adjustment would lag, which would be problematic when nodes in the list can be toggled or re-ordered, once again, it could probably be worked around, but it would be terribly hacky).

re. onbeforeremove, the docs mention a Promise, not a thenable, so I'd assume a Promise A+ compliant implementation is implied. Are there thenables that call their onFulfil /onReject more than once? When it passed a callback (during the v1 beta), `onbeforeremove` was handling those cases gracefully, but that code was nixed because Promises offer similar guarantees...
