### ISSUE TITLE
Removed nodes stay in the DOM after m.render

### ISSUE THREAD

**Issue by just-boris** [MithrilJS/mithril.js#2105]
## Expected Behavior

The following sequence of renders should show only one button

```js
m.render(root, m('a', {}, 'content'));
m.render(root, m('a', {key: 'my-key', oncreate: () => {}}, 'content'));
m.render(root, m('button', {}, 'content'));
```

<details>
<summary>Full example</summary>

```html
<html>
<head>
  <title>Mithril test</title>
</head>
<body>
<div id="app"></div>
<script src="https://unpkg.com/mithril@1.1.6/mithril.js"></script>
<script>
  const root = document.getElementById('app');

  m.render(root, m('a', {}, 'content'));
  m.render(root, m('a', {key: 'my-key', oncreate: () => {}}, 'content'));
  m.render(root, m('button', {}, 'content'));

</script>
</body>
</html>
```

</details>

## Current Behavior
Currently the old `<a>` node stays in the DOM, but it is not expected.

## Possible Solution
The node recycling doesn't work well, and doesn't recognize that older `<a>` node not used anymore.

## Context
I have a component, based on Mithril. It re-renders itself based on some properties provided. When it receives certain order of properties, it doesn't remove node, so you see old and new buttons at the same time, which is obviously breaks UI.

For a workaround I currently assigned absolutely unique keys on every render. It seems to work, but kills all benefits of using Virtual DOM and Mithril in particular.

I have also found https://github.com/MithrilJS/mithril.js/issues/2024 that looks anyhow affecting this behavior

## Your Environment
* Version used: 1.1.6
* Browser Name and version: tested at least in latest Chrome and Firefox
* Operating System and version (desktop or mobile): destop

**Comment by tivac** [comment]
If you render without the `key` it [works correctly](https://flems.io/#0=N4IgZglgNgpgziAXAbVAOwIYFsZJAOgAsAXLKEAGhAGMB7NYmBvEAXwvW10QICsEqdBk2J4hcYgAIATrVpSAvJIAmtagFccDfACNaygJ4BuADpozWfNKbKY0gBSz5FSVnsByDO5fB2k90KMDO4AlCGmaJbWaLYOTsQubp7eksD01NYYjIiS9iGSCgB8qax+AfRBxKHhFlY2do5yCa4eOurExPQpvi7lwsFhRmwcIJg4ePjUcAI0FSIsrAC6VFAQaADWCCic4zxYEMSE0tCUIOrS5DwkxAAOcIgA9A-qaDfrAOaTtFgP+4fHUAAAgBGfCggBsvwOR2g+H4p2IBhu3BA8KWrCAA). 

```js
m.render(root, m('a', {}, 'content'));
m.render(root, m('a', {oncreate: () => {}}, 'content'));
m.render(root, m('button', {}, 'content'));
```

I'm sure it's another weird edge-case around keyed vs unkeyed nodes so #2024 is likely the correct related issue.

**Comment by pygy** [comment]
This is actually fixed in [next](https://flems.io/#0=N4IgZglgNgpgziAXAbVAOwIYFsZJAOgAsAXLKEAGhAGMB7NYmBvEAXwvW10QICsEqdBk2J4hcYgAIATrVpSAvJIAmtagFccDfACNaygJ4AdNCaz5pTZTGkAKWfIqSstgOQZXT4O0muhjBlcASiCAbhMzCysbezliJxd3T0lgAGsYA0RfLAMAWnSDZPpqSwxGLNsgyQUAPhTWHz96AOIAJmCwiLRzSzRrOwd45zcddWJiemTvJybhBgBmDtC2DhBMHDx8ajgBGmaRFlYAXSooCDRUhBRODZ4sCGJCaWh8fkoQdWlyHhJiAAc4IgAPRA6jKNAWDAAdwA5g8trQsECALIPJ7QABSAGUgfdHs8oK84EDWvMYDoYK0wAAWAAc81pGAAnAAGaitVoANh0YFptIAjMpefNqRgAKxM6n8sVgTkAdhgYH5uLRBKJ72IBj+3BAb2OrCAA).

**Comment by just-boris** [comment]
Does the `next` brach contain next major release (2.0) or it will be published as a minor update?

**Comment by pygy** [comment]
As is `next` is `v2.0` WIP, but we do backport some patches into `v1`. I'll have to review if that fix is suitable for a backport.

**Comment by litek** [comment]
I have a similiar issue which breaks [without keys on subsequent renderings](https://flems.io/#0=N4IgZglgNgpgziAXAbVAOwIYFsZJAOgAsAXLKEAGhAGMB7NYmBvEAXwvW10QICsEqdBk2J4hcYgAIATrVpSAvJIAmtagFccDfACNaygJ4BuADpozsKRklKAFAEobAPklZ80pspjTbs+RVdbAHJlCAA3IIDkM0lAoMIARkjJIIB5NBgg+woYuMIAJmSggBUAd1osnLRYrGDQiKjcmuDCAGYi4sIPTPtcgF1etAH7U3M0S0kdG0kHZ1d3T29fOWIA2pDw5OjqvKSAtIzK3PX6ooAeeqcjnfWCjvLr5vj2-c7ux7yAFiKAMVp1aQfW4AVl+4R6ZmGZjMGFmAHo4ZJaABrMw6eGIlEwjFI1FodGOBGSNDyXFsDggTA4PD4ahwAQ0eiMZg8Nh9KhQCBoZEIFCcak8LAQYhdaCUEAA8g8EjEAAOcEQCPUaFlyIA5rTaFg4UKRdJoAABBL4Y0ANh1wtFUHw-HFxAMsu4IFtrD6rCAA). Looks like this is also fixed in [next](https://flems.io/#0=N4IgZglgNgpgziAXAbVAOwIYFsZJAOgAsAXLKEAGhAGMB7NYmBvEAXwvW10QICsEqdBk2J4hcYgAIATrVpSAvJIAmtagFccDfACNaygJ4BuADpozsKRklKAFAEobAPklZ80pspjTbs+RVdbAHJlCAA3IIDkM0lAoMIARkjJIIB5NBgg+woYuMIAJmSggBUAd1osnLRYrGDQiKjcmuDCAGYi4sIPTPtcgF1etAH7U3M0S0kdG0kHZ1d3T29fOWIA2pDw5OjqvKSAtIzK3PX6ooAeeqcjnfWCjvLr5vj2-c7ux7yAFiKAMVp1aQfW4AVl+4R6ZmGZjMGFmAHo4ZJaABrMw6eGIlEwjFI1FodGOBGSNDyXFsDggTA4PD4ahwAQ0eiMZg8Nh9KhQCBoZEIFCcak8LAQYhdaD4fiUEAA8g8EjEAAOcEQCOoyjQ7gwpQA5sLabQsHCALLC0VQABSAGU4UKRdIxfw4flWjAdDB8mBPgAOVqejAATgADNR8vkAGw6MCez0JZSR1qfDDAv2fBLAsChgDsMDACWtJrtUHFDOIBnl3BAEtYfVYQA). Please consider trying to backport this fix.

**Comment by barneycarroll** [comment]
This was fixed years ago
