### ISSUE TITLE
Select onchange requires redraw

### ISSUE THREAD

**Issue by yossicadaner** [MithrilJS/mithril.js#2118]
B"H

It seems for selects to work correctly require an explicit redraw. Shouldn't this be rolled into the api?

https://jsfiddle.net/yossicadaner1/0hoa4a26/16/

**Comment by CreaturesInUnitards** [comment]
@yossicadaner your example is broken, which is why you're not getting proper auto-redraw. [Here's a slight re-tooling](https://flems.io/#0=N4IgZglgNgpgziAXAbVAOwIYFsZJAOgAsAXLKEAGhAGMB7NYmBvEAXwvW10QICsEqdBk2J4hcYgAIJMAA4BGSQF5JyAAwV5AXQA6acVJmyATMtXIA5BlmzYFipIuyYGAE4WtDywHNX1mPaOtH5o3gFauvr0EtKMsgDMZsCS1rYwiKoWvjBMgRYAnjBQULQA7nmuMAAmHg7Obhk+lbkOFgBGMBBhHpKsenqwUnRYskl6kpIAbhAwpRkAFMASGIysAJTKAHyq4xOSWPMWcEUw1MT2u3uSwJdXUxhQAK7psSsw+EbyFLdX9NSEGFCLxgW2ur0YHziihUAGp3sQ3GFiPhJg9nr0fr1vmg7uD3p9lEoVI80FUYJA0NVJAAyan7Q60WTECD0QLJVFPF4kskUqnsRyyCDUADWFjW2Nxn3wWGs81ooIOFkZzNZDloazWt3Ft2WEIJAEIiZJueSIJSqjS6YrjrAzhccXcbg7cRznhldfi4sYJbjJH8AUCMiClNtkh7IXJTCp4YiYMjXSC+s69uxMeGjFGjSbeRbafSlUyWWg2fdORls2a+a1BSKxT6rhnkOmoVppbL5SH88qi4F1Zrk9rk83I5JDcTSabzZb8zbTud63snb7S268RGEgvfvoA2Eg6Cwwi9XFEtH8AjXEiUWjE5jU8mJsOEoTxzzK7mrQzC6qwQnyxOc1iApCqKg6SseTaHp6katjKshygqn4qsWaoalquyRBMehJnoWDSrQJLEPMVS0NQjw4Aw+BtLQVT5A4wyyGslA0LQIzQDArh4G0GAdOQVCzmcRYIDw8QACyIMYAAcbAcCAmA4Hg+DUHAAjMcIzA8GwnggFAZrCkJqCyVweBYBAxCEK40BMY8rjkDwJDELIcCIAA9M5JKyMK3iKSxzkmWZFlQAAAvI+AhQAbL5pnmdA+D8ExxD5M4eBxawWisEAA), which you'll notice chokes on the 3rd select not having values for grape or orange.

**Comment by CreaturesInUnitards** [comment]
Sorry, I should've been more clear.

It isn't Mithril which is failing to redraw as you think it should; your data model is incomplete, and your application doesn't gracefully handle the error conditions.

Sorry again — my re-tooling didn't do you any favors, because I was still using your incomplete dataset. [Here's a similar example](https://tinyurl.com/y934gbea) which doesn't have any conditions where making a choice breaks the app.

> Also, how's you undefined option different from the null fallback?

That's just a stylistic choice that helps eliminate error conditions; the newer example above is a more fully realized specimen. The basic thought:

1. first `option` should be an instruction of what to do (e.g. "pick a thing"), value `undefined`
2. once a choice is made, (and therefore the `select`'s value is no longer `undefined`, the first `option` should be `disabled`

This way the only possible choices are valid, and you can focus on properly handling your dataset.

In any case, this really isn't a Mithril bug.

**Comment by pygy** [comment]
@yossicadaner can we close this?

**Comment by CreaturesInUnitards** [comment]
FWIW (not much, but —) I say yes, in a vacuum or otherwise.

**Comment by barneycarroll** [comment]
Speak not into the vacuum — lest the vacuum speak also into you!
