### ISSUE TITLE
New Logo Proposal

### ISSUE THREAD

**Issue by LuigiBaute** [MithrilJS/mithril.js#2124]
Hello, I would like to colaborate with this project by offering a _free_ new logo proposal that suits better with the name of the project. I already have a few ideas. Let me know if this is of your interest. Thank you.

**Comment by StephanHoyer** [comment]
Hi Luigi,

first thanks for offering your service. We had this discussion [before](https://github.com/MithrilJS/mithril.js/search?q=logo&type=Issues), several times.

Feel free to do some designs but be aware that it might be a death march to get a logo change done :). Some of the people have strong opinions about the logo which is the initial one from the mithril creator @lhorie.

**Comment by pygy** [comment]
Hi @LuigiBaute, thanks for the offer. There's one big constrain on the logo:

> *The logo* **is** *the borromean rings*

— Leo Horie in the last discussion about the Web site design.

He was not flexible on that point, and I'd defer to him for that, even though he's not been around for a while.

**Comment by lhorie** [comment]
If it's something everyone likes, I won't be opposed to it :)

**Comment by pygy** [comment]
He's alive... errr.. Hi Leo :-)

**Comment by lhorie** [comment]
Hi! :)

**Comment by tivac** [comment]
@LuigiBaute I'd love to see a proposal. We've got enough active maintainers for a quorum so we can at least give you a decision one way or the other 😄

**Comment by LuigiBaute** [comment]
I'll start working on it, where can I contact you? Could it be Discord? or here at github? as you please.

**Comment by tivac** [comment]
Update the PR, or you could put something into gitter for more immediate feedback from folks.

https://gitter.im/mithriljs/mithril.js

**Comment by LuigiBaute** [comment]
![logo mithril bocetos](https://user-images.githubusercontent.com/36426974/38965459-ed70aa48-434a-11e8-88e5-4b4eea63f31c.jpg)

I'll gladly adjust it as many times as necessary, we could play with the colors or anything you like.

**Comment by LuigiBaute** [comment]
@lhorie @tivac @pygy @StephanHoyer

**Comment by danielbarion** [comment]
@LuigiBaute hello,

Can i give you a little feedback ? 

The actual logo:
![Mithril's Logo](https://mithril.js.org/logo.svg)

Is very clean; your logo idea is good but is a bit visually polluted.
The first logo colors looks great, but not with the M with the circles and the second (for me) is out of table.

Here is the suggestion:
I liked the colors of circle in the first logo (You got them from the official website, right?), and the color of Mithril + version looks good too.
I suggest you to stay with the circles clean or make a new logo from zero.

See ya; good luck!

**Comment by pygy** [comment]
I like the idea of intertwining the M with the logo, but the result is indeed visually crowded.

If you want to make the rings distinct (be it their color, or some other aspect), please look at https://en.wikipedia.org/wiki/Borromean_rings for an overview of how they are supposed to overlap.

**Comment by LuigiBaute** [comment]
@pygy  @danielbarion If you want I can take away the logo m I have no problem if you wish and feel comfortable

**Comment by dnErf** [comment]
![cropd](https://user-images.githubusercontent.com/9046077/39092332-6f5c53c8-45c0-11e8-81aa-85d3dcba3754.jpg)

just playing with paint .. 😀  Borromean with open rings .. it is connected and overlapping but loose and does not constrain ...

**Comment by LuigiBaute** [comment]
![logo mithril bocetos2](https://user-images.githubusercontent.com/36426974/39214525-bcc27ff6-47e2-11e8-9651-53ec8bc280b8.jpg)
what do you think of these modifications?

**Comment by lhorie** [comment]
I see you're trying to go for for a fantasy metallic feel, but I'm afraid bevel, gradients and serif fonts are somewhat dated design techniques </two-cents>

Generally, I think design trends right now tend to favor flat designs (see [React](https://upload.wikimedia.org/wikipedia/commons/a/a7/React-icon.svg), [Vue](https://upload.wikimedia.org/wikipedia/commons/5/53/Vue.js_Logo.svg), [Chrome](http://logok.org/wp-content/uploads/2014/12/Chrome-logo-2015-1024x768.png), [Microsoft](https://blogs.microsoft.com/uploads/prod/2012/08/8867.Microsoft_5F00_Logo_2D00_for_2D00_screen.jpg), [Uber](https://i.kinja-img.com/gawker-media/image/upload/evbue7vsyhqvrmiszp8l.jpg), etc)

Within those constraints, there are still different ways to invoke a material feel, e.g. via [text shaping](https://ae01.alicdn.com/kf/HTB1DWUFj_J_SKJjSZPiq6z3LpXaP/PALLADIUM-PAMPA-HI-ORIGINALE-TC-Sneakers-black-and-white-Classic-Canvas-Shoe-Ankle-Boots-Fashion-Casual.jpg_640x640.jpg) or [stylized letters](https://www.appcelerator.com/Titanium/). Another excellent example of a timeless flat design is the coca cola logo and its smooth flowy feel.

Although I originally used the borromean rings for their texture similarity to chainmail and the trinity connotation (for MVC, get it haha?), a new design doesn't necessarily need to keep them since that symbol is not unique at all in the first place. Please don't feel like you have to keep using it, as I feel that doing so might be hindering your artistic freedom.

**Comment by LuigiBaute** [comment]
Ok thanks, now I get where the logo idea came from. let me remake everything and start with the same point of view you had at the beggining to see what comes up! Cheers! :smiley:

**Comment by LuigiBaute** [comment]
![2](https://user-images.githubusercontent.com/36426974/39501987-ea37ded2-4d8b-11e8-8e0d-12a9a37256a8.jpg)
![logotipo mithril 1 1 6](https://user-images.githubusercontent.com/36426974/39502017-10dffc7c-4d8c-11e8-85d5-6ce99aa998f1.jpg)
What do you think?

**Comment by StephanHoyer** [comment]
For me it's still way too much. [this](https://github.com/MithrilJS/mithril.js/issues/1033#issuecomment-282626056) by @ludbek is still my favourite one.

**Comment by pygy** [comment]
I do like the addition of color in the simplest item, and the pseudo-perspective added by the inner ring (though you messed up the way the rings overlap, you had it right in the metallic version ;-)).

I like @ludbek's logo, but the link/chain metaphor is AFAICT already more in use in the wild than the three rings thing, which is thus more distinctive (though I only did a quick Google image search, I may have missed some key search term... `logo three rings`, `logo borromean`, `logo chain`, `logo link` is what I looked for).

**Comment by pygy** [comment]
They might as well grow on me, especially the second one.

I see massive support for the link-like logo, but I think it is too generic as well, especially in a Web context. @LuigiBaute do you mind if I re-open this, or are you done with the idea?
