### ISSUE TITLE
[Question] How can I prevent a video element being redrawn on a route change?

### ISSUE THREAD

**Issue by bentranter** [MithrilJS/mithril.js#2125]
In part of my app, I show a video. I want that video to keep playing after a route change. A simplified version of the code I have now is:

```js
var root = document.body

var video = {
  view: function() {
    return [
      m("video", {
        src: "https://www.w3schools.com/tags/movie.mp4",
        autoplay: !0
      })
    ]
  }
}

var view1 = {
  view: function() {
    return [
      m("h1", "View 1"),
      m("a", {
        oncreate: m.route.link,
        href: "/page-2"
      }, "Next"),
      m(video)
    ]
  }
}

var view2 = {
  view: function() {
    return [
      m("h1", "View 2"),
      m("a", {
        oncreate: m.route.link,
        href: "/"
      }, "Prev"),
      m(video)
    ]
  }
}

m.route(root, "/", {
  "/": view1,
  "/page-2": view2
})
```

## Expected Behavior

When `page-1` is drawn, the video playback begins as expected. When I click the link to visit `/page-2`, the video playback should continue uninterrupted.

## Current Behavior

When `page-1` is drawn, the video playback begins as expected. When I click the link to visit `/page-2`, the video playback stops, the video is reloaded due to a redraw, and playback begins again from the start of the video.

## Steps to Reproduce

See [this fiddle](https://jsfiddle.net/dqcx1ffx/5/).

## Your Environment

* Version used: Mithril.js 1.1.6

**Comment by tivac** [comment]
You might be able to add an [`onbeforeremove`](https://mithril.js.org/lifecycle-methods.html#onbeforeremove) and prevent the `<video>` element from being removed.

You could also potentially use a [Layout Component](https://mithril.js.org/route.html#wrapping-a-layout-component) with a RouteResolver to keep the component around, since it will be diffed on route change instead of being torn down.

Neither approach seems perfect, but I'd probably choose the second option.

**Comment by bentranter** [comment]
Thank you both, using RouteResolvers with render functions works perfectly for what I'm doing.
