### ISSUE TITLE
Suggestion: Have m.withAttr return the result of the function call

### ISSUE THREAD

**Issue by webketje** [MithrilJS/mithril.js#2127]
## Expected Behavior
`m.withAttr(fn)` should return the result of its evaluation

## Current Behavior
`m.withAttr(fn)` does not return the result of its evaluation

## Possible Solution
At `mithril.js` [line 1372](https://github.com/MithrilJS/mithril.js/blob/next/mithril.js#L1372), place a `return` keyword before `callback.call`.

## Context
For an example, see fiddle: https://jsfiddle.net/kevinvanlierde/ooh46g2d/. The fiddle shows an input component which uses an m.withAttr function that is used as a validator. Unfortunately currently this usage is not possible. A workaround involves passing the input value directly to the function, however this has an obvious drawback (e.g. if some custom input needs to be validated against another attribute). The event itself can also be passed in, but then you lose the convenience/ readability of the `m.withAttr` signature.

**Comment by webketje** [comment]
Further thoughts:
Is `m.withAttr` meant to be used merely as a convenience connector between mithril views and event listeners, or can/ is it ok its use be generalized to a generic prop/attribute selector?

I like the idea of being able to use `m.withAttr` as a pure function. It could also be used, for example like below:
```
const model = { hasSomePermission: false }
const component = {
  view: (vnode) => m('div', 
    m('input', {
      disabled: m.withAttr('hasSomePermission', (yesOrNo) =>
    })
  )
}
```

In the fiddle referred in previous post, it's trivial to hardcode `m.withAttr` in the `input` component, but there are couple of drawbacks:
- less flexible (all instances must validate against the same attr)
- less declarative (

**Comment by webketje** [comment]
Further thoughts:

- It's interesting that `m.withAttr` can also be used with non-DOM targets, as long as `e` has a `currentTarget` property, e.g.: `const addSelectedToBasket = m.withAttr('price', (price) => total.add(price)).bind({ currentTarget: selectedItem })`. This is interesting because developers/ teams might prefer not to read values from the DOM, but store them in and read them from a separate object. Unrelated, but it can also provide a simple base for a lightweight event system.
- I like the idea of being able to use `m.withAttr` as a pure function. Currently its output (return value) is not determined by its arguments (always undefined), and it is mostly used exactly as the opposite (i.e.  triggering side effects in state).
- Question is: Is `m.withAttr` intended to be used merely as a convenience connector between mithril views and event listeners, or can/ is it desirable its use be generalizable to a prop/attribute selector? I think there's a case for keeping its footprint small/ not subverting its purpose, but on the other hand it could provide a very simple, unified interface for accessing not only DOM element, but just any object's properties. 

@pygy Didn't see this would be a breaking change proposal, so when an event handler returns false, mithril does the same as `e.preventDefault`?

**Comment by barneycarroll** [comment]
@webketje the `return false` behaviour is native to `element.on${ eventType }` handlers. It's an early DOM specification that prevents default behaviour (before the event model became as functional as it is today). [Here's a plain HTML & JS demo](https://flems.io/#0=N4IgzgpgNhDGAuEAmIBcIB0ALeBbKIANCAGYCWMYaA2qAHYCGuEamO+RIsA9nYn6wA8JbgCdcAAjJIAvCPEA+ADp0l8QWToAHAK7wVatfACeWiDNhY4AawBG3AB4H98aTM279q+Mu9qAKqLGEpY2mgDmEvBWIVawdo6ckDAIZLxU6ACsqABMAOwgAL6E9Ews6BgAVlTEPHwQAujyuBi8sFBk8RIyEgAUAJTdChLAznVg3DAYUNzhvQDkzRKiEOFkYIgrSCEd8fP9KoUGdB56rXTtndbdfYMywyQMUJBJ0HCu6awAjLkAbEUAXUKQA).

I think you're right in identifying  `m.withAttr` as an API that is explicitly for side-effects — it exists purely as a convenience function to extract salient user input (usually `value`) and pass it on to the consumed function, which is the real focus. Because `m.withAttr` is designed for consumption by the DOM events API, that is where it's return value would be consumed.

I think the functionality you're reaching for would be more intuitively provided by a function that had nothing to do with Mithril core, since it's actually a very generic utility which as you suggest seeks to distance itself from the DOM/events API domain. [Ramda](https://ramdajs.com) has such a function, `prop`, which consumes a property key and returns a function which consumes an object: the return value of that function is the value of the property of that key on the object. [There's a decent explanation of the concept here](http://randycoulman.com/blog/2016/06/28/thinking-in-ramda-immutability-and-objects/).

The direction of this kind of approach to defining ways of intercepting properties and acting on them to produce new values tends towards a holistic attitude to application model architecture involving streams & lenses. Have you seen [Meiosis](http://meiosis.js.org/tutorial/01-hello-world-mithril.html)? Based on the direction of your thoughts it might offer the full package for the system you're hinting at (the author @foxdonut is a habitual character in the [Mithril chatroom](https://gitter.im/mithriljs/mithril.js))…

**Comment by pygy** [comment]
Adding to what @barneycarroll re. `return false`, Mithril v1 actually wraps the functions you pass to it, but the wrapper forwards the return value of your handler.

https://github.com/MithrilJS/mithril.js/blob/8d30578b9ea6c44a06849b80ac2b2b26c74ea51a/render/render.js#L583-L587

I'm not even sure it would trigger problematic behaviour in real world code, but some IDL getters return booleans (e.g. `checkbox.checked`), and Mithril streams return the value you just passed to them. I don't know the full DOM API, so I'd rather be on the prudent side.

It wouldn't be a breaking change in v2 since we won't use legacy handlers.

**Comment by webketje** [comment]
@barneycarroll Thanks a lot for all the pointers, the JS example, and the chatroom link. I definitely have to play around with 'the Meiosis pattern' (I've worked with Redux at work recently but it looks so much more elegant in plain js/streams in the video on the meiosis homepage). 

I side with barney's explanation for my further thoughts on using `m.withAttr` on any object: 
> it exists purely as a convenience function to extract salient user input (usually value) and pass it on to the consumed function, which is the real focus. Because m.withAttr is designed for consumption by the DOM events API, that is where it's return value would be consumed.

I didn't remention it in my second comment here, but a valid use case for `return`ing which does comply with the usage described (DOM events API), is like the one in the [fiddle](https://jsfiddle.net/kevinvanlierde/ooh46g2d/), where 2 attrs are combined into one function in the component. Which might still make it worth considering for v2, especially if there are no drawbacks.

**Comment by isiahmeadows** [comment]
We elected to remove `m.withAttr` entirely, so I'm closing this bug.

**Comment by webketje** [comment]
See https://github.com/MithrilJS/mithril.js/pull/2317 fror why m.withAttr was removed
