### ISSUE TITLE
mount Why are there two render?

### ISSUE THREAD

**Issue by yulei745** [MithrilJS/mithril.js#2189]
```
    m.mount(document.querySelector('#modal'), {view: () => {
        console.log(4444);
        return 'asldjfklaksjdf';
    }});

    m.mount(document.querySelector('#modal_new'), {view: () => {
        console.log(123);
        return 'fff';
    }});
```

The #modal view Why are there two render?

## Expected Behavior

```
console.log(4444);
console.log(123);
```

## Current Behavior

```
console.log(4444);
console.log(4444);
console.log(123);
```

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used: 1.1.6
* Browser Name and version: 
* Operating System and version (desktop or mobile):
* Link to your project:

**Comment by barneycarroll** [comment]
When you use `m.mount` or `m.route`, the contents are subject to [global auto redraw](https://mithril.js.org/autoredraw.html). This means that one cannot render without all the others rendering.

One of the key advantages of auto-redraw is that all your views are guaranteed to stay in sync, so you no longer have to worry about explicitly writing code to define the relationship between data points and the views that depend on them. 

Consider if both your mounted components depended on a `name` property, which changed value between mounting the first component and mounting the second. Without auto-redraw, the second component would show the new value while the second would continue to show the old value.

If you want to opt out of auto-redraw, use [`m.render`](https://mithril.js.org/render.html) instead of `m.mount`:

```js
    m.render(document.querySelector('#modal'), (
        console.log(4444),
        'asldjfklaksjdf'
    );

    m.render(document.querySelector('#modal_new'), (
        console.log(123),
        'fff'
    ));
```

**Comment by pygy** [comment]
That only occurs in the v1 branch, where `m.redraw()` is called internally after subscribing a component.

In v2, when called, `m.mount` only renders the current tree and subscribes the component to the aut-redraw system for further redraws (either implicit on events or explicit with m.redraw()), solving your issue.

**Comment by yulei745** [comment]
@barneycarroll 
I am talking about m.mount. For example, I have m.mount in several places.


```
m.mount(document.querySelector('#mount1'), {view: () => {
        console.log('mount1');
        return 'mount1';
    }});

m.mount(document.querySelector('#mount2'), {view: () => {
        console.log('mount2');
        return 'mount2';
    }});

m.mount(document.querySelector('#mount3'), {view: () => {
        console.log('mount3');
        return 'mount3';
    }});
```


The m.mount in the back of each mount will be re-rendered once every time. This is not unreasonable.

**Comment by yulei745** [comment]
see https://jsbin.com/madowec/edit?html,console,output

**Comment by pygy** [comment]
@barneycarroll IMO the view code shouldn't have side effects that affect the global state. So growing another tree in itself doesn't require one to redraw the whole app. At least it doesn't if you follow a SAM/meiosis-like approach where the view is a pure function of the state (I'm partial to that approach :-).

An alternative for `m.mount()` would be to have it subscribe the component to the autoredraw system, and schedule an async redraw. That would also let one call mount several times within a single tick without having the double paints that happen in v1.

**Comment by sjmik** [comment]
Just browsing through issues; based on @yulei745 's link, it looks like this is resolved in the latest version.
