### ISSUE TITLE
Allow space-separated attrs to bind one function to multiple events / lifecycle hooks

### ISSUE THREAD

**Issue by barneycarroll** [MithrilJS/mithril.js#2343]
### Description

Instead of 
```js
const handler = e => {}
const hook = v => {}

m('div', {
  onclick: handler,
  onkeypress: handler,

  oncreate: hook,
  onupdate: hook,
})
```

Allow
```js
m('div', {
  'onclick onkeypress' : e => {},

  'oncreate onupdate': v => {},
})
```
### Why

1. Increase expressivity, reducing the need for statements and increasing declarative power for scenarios when the same handler applies to multiple triggers
2. Reduce the cognitive burden of scope issues
3. Allow ad-hoc React-hooks-like flexibility with fully functional single-scope components

### Possible Implementation & Open Questions

1. Handler code forking can be handled via `event.type` interpolation. To enable lifecycle forking, a `vnode.phase` flag could achieve similar functionality.

### Is this something you're interested in working on?

Yes

**Comment by isiahmeadows** [comment]
BTW, I have major performance concerns here, particularly if it involves components' lifecycle methods, too.

**Comment by barneycarroll** [comment]
Yeah that makes me feel uneasy too. Is it the cost of querying every key for whitespace or the overhead of iteration on each match in particular?

**Comment by isiahmeadows** [comment]
It's the overhead of matching and inability to cache them. Also, there's
overhead in splitting and iterating the events, and the open question of
whether this extends to attributes as well (like `"checked data-checked":
checked`), which itself is a mild perf headache because of the complex
parsing it'd entail.

**Comment by ww9** [comment]
Hi @barneycarroll, thank you for submitting an issue related to the question I asked in Gitter. That's very  kind and proactive of you.

@fuzetsu [provided a userland](https://gitter.im/mithriljs/mithril.js?at=5c181bd6b4ef8202484ba4d2) solution to my problem which I'll transcribe here in case it helps someone else:

	const multiEvent = (events, handler) =>
	events.split(',').reduce((o, e) => Object.assign(o, { [e]: handler }), {})

	m.mount(document.body, {
	view: () => m('button', {
		...multiEvent('onclick,oncontextmenu,onmouseover', e => {
		e.preventDefault()
		console.log(e.type)
		})
	}, 'Button')
	})

Also provided a [working demo](https://flems.io/#0=N4IgZglgNgpgziAXAbVAOwIYFsZJAOgAsAXLKEAGhAGMB7NYmBvEAXwvW10QICsEqdBk2J4hcYgAIsAVyjEIAUQBuIyQF5JAChiqGcCpMIY0AE1gAnAJQaAfAB00kybpFx8cAA5QIxLQHIKfyt8CxhTGWoYLS1aQxgbdVtJAHkAI14YamJ8DDg4CABzNFjDYElkGABdRCMTcxgLSVYrMpbHRyx8LFoZBi1TWmoZHAZ8NNpTAE8yx2dlCBgAd1qtROSsALSZYmJ6QMlgOedJfDPZeSU9P396ah9qAGsKO-pGAA9SJhkXtB6ZOAwWiqCwHGB2Q7HE4ufCeMLXAAiMDAGDkfisUJO4losHwUFohR0+GIU08CUx7SczUM-gAQjs9mhgo4WpQQIDYNkIPQEDwAJyIACMABY2BwQJgcHh8NR8myhIxmDw2FUqD40I9eagJVw8FhfIQLNAAAJoGCfNkyCzkHgkYieOCIAD0Tr6nkehRltCwTv1xENJoATPgAAyhgC0Fmo+AAzL6DUaoPh+GySWS8HBqEbPKJWFVWEA).

I'm quite inexperienced with Mithril so, for what is worth, my uneducated opinion is that binding a single function to multiple events might not be too common and I'd consider supporting it only if performance and code complexity impact were very low.

Regardless, I'm impressed with Mithril and its community so far. The context of this very issue demonstrates a very welcoming environment.

**Comment by barneycarroll** [comment]
@ww9 all suggestions are always welcome! Thanks for participating — it's our collective exploration of possibilities that makes Mithril what it is.

**Comment by isiahmeadows** [comment]
@barneycarroll 

> It's the overhead of matching and inability to cache them. Also, there's
overhead in splitting and iterating the events, and the open question of
whether this extends to attributes as well (like `"checked data-checked":
checked`), which itself is a mild perf headache because of the complex
parsing it'd entail.

Remove the "inability to cache them" part. I thought about this part again and realized caching isn't as bad as I initially thought. I still have concerns about how high the overhead is for the dictionary access, and I'll need to iterate the string to ensure there's no spaces for the fast case where I don't have to cache.

I'm thinking this can be done separately for DOM vnodes (in `render/hyperscript.js`) and for components (in `render/render.js`), so we don't have to muck up the core renderer *too* much.
