### ISSUE TITLE
The mocks don't support custom elements

### ISSUE THREAD

**Issue by pygy** [MithrilJS/mithril.js#2347]
If we want to properly test getter and setter properties on custom elements, we need to have them supported at the mocks level. This isn't the case currently.

The way element are currently defined doesn't make then amenable to extension (in the OO sense), since the state is kept in the scope of the `createElement` function.

**Comment by isiahmeadows** [comment]
@pygy I'll most likely add it as part of implementing #2339, since I need support for pretty much everything mod `customElements.define`.

**Comment by pygy** [comment]
Another pain point with custom elements: we must deal with those that extend form elements in `setAttr` (the Chrome/cursor issues).

**Comment by pygy** [comment]
@barneycarroll a custom element that inherits from `<input>` and doesn't override the `value` setter will inherit the cursor issues in Chrome (at least I assume it will, I didn't test it).

It will result in user disappointment, since `<input>` elements work fine.

The "inputness" could be detected at creation time and tracked as metadata on the vnode.

**Comment by barneycarroll** [comment]
Oh God I see. That's horrible. Another nail in the coffin of homegrown DOM mocks IMO.

**Comment by isiahmeadows** [comment]
@pygy Those that extend built-in elements are supposed to use `<form is="my-form">` and similar, not `<my-form>`, and IIUC browsers won't render them as customized built-ins without `is`, either. That's the main difference between "automomous custom elements" vs "customized built-in elements". (FWIW, [only about 2/3 of users support both](https://caniuse.com/#feat=custom-elementsv1), compared to almost everyone not using IE or Edge who support autonomous custom elements.) But because they have to use `m("form", {is: "my-form"})`, our workarounds do in fact apply to those customized built-ins as well. We just need to pull the `vnode.attrs && vnode.attrs.is` condition out of [this check](https://github.com/MithrilJS/mithril.js/blob/next/render/render.js#L771).

**Comment by dead-claudia** [comment]
Closing due to age.
