### ISSUE TITLE
Passing an object with a key of `tag` to a Component leaves the Component with an empty `attrs`

### ISSUE THREAD

**Issue by nickolasgregory** [MithrilJS/mithril.js#2414]
### Mithril Version: 2.0.0-rc.4

This [flems.io](https://flems.io/#0=N4IgZglgNgpgziAXAbVAOwIYFsZJAOgAsAXLKEAGhAGMB7NYmBvEAXwvW10QICsEqdBk2J4hcYgAIAKvGIBhWlgAO9EZIC8k4AB00kyQDcIMAO6Ij+jQD5tegwfG1Y+KLQDmACh0gMxYgBOcJqSPhSW+H6BcACU9g5OLm5ePtSE0AAmAUwhYRFpmdlocfoO2cQArgH6yPEOklieAORwyhhoTeGGaJH+QfjEGO4x4QD0o5JFXA0wdQ6NLW0dXT1R-Vi02SX1ALrxrHoHaHpY+BsVDJ4ZtNQVOAz4AEa0GQCe4bqlxmYW3Zq2tVKBgWrXanVCIAA8mhZiARnNGrIJIoVGoGB9QkCHIN3BYfNJTLQ8uNJkxpjg5sDNjA8SBpIRsrC5qxtpI9mgWXpKCA4DBYNRiBB6AgeABmRCigCMbA4IEwODw+GocAENHojGYPDYOyoUAgaAA1iLUHKuHgsBBiAzoAABGEAD1EVCq5B4JGIyjgiHGF2UBvcSqUowtVoCtoATPgAAzRgC0AWo+AALMHLdaoPh+NziK9lNwedQw8onTy+TABUK0CKQJKAKwAdgAnIhw7G603EI3tawgA) shows that when passing data with a key of `tag` to a Component, mithril "skips" the `attrs` and assigns the data instead to `children`. See the flems console.

## Expected Behavior
I'd expect to be able to pass data with any (valid) keys to a Component

## Possible Solution
* Document other "reserved words" (aside from `key`)
* Something to do with [hyperscriptVnode.js:L39](https://github.com/MithrilJS/mithril.js/blob/next/render/hyperscriptVnode.js#L39)

## Steps to Reproduce
Very simple. See flems.io link above

## Context
A "tag" is a thing in my project. I had to "rename" it.

## Your Environment
Not relevant

**Comment by isiahmeadows** [comment]
Really, that's the only other "reserved word" aside from `key` and lifecycle attributes. It's worth documenting in that it's how we tell vnodes apart from attributes, but there's not really anything else to document as "reserved".

Definitely accepting PRs to document this somewhere in the hyperscript docs somewhere (where it's given the magic behavior).

**Comment by nickolasgregory** [comment]
Closing this as it may be covered by the docs revamp #1687 etc...   
or alternatively #2414

**Comment by isiahmeadows** [comment]
Reopening as it's not covered by any existing bug I'm aware of. It's related to #2478, but only related.

**Comment by PierBover** [comment]
Not sure if related to this, but when passing a `tag` attribute the `vnode.attrs` comes up empty too.

Are the reserved words documented anywhere?

**Comment by pygy** [comment]
This was actually documented implicitly from the beginning, since it is stated that the presence of a `"tag"` key on a JS object is what Mithril uses to duck-type Vnodes. So, `m("div")` returns `{tag: "div", ...}`.

Since `m()` is variadic, and `attrs` are optional, when Mithril encounters (`m("div", x)`, if `x` has a `"tag"` key, it is considered as a child Vnode of the `div`, and the `attrs` for the div are `undefined` (likewise if it was a component). If it doesn't have a `tag`, `x` is passed as attributes/properties to the `div`.

If you want to use the word "tag" in your code, you can capitalize it as `"Tag"` or `"TAG"`, it will work fine.

The other "reserved" names on the attrs are the lifecycle methods (`oncreate`, etc...). IIRC that's all.
