### ISSUE TITLE
m.request not redrawing automatically in Chrome

### ISSUE THREAD

**Issue by sagebind** [MithrilJS/mithril.js#2426]
### Mithril Version: 1.1.6

When using `m.request` inside an `oninit` lifecycle method that returns a promise, Mithril does not redraw automatically in Chrome like it should when the request finishes and the promise resolves. It does work in Firefox and Safari.

- Chrome version: 75.0.3770.80
- Firefox version: 68.0b6
- Safari version: 12.1.1 (14607.2.6.1.1)

## Expected Behavior

- Mithril should redraw automatically when an Ajax request finishes.
- Mithril should behave consistently between Chrome and Firefox at the very least.

## Current Behavior

- The redraw callback is never called in Chrome.

## Possible Solution

I tried stepping through Mithril in the browser debugger on Chrome and Firefox to figure out what is different between the two, and in Chrome it seems like this callback is never getting invoked: https://github.com/MithrilJS/mithril.js/blob/v1.1.6/request/request.js#L20-L26. Maybe Chrome does not allow reassigning `then` on a native `Promise` object? If that is the case, maybe there's some other way of doing this, like creating a new promise and wrapping the old one.

As a workaround, I am calling `m.redraw()` manually at the end of my oninit lifecycle in my actual application (company Intranet project).

## Steps to Reproduce

Here is an example tiny app that reproduces the problem:

```html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <title>Demo</title>
    </head>
    <body>
        <script src="https://unpkg.com/mithril@1.1.6/mithril.js"></script>
        <script>
            class Page {
                async oninit(vnode) {
                    let response = await m.request("https://reqres.in/api/users/2");
                    this.user = response.data;
                }

                view(vnode) {
                    return m("main", [
                        m("h1", "Demo App"),
                        this.user ? m(User, {
                            user: this.user,
                        }) : "Loading..."
                    ]);
                }
            }

            class User {
                view(vnode) {
                    return [
                        m("p", `Name: ${vnode.attrs.user.first_name} ${vnode.attrs.user.last_name}`),
                        m("p", `Email: ${vnode.attrs.user.email}`),
                    ];
                }
            }

            m.mount(document.body, Page);
        </script>
    </body>
</html>
```

In Firefox, this shows `Loading...` for a short time and then displays user information. On Chrome, this displays `Loading...` forever unless you call `m.redraw()` manually in the JavaScript console.

## Context

<details>
  <summary>Additional Information</summary>

## Your Environment

* Browser Name and version: Chrome 75.0.3770.80
* Operating System and version (desktop or mobile): macOS Mojave 10.14.5
* Link to your project:
</details>

**Comment by spacejack** [comment]
Hi. I assume you're using 1.1.6. You might try rc6 (`npm i mithril@2.0.0-rc.6`) to see if it solves it.

The problem is the redraw occurs after the `request` promise chain ends. You `await m.request()` so the redraw happens before this line runs: `this.user = response.data;`

One solution is to use promises:
```js
oninit ({state}) {
  m.request("https://reqres.in/api/users/2"),then(response => {
    state.user = response.data;
  }) // Redraw happens after this chain resolves.
}
```

Another is to manually redraw:
```js
async oninit(vnode) {
  let response = await m.request({
    url: "https://reqres.in/api/users/2",
    background: true
  });
  this.user = response.data;
  m.redraw();
}
```

**Comment by sagebind** [comment]
@spacejack Just tried `2.0.0-rc.6` (just replace `1.1.6` in the example app I included) and the behavior is the same.

A couple of things:

> The problem is the redraw occurs after the `request` promise chain ends.

If that is the case, then why does it work in other browsers, just not Chrome?

> One solution is to use promises:
>
> ```js
> oninit ({state}) {
>  m.request("https://reqres.in/api/users/2"),then(response => {
>     state.user = response.data;
>   }) // Redraw happens after this chain resolves.
> }
> ```

Well an async function is just syntax sugar (to some extent) for promises, no? My async function should be semantically equivalent to something like this:

```js
oninit(vnode) {
    return m.request("https://reqres.in/api/users/2").then(response => {
        this.user = response.data;
    });
}
```

`await` adds to the promise chain in the same way that calling `then` does. [According to MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/await#Examples), `await` will literally invoke `then` with a native callback as an argument.

**Comment by spacejack** [comment]
Sorry, I ran into a similar problem a while ago and maybe my assessment of it was wrong. I don't understand why it works in other browsers either.

What if you try
```js
async oninit(vnode) {
  this.user = (await m.request("https://reqres.in/api/users/2")).data;
}
```

**Comment by sagebind** [comment]
Nope, that behaves the same way. Still works in Firefox, still doesn't work in Chrome.

**Comment by spacejack** [comment]
[Here is a flems repro](https://flems.io/#0=N4IgZglgNgpgziAXAbVAOwIYFsZJAOgAsAXLKEAGhAGMB7NYmBvEAXwvW10QICsEqdBk2J5qUDHDgACAAoYA5jGnAAOmmnTJATzTVp9CGgjEAFAEoV6zZtjFpAJ3gAHenGUBeLQHcMJ6Vj4TgCOAK7wZqogJMTOcIgA9AkARhhCEHGhgXRYCRjOEAkA-MTazjAeOBjEALQYaAAmNZBQsA5R5gDc1jbEhBBw+KHuDtJeTnCuaO7dGtKsPUkGxsb2psBwxNUwrJZqc0uagSHhm6ZRMXGJKWmGmdm0ufmFJWUVVbX1TS1tHfh9TFME1CUHsHgAfFYDgkbJpNtshiMxo54CDiIsYZpdhj5uoegA3CAwbwWKGwpzEUIODRYc4gLB+NBRCjSZA9WG0i4ARmZ0iiABEYFhaNIAILOZwdCjs3r9QbDGCjIoBUwAVRGLP2sNhCociGkfQGiMV0rmsN20n1UQAMrQMA0jAp8M6ojKALpdHoLNDe9TiSQydWKsk2QnE9bVYgOOAWrXazQUqk0umSyjSADkQb1GekAGotMQo-KRuYZd7fWhAsLQgxTA1aNQsiJ8MlaA1tCz5EpPWhKCB3LBqMQIG48FyAAyIcdsDggTA4PD4ahSPtCRjMHhsN1UKBGADWCBQnAXPCwJkIDmgAAEAEz4cf3moOaj4ABsfap5B4l3iSRrzj3J0cgSM8+kvKBb3vR9nzfEDz3A-AzzQfB+D7UpyjwOBqEvZxRFYN1WCAA) of your example with Mithril 2.0-rc6.

**Comment by osban** [comment]
You'd expect the code to work like [this](https://flems.io/#0=N4IgZglgNgpgziAXAbVAOwIYFsZJAOgAsAXLKEAGhAGMB7NYmBvEAXwvW10QICsEqdBk2J4hcYgAIMkgLySACgCdaWCHBj4l8WlABuMABQBKfMUJNDJuQD5JAB0MBybQBMlGAO5PjxgDpoAeJSjBJy0nAAnmjUktaydsABkg6GAIz+aCleGBBSGMmpAMyZrAEBocQmlCAasNTEEPQIPADsiAAMbBwgmDh4+NRwAjT0jMw8bAC6VFAQaADWLai9XHhq5krQNQCuSuQ8JMT2cIgA9Gc7aPYLAOaDqmcbhFtQAAJp+J8AbE95L9B8PwasRIvZuLVqFt7KJWFNWEA), but yeah, in Chrome it doesn't.
Another workaround could be to just use another `then`, like [this](https://flems.io/#0=N4IgZglgNgpgziAXAbVAOwIYFsZJAOgAsAXLKEAGhAGMB7NYmBvEAXwvW10QICsEqdBk2J5qUDHDgACAAoYA5jGnAAOmmmbpkgJ5pq0+hDQRiACgBuaWgBMYAShXqtL7QHcMp6VnwAnGACOAK7w5qogJMQADnCIAPRx-gH+cPjGcRhREHFBcDC+cHEATOH2zq6a+MSETGYpUfR50gC8AHzS1RCpufkt0vWNMPg2GMQYZRparOrlmhYQMG6W1naOapMV-sRBvhpYZuFYnmjhFNLIsxVa++GEAIyn0uEAIjBYtNIAglFRpRSXVw6hC6+B6vmkAH5vGYAKp5XxndaAwFgxBAkFg-4bZGsRxo8IAGVoGBsxgU+Ap4QBWgAuvYANyXaZoZnqcSSGRw3pIrTzRbLWwOJzYlxbHYaC4iq43EC-SjSAAGADkuGiACTAKyC-CjYgFUHw-CQArEAD6mBwrGkGq1dh1xD13UNEjgZotMFYCvsWOR1wOsseCoAokdoOrNSshrr9WD8G9PFBPd7qZoaYzsczWWgfO8ggwzDZaNQgjgGPgAEa2HRneRKBnqSggPKwajECCNPBFABsiAADGwOCB3Xh8NQpI2hIxmDw2DSqFBjABrBAoTg4PBYUyEXzQAACRXwvcPAFpfNR8F3GztyDxIjF4jk0FFF+S6Fg4pvqjuoPvDyezxeH5bt++Cbmg+D8I2xA6FE3BNtQO5RKIrA0qwQA).

**Comment by isiahmeadows** [comment]
First, [I'm seeing the same issue on v1.x with Chrome](https://flems.io/#0=N4IgZglgNgpgziAXAbVAOwIYFsZJAOgAsAXLKEAGhAGMB7NYmBvAHgBMIA3APgGEBXAE6CmxRAAIWcAA4Y04iGwC8AHRDEAntJhruAAwxwNaanoD0BgO4YIxPSzMy53Bxx4q0LAEb9ixegrKaobG1LoASvzylraE4gZGJuZWNnYOPn703B7evv7yiqrqhEwRUeIxxHF6AAqCtFgQcDD40vX+mtr4VUz2Zhn52Z5ugUUY0tK6rlzclCDNsNTEEPQIiCAAzIgATAAMIAC+FOjYuOv4AFYIVHQMoniwxOJtMJweYFFLKwVotgAU-GaABUSmgAJTiYAecQKMDiP4vTjiJQo8SAmAgpgQkTEIRoaHPERIpRo4Gggm3OBPTowZGkjHk+Qw8QAfnEalq9UazVa7VoNO6oL0agJMIkHJCSQsGGstmFIAJ0j+egAVGqFL8ngASYA0g7iNUqvRgglsWjUfg4Bj4ADmMGIAFFYFbiAAhDQASTYfzUNLUYO6MAAHsRePRGAw6X6mZSnkIoHS1CRiNI4IgzP0MLcIKnLfg6FgzOMIGYWTSlDgMMQALRyNjVyBQWCCEVMx70ltMrD4LC0KLEP5mi0u232p0wF3ur0+kDjSYgMEUSGi8T0CCaiTozH4pnM1nwiFKbjibsiACO-HgA-jAZ6aD+Ijg-CgTyPy93e47dMfz+IK73SpqI+tBQJwMBsP6-7iAcJofmK4iStQB7IseUJwcy6KCHSMqpCe+DnpeVIAoIUCwZ+zKASAwGgeBkHoUcK6cBAMCWBIfyHqhUGUUxLF0eROJ4ieM5YDY+KUOIyBQTCWAzoQACMahLmoAAiE60OIACCEz+hQUkdnpMJsjJajzkuegAKrNIIEg6phBzGgZ4jiiAAAytAYBwaA2vgPmtuRAC6YIANwrgxTIwR4BweB4Q6WqIo6Os6ohTt6wSJGEC74PQ1BQBA1AANZ0uxKEav8YAYFAzSwbFI52olE7JZ6qXFKUmXZblBVFRxpUDsQgiXrB65lRVVUeHMCwwF8qx4FsckAGyHMcICYDgeD5nA1w0OG9zrAMATAOIHAyFAGAaBIXhQOa+VBdB40wIsyzTesuw7AArIc-lULlaD5WsqDLaceCNFUgjQAAAnJczxngyapumZhRNI+XeQWZjA4QoNQBD+Byfgc1o7EmOXJtNJ4HA1Cg9IxAfQcQA). That repro lets you compare both through a couple simple buttons.

Second, I *strongly* suspect a V8 bug here. [It repros even without the DOM](https://flems.io/#0=N4IgZglgNgpgziAXAbVAOwIYFsZJAOgAsAXLKEAGhAGMB7NYmBvAHgBMIA3APgGEBXAE6CmxRAAIWcAA4Y04iGwC8AHRDEAntJhruAAwxwNaanoD0BgO4YIxPSzMy53Bxx4q0LAEb9ixegrKaobG1LoASvzylraE4gZGJuZWNnYOPn703B7evv7yiqrqhEwRUeIxxHF6AAqCtFgQcDD40vX+mtr4VUz2Zhn53JQgzbDUxBD0CIggAEyIAGwADCAAvhTo2Lgz+ABWCFR0DKJ4R3DE4tLiSuJ1DU0tInC0UJwwABQAlB5nFz3yN2k3RKaA8HiB-2u4ne+FhGEEAHM4J9rtxxMAPOIseIzi8WlBaAj3moRNQYFwYGxxP81N95NiRMQhPJwjAwGNiPgMNJpFANO9-hRLkL4Ui6aswZhEtRxGAouNJvJGOcAILSr7ozHY3GwfAEolqagYKBQcQhEy0rVYjDWWyXK04qZ4vWE4kgJ78HBm23ES1oCWgtBykwTALK4gAFRBGox9KxOvxrsNxtNNJAdOx4kZzMuwKY7w1SjRsczmYTLoN7vgnpg1JBfszq3FktgFzaME4HmDCoCEDQtne-GaUaYKJL2IgYGh7c41yUNyHMBHaBR2cEgczM6hi+XDt+1K0tYXw-rcdLAH5xGpavVGs1Wu1aJ0Wv89GoHZmJNfzaYLDbUm+IB7k6ur6u8egAFRQQo-YXAAJMAz6rOIUEQXoGbYmwtDUDWDD4AiMDEAAorAOAMAAQhoACSbBus+tLdDAAAexC8PQjAMFC9FnpO0I7iCKLhsuXwOjAUDNNS8DEGqoQif6kpYThZGcgRxGkaIlE0W6P4MfQ1BQBA1AANZQoWaJ9gOYDGs0dKKbhKmESRMDKZptFqGmnz4HpBnGaZKJFjBA7EII-AwHSFnEO8VniWFHjDKMMA9mg0xzAA7IgsypWsGwgJgOB4Pg1BwAcNDsScMwDAEwDiBwMhQBgGgSF4BLGQA3OIqzxWJiWhsleBLBlCxrAAulQBloEZ0yoLlWx4I0VSCNAwxCOQMwkMQ0hwIgZhmFE0hGQihUNGY82EItUAAAIAIz4DdCwnbE517CVz54HA1CLdIxAjasQA). If it's not a V8 issue, then I suspect it's either a spec bug or a design limitation I can't really work around. I've filed https://bugs.chromium.org/p/v8/issues/detail?id=9349 to track this.

**Comment by spacejack** [comment]
@isiahmeadows was wondering, with redraws being async (by way of RAF) does `m.request` still need to use its 'finalizer'?

This would break cases where you're relying on it to defer the redraw until another long-running (i.e., longer than RAF) promise is appended to the chain (and you might need to use `background: true` if you're chaining several requests.) But it might work for the common cases like this one.

**Comment by isiahmeadows** [comment]
@spacejack Yes. The event loop in modern browsers obviously can't run animation callbacks while draining the microtask queue, because those are always drained at highest priority as a single step, and as per spec they aren't handled as a normal "task queue" like the task queues for requests and timers are. However, you *could* schedule a `new Promise((resolve) => setTimeout(resolve, 0))`, and that *could* result in an animation frame in the middle, if you call that more than once. It's pretty well-known the minimum delay is 4ms (well, only with a nesting depth of at least 5), but it only takes 4-5 of those to hit a 16ms animation frame, and the Promise polyfill in practice could easily hit not only the nesting depth requirement of 5, but also the remaining 4-5 delays required to hit that nesting depth, because, like most other userland Promises/A+ implementations targeting browsers, it specifically uses `setTimeout(callback, 0)` to defer and it doesn't try to batch tasks and emulate its own microtask queue. (Bluebird is a rare exception here, and most Node implementations use `process.nextTick` to correctly schedule microtasks.)

Here's the relevant parts of the spec:

- Event loop processing model: https://html.spec.whatwg.org/multipage/webappapis.html#event-loop-processing-model
- Timer initialization steps: https://html.spec.whatwg.org/multipage/timers-and-user-prompts.html#timer-initialisation-steps

**Comment by isiahmeadows** [comment]
Figured it out: V8 is actually doing the right thing here, but nobody else is and so that's why this shows up in Chrome, but not Firefox or Safari: https://github.com/tc39/ecma262/issues/1577. It's *exceedingly* subtle, but it comes down to this:

- The `.then` method on the object is only called [when wrapping promises](http://tc39.es/ecma262/#sec-promise-resolve-functions), no earlier and no later.
- [If `p.constructor === Promise`, the object is *not* supposed to be wrapped](http://tc39.es/ecma262/#sec-promise-resolve), but instead returned directly. (This gives rise to a [genuine spec bug](https://github.com/tc39/ecma262/issues/1578), but is otherwise unrelated to this issue.)

Gotta love spec bugs and implementation divergence. 🙂

The proper workaround is two-part and *very* subtle:

1. Add `function PromiseProxy(executor) { return new Promise(executor) }; PromiseProxy.prototype = Promise.prototype; PromiseProxy.__proto__ = Promise` [here](https://github.com/MithrilJS/mithril.js/blob/next/request/request.js#L9) to reduce runtime impact. The first is to work with async functions as explained above. The rest is to make the wrapper as transparent as possible, in case the global `Promise` Mithril sees relies on `this.constructor.foo` or `p instanceof this.constructor` for some reason.
1. Before [this line](https://github.com/MithrilJS/mithril.js/blob/next/request/request.js#L36), add the line `promise.constructor = PromiseProxy`.

**Comment by spacejack** [comment]
Nice work @isiahmeadows.

**Comment by sagebind** [comment]
Good investigation! The solution is way above my head, but still interesting to read.

**Comment by isiahmeadows** [comment]
@sagebind If you'd like to know a bit more about the background leading up to my fix, I wrote [this Twitter thread](https://twitter.com/isiahmeadows1/status/1138055097865461762) on it, targeting a less technical audience that includes non-programmers.
