### ISSUE TITLE
m.route.Link reloads whole page without preventDefault

### ISSUE THREAD

**Issue by gdandersson** [MithrilJS/mithril.js#2474]
Having m.route.prefix = '' seems to reload the whole page when rendering links via m(m.route.Link, {href: "/url"})

Or, when the links are clicked.

If I add onclick: function (e) { e.preventDefault() } everything seems to work as intended (for a SPA). It redraws, not reloads.

**Mithril version:**
2.0.0-rc.8

**Browser and OS:**
Chrome 75 on OS X

## Expected Behavior
Redraw, not reload

## Current Behavior
Reload

**Comment by isiahmeadows** [comment]
Could you put together a [Flems](https://flems.io/mithril@2.0.0-rc.8)? Also, does this reproduce in v1?

Do note that `e.preventDefault()` now also aborts the route change in `m.route.Link` `onclick` handlers, so that's why you're seeing a redraw. (If a route change *still* occurs, that's a bug.)

**Comment by gdandersson** [comment]
https://flems.io/#0=N4IgZglgNgpgziAXAbVAOwIYFsZJAOgAsAXLKEAGhAGMB7NYmBvEAXwvW10QICsEqdBk2J4AYgCd6xAA4YA5jAAEAXiXAAOmiVKAbhBgB3RErABXNNWIR6ACgCU6rRuIuJMYmYnastrPikzRnwAGQg0AGsKdUJ3MBMNEAB6RjhXNmjEgHFaJWJc1PT7LR1WLTK0LQAVeGJVJ209A2NTCysbNAcGlzcPLx8-ANogmFDwqJi4hOTE9iVEqtywKQY5RUTixoqK5zR-QOCZOIgAD3qAcnOtfeHGWwATWmozHAZ8ACNae4BPTJnKBo6HSJJKJEySaRrGAUEpAkGFMFKGppcqbSggOAwWDtegIHgARgAHIgAAwZTg4PD4ahwAQ0aQiFisAC6VCg4zxqBAmEpPCwEGIsWgAAEAEz4EkSgC0Emo+EJ6K85B4JFkcEQSSSFhkEXk1NoWCS-MFEhF4slJJlcsJRoFQqg+H5aHw-HRxG+Mm4GOoppkohZrCAA

Have not tested on v2, just followed the instructions on Installation and installed the latest version.

But.. e.preventDefault() in onclick does change the route, at least URL-wise and display/render-wise.

**Comment by isiahmeadows** [comment]
@gdandersson Your flems doesn't include an `e.preventDefault()` call. [I fixed it to one that does](https://flems.io/#0=N4IgZglgNgpgziAXAbVAOwIYFsZJAOgAsAXLKEAGhAGMB7NYmBvEAXwvW10QICsEqdBk2J4AYgCd6xAA4YA5jAAEAXiXAAOmiVKAbhBgB3RErABXNNWIR6ACgCU6rRuIuJMYmYnastrPikzRnwAGQg0AGsKdUJ3MBMNEAB6RjhXNmjEgHFaJWJc1PT7LR1WLTK0LQAVeGJVJ209A2NTCysbNAcGlzcPLx8-ANogmFDwqIadKaVYmHilRKTEihLppXpqKAhqCJNzS2t6JVsYXUdNRrWlU-wZd10RABE5jDMoYgdVq4ATGAAjMzyRQSL5TCrTdgLEBVXJgKQMOSKRLFRoVCrOND+QLBO5zCAAD3qAHIiVoscNGLZvrRqGYcAx8H9aN8AJ6ZZLLSZTRaJEySaSImArS5QlK1XlKGppcooyggOAwWDtegIHgARgATIg1QA2DKcHB4fDUOACGjSEQsVgAXSoW0iqtQIEwhp4WAgxFi0Hw-DlXnIPBIsjgiCSSQsMgi8mNtCwSXdnok0AAAhr8AAGDMAWgk1HwAA54x6vVAfWbiCyZNx5dQkzJRDbWEA), and I see the issue there: my `!e.defaultPrevented` condition needs inverted. Fix incoming.

Still would like to see a snippet showing it reloading the whole page instead of just one part, though. Do note that you'll need to use a route resolver `render` method to do it.

**Comment by gdandersson** [comment]
No, my flem is based on examples from the documentation where it says "Using m.route.Link causes the link to behave as a router link - clicking it navigates to the route specified in href, instead of navigating away from the current page to the URL specified in href."

I assumed that was the same thing as <Link> in React, where only part of the page is redrawn instead of a reload.

Hm, not sure what you would like to see. In the flem you pasted, if you click "To frontpage", the page isn't reloaded but redrawn/rerouted. Compared to "Go to test" which reloads the page.

**Comment by thequailman** [comment]
I am seeing this behavior as well, looking forward to the fix!  I really like the new syntax.

**Comment by isiahmeadows** [comment]
Not quite. I've got a series of fixes coming for the rest, too.
