### ISSUE TITLE
Is there a standalone library for `vnode` creation?

### ISSUE THREAD

**Issue by ghost** [MithrilJS/mithril.js#2500]
Hey!

Render function can be used as a standalone library `var render = require("mithril/render")`
Since it requires a `vnode` as the second argument, my question is how to create a `vnode`? Is there a standalone tool than can be imported from `mithril`?

I tried feeding `hyperscript` vnode to render function, but it didn't work.

```
var h = require('hyperscript')
m.render(body.document, h('p')) // error ... can not get view of undefined or something like that
```

**Comment by isiahmeadows** [comment]
It's not (yet) documented, but try `require("mithril/hyperscript")`. That should do precisely what you're asking for. It's still part of Mithril, but doesn't require the DOM and it's completely standalone. In fact, Mithril's renderer depends on some of *that* module's internals.

**Comment by isiahmeadows** [comment]
Marked as a docs bug because it should've been documented a long time ago.

**Comment by hqproto** [comment]
```
import m from 'mithril/hyperscript';
// const m = require('mithril/hyperscript');
import render from 'mithril/render';
// const render = require('mithril/render');

render(document.body, m('p', 'hello world'));
```

*chef's kiss*

**Comment by barneycarroll** [comment]
I disagree that we should document granular Mithril module imports without a compelling author story and a holistic proposal for what that documentation ought to be - a couple of lines showing the lines of code necessary to require the internal modules isn't good enough IMO. We're already under strain maintaining documentation that is often less clear than we'd like, and partially documented features raise more questions than they answer; in the absence of a strong example this would add to the problem. 

We shouldn't be encouraging people to use features without also being able to provide guidance. OP was curious enough to investigate the source - which is the de facto documentation for internal module usage - and only slipped up because of a typo, which @isiahmeadows was able to advise on promptly. This is a good end result!

We can reference this issue for posterity but in light of the huge backlog of issues and the lack of clear direction I'm closing this. Documentation pull requests will be considered on their own merits.
