### ISSUE TITLE
One variable is write/read from two components. 

### ISSUE THREAD

**Issue by 14e28f87** [MithrilJS/mithril.js#2509]
Hi,

I created a sample application code.
[https://codepen.io/14e28f87/pen/PMaBPJ](https://codepen.io/14e28f87/pen/PMaBPJ)

One variable is write/read from two components. 

Immediately after initialization, there seems to be one variable.
However, if you write from two components, it will behave strangely.

why?

(Is it a bug or a specification?)

- mithril: 2.0.3
- firetox 68.0.1 , chrome 76.0.3809.100

**Comment by isiahmeadows** [comment]
[Tip: define components statically, call them dynamically. Don't create them in userland, but instead let Mithril itself create them.](https://mithril.js.org/components.html#avoid-creating-component-definitions-inside-views) The docs example uses factories, but the same thing applies to classes.

Here's one way your code could be improved, using a shared state object:

```js
class CounterComponent {    
    view({attrs: {counter}}) {
        return m("div.border.m-5.p-2", [
            m("h1", "CounterComponent"),
            m("div", "counter.count : ", counter.count),
            m("button", {onclick() { counter.count++ }}, [
                "count up (CounterComponent counter.count++)"
            ])
        ])
    }
}

class MainComponent {    
    constructor() {
        this.counter = {count: 0}
    }
    
    view() {
        return m("div.border.m-5.p-2", [
            m("h1", "MainComponent"),
            m("div", "this.counter.count : ", this.counter.count),
            m("button", {
                onclick() { this.counter.count++ }
            }, "count up (this.counter.count++)"),
            
            m(CounterComponent, {counter: this.counter})
        ])
    }
}

m.mount(document.body, MainComponent)
```

**Comment by osban** [comment]
@14e28f87 @isiahmeadows the suggested code doesn't seem to work as intended...I think it's because `this` in `onclick() { this.counter.count++ }` is not the instance (because of it being in an event...learned this yesterday from @barneycarroll). One way to solve this would be to call `counter.count` directly with an arrow function: `onclick: () => this.counter.count++`. [Flems](https://flems.io/#0=N4IgZglgNgpgziAXAbVAOwIYFsZJAOgAsAXLKEAGhAGMB7NYmBvEAXwvW10QICsEqdBk2J5qUDHDgACAMK0ArsIBO8rAAd6I6cGl7pAHTT7pANwgwA7gApgGYsWVxEOuksbLWrAJQ6jJk2UYYgVlYyxrAxAAEwhTfAAjWmVomGV8LABaAFZ8dUyAJiiKaWR-AIqIqMIARmLDEHl3NLVNNBEo7wpyipMqmLj6qLcVfBHiaRd68bSxxQYunt69foSFB3p64HpxCGoAa2tfXRn08YBqc+kvErLjZd7h+YmFdWlrJpVWrQZpU7n3JdvFElssALrA+4VCFLVhGOFoIziSQyACyGAgaG+7V+un0SyEcEcCmoxGSRz8UICxEIEDgAJU0gAvK5ni4AAwIkxcpbmKwU4Cg-RBEJhaT9WLxJIpWZZXL5IqUUpCyqREC1IYgdGY7EdECLKnLCWDJVRGl0hkeS2TBolc30-7jA0PfSrdZkxFKwWGl3SHZQPb7FwUpkAPmk9stswu5xVAXYDXG0le70jjueQM63R9FTjfQ+zxatA0P2IJWApxcacLnkh4Lr+gRCKMWAyz2s0Vo1AUOAYiVo0QAniVtVji20RN5KCA4DBYKSIPQEDwCgBORDstgcECYHB4MZSadCRjMHhsMFUANofbL1A7rh4LAQGnKaDT0LkHgkYjqZwAej-JR1H2ABzOYsD-J8X2gAABAp8HZfAAGZIOfQhXygDJMXwfhp2IQd1G4GdqFfdRRFYMFWCAA).

**Comment by 14e28f87** [comment]
> define components statically, call them dynamically. Don't create them in userland, but instead let Mithril itself create them. 

I understand this. 

However, I don't think that a good design of OOP is that components can only be used statically.

In render/render.js  Line 142,
I think that it can support both static and dynamic when using components by changing as follows.

* Object.create () is not used. This is because variables are passed by value.

```
*** /home/sample214/node_modules/mithril/render/render.js	Thu Aug 15 04:07:28 2019
--- /home/sample214/node_modules/mithril/render/render.js.orig	Thu Aug 15 04:37:46 2019
***************
*** 139,146 ****
  	function initComponent(vnode, hooks) {
  		var sentinel
  		if (typeof vnode.tag.view === "function") {
! 			//vnode.state = Object.create(vnode.tag)   // 
! 			vnode.state = vnode.tag     // 
  			sentinel = vnode.state.view
  			if (sentinel.$$reentrantLock$$ != null) return
  			sentinel.$$reentrantLock$$ = true
--- 139,145 ----
  	function initComponent(vnode, hooks) {
  		var sentinel
  		if (typeof vnode.tag.view === "function") {
! 			vnode.state = Object.create(vnode.tag)
  			sentinel = vnode.state.view
  			if (sentinel.$$reentrantLock$$ != null) return
  			sentinel.$$reentrantLock$$ = true
```

**Comment by isiahmeadows** [comment]
@osban @14e28f87 Fixed my suggested workaround - forgot to use an arrow function. (My bad.)

> I understand this.
> 
> However, I don't think that a good design of OOP is that components can only be used statically.

Mithril is more impure functional at its heart than it is object-oriented. Components are types, where their instances provide the underlying vnode and related hooks. They're very much just a giant function of `(attrs) => view` with associated state.
