### ISSUE TITLE
'Link' of undefined (m.route.Link)

### ISSUE THREAD

**Issue by souricevincent** [MithrilJS/mithril.js#2546]
**Mithril version: 2.0.4**

**Browser and OS: Chome Version 78.0.3904.70 and Mac mojave**

**Project: https://github.com/souricevincent/mithril-ssr-boilerplate/blob/master/app/common/m.js**

## Code

```javascript
if (process.browser) {
    module.exports = require('mithril');
} else {
    module.exports = require('mithril/hyperscript');
    module.exports.route = {
        Link: "a" // Fix 'Link' of undefined
    };
    module.exports.request = require('mithril/request/request')(window, require("mithril/promise/promise"), null).request;
}
```

## Expected Behavior

I would like `hyperscript` turn `m.route.Link` into `a`

## Current Behavior

If i charge just `hyperscript` i have `Link` is undefined on the `m(m.route.Link, {disabled: disabled, href: "/test"}, "test")`

## Context

For the SSR

**Comment by isiahmeadows** [comment]
Not a bug - I've adjusted labels accordingly. (You can select "Enhancement" for these kinds of suggestions.)

You can `require("mithril/route")` server-side as long as you set the globals it requires to *something*, even if it's just `global.window = undefined` (IIRC). Also, the hyperscript API by design can't tell `mithril/render` apart from `mithril-node-render`, and I have no plans to change this. So this is very unlikely, just as a heads up.

**Comment by souricevincent** [comment]
thank you : 
```
if (process.browser) {
    module.exports = require('mithril');
} else {
    module.exports = require('mithril/hyperscript');
    module.exports.route = require('mithril/api/router')(window, null);
    module.exports.request = require('mithril/request/request')(window, require("mithril/promise/promise"), null).request;
}
```
