### ISSUE TITLE
[Discussion] Mithril for Rust GUI

### ISSUE THREAD

**Issue by DaniellMesquita** [MithrilJS/mithril.js#2564]
Mithril is doing amazing in JS.
But how Mithril would work as a library for graphical Rust apps?

**Comment by isiahmeadows** [comment]
I would recommend starting out with writing some Rust bindings for Mithril using Emscripten, if you plan to use it in the browser via WebAssembly. You may also wish to consider exposing `vnode.dom`/`vnode.domSize` via [wasm-bindgen](https://github.com/rustwasm/wasm-bindgen).

I do want to throw a couple Rust-specific notes if you choose to do this:

1. Make sure to enforce that the vnode view's type is something along the lines of `Fn(&Vnode<Attrs>) -> Vnode<_>` (the result returned by value so the callee gains ownership) and not `Fn(&Vnode<Attrs>) -> &Vnode<_>`. This is an API invariant enforced by convention for JS, but Rust can enforce it at the type level.

2. You may wish to consider using closure components with some macro magic for modeling Mithril components - it's way easier to use. Something to similar to this:

	```rs
	static Foo = component<Attrs, Children>(move |initialVnode| {
		let mut state = "foo";
		instance! {
			view: |vnode| m!("sel", {/* attributes, lifecycles, keys, etc. */}, /* children */),
			oncreate: |vnode| { /* ... */ },
			// Other hooks as applicable
		};
	});
	```

3. Instead of exposing `vnode.dom` + `vnode.domSize`, expose a `fn dom(&self) -> Iterator<Node>` iterator that returns the first `vnode.domSize` entries starting at `vnode.dom` (and for empty fragments, don't return any element).

**Comment by DaniellMesquita** [comment]
Quote from https://aeplay.org/citybound

> RUST-WASM-JS BRIDGE
> Compiling Kay to WebAssembly allows running a fully fledged actor system node in the browser, which can communicate with the simulation backend through type-safe high-performance messages and do computation-intensive preparation work for rendering, before efficiently serialising and passing rendering-relevant information as JavaScript objects to a React app that implements the rest of the UI. The React app can call Rust hooks that were exported to JavaScript, to send Kay messages back to the simulation backend for influencing the game world based on player input.

In this case, could Mithril be used instead ReactJS?

**Comment by isiahmeadows** [comment]
In theory, yes.

**Comment by DaniellMesquita** [comment]
@isiahmeadows, this issue is related to: https://github.com/MithrilJS/mithril.js/issues/969. Also, many thanks for your open mind on discussing on my issue.

Mithril with WebAssembly > Rust is the true "Mithril Native" ppl are looking for.

**Comment by isiahmeadows** [comment]
@DaniellMesquita I wouldn't consider WebAssembly "native" on most platforms. Also, to run Mithril directly on WebAssembly, you'll need to literally reimplement the framework unless you're willing to bear the immense performance cost of frequent data marshalling.
