### ISSUE TITLE
Stale Select value in Firefox

### ISSUE THREAD

**Issue by LeXofLeviafan** [MithrilJS/mithril.js#2572]
In some cases, `<select>` element rendered by Mithril doesn't display the option provided in `value` attribute when operating a dynamic list (see Context section for details). This happens specifically in Firefox, while Chrome doesn't have such an issue.

**Mithril version:** 2.0.4

**Browser and OS:** Firefox 72.0.1, 64-bit Linux (also tried on 69 LTS with the same result).

## Code
The code I tried originally looked essentially like this:
```javascript
let Panel = {
  view: () => m('.panel',
    /* controls here */
    m('.row',
      m('button', {onclick: () => addItem(items.indexOf( selectedItem() ))}, "+"),
      m('select', {value: state.selected, onchange () {state.selected = this.value}},
        items.map(it => m('option', {key: it.id, value: it.id}, it.title))),
      m('button', {onclick: () => removeItem( selectedItem() )}, "-")),
    /* item details here (overview if nothing selected) */),
};
let addItem = idx => {
  let item = Object.assign({}, items[idx], {title: "?", id: newId()});
  items.splice(idx+1, 0, item);
  state.selected = item.id;
};
let removeItem = item => {
  if (confirm(`Remove item "${item.title}"?`)) {
    items.splice(items.indexOf(item), 1);
    state.selected = null;
  }
};
```

## Steps to Reproduce
1. Select an item, click `+`
2. Click `-`, then "Ok"

## Expected Behavior
- After step 1, the newly selected item should be selected in dropdown (selected title will be `?`)
- After step 2, the dropdown box should be empty as nothing is selected

Both of these happen in Chrome.

## Current Behavior
- After step 1, the title of the first item is displayed
- After step 2, the title of the next item after the removed one is displayed

Both of these happen in Firefox.

## Context
When the Select element is used to navigate a dynamic list, it's a common practice to automatically have the newly added option selected; and after the currently selected option is removed, one possible action is to unset the selection altogether (depending on UX logic). After I tried to do this, I encountered an issue in Firefox (which doesn't happen in Chrome): when switching to the newly added option value, the one actually displayed was the first in options list; and when unsetting the value after removing the selected one, it instead displayed the option which had followed the one I removed. Calling `m.redraw()` immediately afterwards from REPL (or triggering a redraw in-app) caused the element to re-render correctly.

After some fiddling, I managed to figure out that Firefox applies special logic to cases when the dropdown options list doesn't have the provided value at the time of setting (and likely similar shenanigans for cases when the selected option is removed that ignore unsetting the value). This led me to producing a functioning workaround:
```javascript
let Dropdown = {
  options: [],
  onupdate ({attrs: {options, value}}) {
    if (!this.options.some(it => it.id === value) || !options.some(it => it.id === this.value))
      m.redraw();
    Object.assign(this, {options, value});
  },
  view: ({attrs: {options, value, onchange}}) =>
    m('select', {value, onchange},
      options.map(it => m('option', {key: it.id, value: it.id}, it.title)),
};
/* then using new component in place of original 'select' */
```

**Comment by osban** [comment]
@LeXofLeviafan Would [this](https://flems.io/#0=N4IgZglgNgpgziAXAbVAOwIYFsZJAOgAsAXLKEAGhAGMB7NYmBvEAXwvW10QICsEqdBk2J4hcYgAIMABxmSAvJIAUASkUA+ScAA6aSZNhTqhWhGoxF2iABNEkgIwBWABwBmAAxOAnADZvfg5uFJLEEMSw9gDkAJKMWABMUax6BuJStDJh9HBWyKkG1naOrp4+-oEJIWERMNFxMFgOyRQFBsC29s7uXn4BvkHV4ZGSsfFJ7G1FXaW9FQMALEO19fFuyQUAugUF6dI2NlZqmtpTe2gwAO6ZUkodxQAiGIz4aLSXassjUQD8G-qFG4QHL4GQAVzghGUF2uWVUZ1M5ksShhNwKKQBewATo0juoFFpdACDECQXAZFAkcowLRaPg4DBYNRGDYYmgbDAAB4hBzw4mSExmCxWe7RKJfOqjf4GDEGAo44hgrH6ImFSQANwgV3sxwJkny-IMWGUUUIzRCUQAyoyYMyoqpWobJMaogAjMHEYj0cXaejUSnUADW9gwB3YowA1PbHWqjSaGUziABiGm0H2q2Nqv2EDBoADmkuRWkFSKspLQcGQMHwxAwWILxHpNuZMFZ7K5mxjmcK6owUDBkpLFhrwxgUzVkydJKywIr+CwsmUnM049jLvL6dXmYTtpZ9k5+FsigUSiH1dsW8K4YPNVgfO7knvsYdq5d7s93pCwD9AeDkhxWDhlEAC00aviaMg4j6ABSloAPIAHL0sQWIQPmEBgAAnsoZ4hGgYJQFAIQJKoT4GNsAIYhiehYPOtBggwyg2LQ1BgjgDD4K6tA2JhISyDIqiUDQtBYDI0AwFieCuhgrqMkJO7MrOCA8G4ADsiAeGwHAgJgOB4Pg1BwAIwnCMwPBQDJjLaJINgQOSFmYfYrpQCxgaSKwbCdiAlJoIGymoDpXB4Fg4SEKh5BUEq5A8CQxAyHAiAAPSJQxMiBnmBkiYlIXEGF0BCcQmEyNwIBwNQqFZJ5rBAA) work for you? I don't think this is a Mithril issue, but that the `selected` attribute of the correct option needs to be set manually.

**Comment by LeXofLeviafan** [comment]
@osban …I have no clue how the hell it happened, but the `selected` thing (which was the first thing I tried when I encountered this issue) now works completely different from how it did a couple days ago in the very same browsers (I've spent several hours trying to make it work back then) 0_o

Now the new-id thing works just fine, both in your example and my code (with `selected` hack, that is). The unset-id thing, however, doesn't (and now it doesn't work in Chrome as well…). [Here](https://flems.io/#0=N4IgZglgNgpgziAXAbVAOwIYFsZJAOgAsAXLKEAGhAGMB7NYmBvEAXwvW10QICsEqdBk2J4hcYgAIMABxmSAvJIAUASkUA+ScAA6aSZNhTqhWhGoxFkgOTWA3HoPiptGcQj04V5I4PaIACaINgCMAKwAHADMAAxhAJwAbPFJIQBM1hSS7sSwwdYAkoxYIdbsvgbAgfnh0XFJKYkhUZnZELkw+UUwWBnl+n5VQaGRsQnJqQAsrTl5Nt1YLay+ALoOA0aScDCw1IwBBWgBMAAeVmqakq7unviQR4fHJ8pnClon+IGKCkomZhaqdYGXzOaQBALndRvbQVSSgtAwADu1ysQ2CAAMACTAAAiGEY+DQtERalY6Kys06NgA-GUgX5rh40HB8HAZFBzDBlNtdvtHqc1ABqEJZGJZBHItyA2F-TlWCXXT4BemsemggBOPUhl10AwMjNubI5Fm5OxgexgByOAtUWRC0r1cNMcqUtjsfgA9B7JGgAK5QKCSAK0eBoaxSZHqgDWcNo6s1eygAE9fKrfL5NcRfer9Lq-Fc-TIAvjLBc8-nsoQICzZRZJAAyeuSACEtcsjckWHwmoC6owJIdFcr1fwbasbfpBn6+YAbhAkcELtCfI6DFhlNZCKUssB6NRjVHguJaLB8FBaABzdg2ADKZr21ltsLXG4ARr7iMR6K1d2h9+ZDzBAJr2sQVHwoZ9Ow3HlzWIH9IPzPdCAwNAL1LdRgDHJRiCrFkZwwKBfRgachz8fDCKpNsINXPwSKHA1mXwLBZBeTQEL8ddrAY+CaKHciiOCD5Amo0iKxgi1hiEiEfl+Z0LBE0TJGvD5KSfXjJDUodNIrTj30-b8dz3A9gk1LAQIAWnAyDlDHakoOsGRNVaAApG8AHkADlWWIdUIFQiAwCTGy5JgcV-SgLI0lUVR2KHYJOP9VoGJZZiZFY6FOI5VoVPaWBouihSDBWBS0zQUq9C7LBaF9BhlGDahfRwBh8FfWgAiTLJZBkB1KBoWgsBkaAYHVPBXwwV8dl68SbmZPA0iiRBEnMtIYkQSY2A4EBMBwPBRzgAQ+uEZgeCgcadm0INq3ZDAk2CV9z2oGNWDYYqQA5NAowQFBOB2ngsHaQhfPIKhs3IHgSGIGQ4EQL0apkKML1HfqPX+nCgd64gkxkbgQDgahfLcF7WCAA), I've changed up a few things (bringing it closer to my usecase and fixing stuff like using captions as option IDs); you may notice that if you comment out the `onupdate` and remove an item, the unset won't be applied until the next redraw (which can be triggered by clicking on the header).

**Comment by osban** [comment]
@LeXofLeviafan The problem is that `selectedIndex` will be -1 when `choice === ''`, and also that after removing an item `choice` will be `''` again, so it doesn't correspond with the first item. So you'll need to do something like [this](https://flems.io/#0=N4IgZglgNgpgziAXAbVAOwIYFsZJAOgAsAXLKEAGhAGMB7NYmBvEAXwvW10QICsEqdBk2J4hcYgAIMABxmSAvJIAUASkUA+ScAA6aSZNhTqhWhGoxFkgOTWA3HoPiptGcQj04V5I4PaIACaINgCMAKwAHADMAAxhAJwAbPFJIQBM1hSS7sSwwdYAkoxYIdbsvgbAgfnh0XFJKYkhUZnZELkw+UUwWBnl+n5VQaGRsQnJqQAsrTl5Nt1YLay+ALoOA0aScDCw1IwBBWgBMAAeVmqakq7unviQR4fHJ8pnClon+IGKCkomZhaqdYGXzOaQBALndRvbQVSSgtAwADu1ysQ2CAAMACTAAAiGEY+DQtERalY6Kys06NgA-GUgX5rh40HB8HAZFBzDBlNtdvtHqc1ABqEJZGJZBHItyA2F-TlWCXXT4BemsemggBOPUhl10AwMEDAKh5MD2MAORwF6i0AFoQupdX4GW4mSy2RyLNydia+Rbnqosnb6Y7ZRYrIzPMgYislXY-AB6OOSNAAVygUEkAVo8DQ1ikyPVAGs4bR1Zq9lAAJ6w5YDVW+Xya4jJ9X6B1+ABuECRwQu0J8er8WGU1kIpSywHo1HdBeC4losHwUFoAHN2DYAMpevbWf2wgxD6wAI2TxGI9FaE7QU-MM7BATX1kFO4oe8kB+NewAxGBaLQL6-HUnQgMDQZdLAuYAQ0sJRiEICAWXbDAoGTGB+kddDJEQ5CqSgl8B0dNCMKuZ1biwWQXk0ADB2HcMc3HKjHSwlDgg+QI8KI9CP32FilW+X5TE5diOMkNcPkpXd8L8CSMOk9CD2PU9z3HSdp2CTUsAfa1n1fZQoMkak32HGRNVaAApdcAHkADlWWIdUIFAg0K10gSLHFVMoCyNJVFUBj0OCA9U1aWiWTImQKOhA8OVaMT2lgHyfKEgwViEus0DSvQsHwLBaGTBhlEzahkxwBh8EPWgAgrLJZBkaU0EoGhaCwGRoBgdU8EPDBDx2BquJdPBJkmRAYjYDgQEwHA8Hwag4AERrhGYHgoC6nZtAzeD2QwCtgkPJdqCLVg2BSkAOTQAsEBQThJp4LB2kIezyCoZtyB4EhiBkOBEATPKZALZdpqauNbtgh6GuICsZG4EA4Goey3CO1ggA). Does that work as intended?

**Comment by LeXofLeviafan** [comment]
@osban …
Read my comment again

**Comment by osban** [comment]
@LeXofLeviafan OK, what I misunderstood was that you actually wanted to have the selected value to be empty after a removal. That problem can be solved by manually setting the `selectedIndex` to -1.
The other issue is what I mentioned (but perhaps not explained clearly enough) about the `selectedIndex()` function returning -1 when the `select` value is empty. When the '-' button is clicked in that situation, the last entry is removed. I doubt that is what you intended, which is why I added the `if (selectedIndex() > -1) {...}` to `rem`. You can see the total code [here](https://flems.io/#0=N4IgZglgNgpgziAXAbVAOwIYFsZJAOgAsAXLKEAGhAGMB7NYmBvEAXwvW10QICsEqdBk2J4hcYgAIMABxmSAvJIAUASkUA+ScAA6aSZNhTqhWhGoxFkgOTWA3HoPiptGcQj04V5I4PaIACaINgCMAKwAHADMAAxhAJwAbPFJIQBM1hSS7sSwwdYAkoxYIdbsvgbAgfnh0XFJKYkhUZnZELkw+UUwWBnl+n5VQaGRsQnJqQAsrTl5Nt1YLay+ALoOA0aScDCw1IwBBWgBMAAeVmqakq7unviQR4fHJ8pnClon+IGKCkomZhaqdYGXzOaQBALndRvbQVSSgtAwADu1ysQ2CAAMACTAAAiGEY+DQtERalY6Kys06NgA-GUgX5rh40HB8HAZFBzDBlNtdvtHqc1ABqEJZGJZBHItyA2F-TlWCXXT4BemsemggBOPUhl10AwMEDAKh5MD2MAORwF6i0AFoQupdX4GW4mSy2RyLNydia+Rbnqosnb6Y7ZRYrLY7H4APSRyRoACuUCgkgCtHgaGsUmR6oA1nDaOrNXsoABPWHLAaq3y+TXEOPq-QOvwANwgSOCF2hPj1fiwymshFKWWA9Go7uzwXEtFg+CgtAA5uwbABlL17az+2EGXvWABGceIxHorWHaFH5nHYICi+sgvXFE3km3xrXQ4fjvocZkAXxVOUwBTWCsFCWhVIaygAIQhjA6gAayq4+k8Vi2v0jqoVcp6EBgaBzlSljQsAUFWDA+DEBg6o4cQ+BNhgUBxjAKFoc2NF0ROpicve3aOgxaGMrcWCyC8mhvj2fa8emr6cYx1G0VSHyBBxjGoc++zBHJEI-L8bEWApimSIuHyUhukkGEZaGmah257geR5DiOY7BJqgFZNY1p3g+yiEdSj59jImqtAAUkuADyAByrLEOqEDYQaxYeVpMDigmUBZGkqiqMJaHBNuCatGJLL8TIgnQtuHKtAZ7SwGlaU6QYKw6ZWaANXoWD4FgtBxgwygptQcY4Aw+A7rQATFlksgyNKaCUDQtBYDI0AwOqeA7hgO47FNykungkxhIgMRsBwICYDgeD4NQcACNNwjMDwUArTs2jJhAboYMWwQ7rO1C5qwbB1SAHJoNmCAoJwx08Fg7SEJF5BUHW5A8CQxAyHAiDRh1MjZnOp0zZG4PEJD0BTcQxYyNwIBwNQkVuD9rBAA).

**Comment by LeXofLeviafan** [comment]
@osban So… you're suggesting replacing a workaround with a workaround, then?
And as I said, it's a refresh bug – the value _is_ empty, but it's not propagated to DOM/UI until the next redraw.

As for the 'other issue', it's a matter of app logic (ensuring if an item is selected before removing it; the natural way is to check if `choice` is empty/nil) and has nothing to do with Mithril itself.

**Comment by osban** [comment]
@LeXofLeviafan The value is _not_ empty, because the `selectedIndex` is reset to 0 after the selected element has been removed, and this in turn sets the value to the title of the first list item (see [here](https://flems.io/#0=N4IgZglgNgpgziAXAbVAOwIYFsZJAOgAsAXLKEAGhAGMB7NYmBvEAXwvW10QICsEqdBk2J4hcYgAIMABxmSAvJIAUASkUA+ScAA6aSZNhTqhWhGoxFkgOTWA3HoPiptGcQj04V5I4PaIACaINgCMAKwAHADMAAxhAJwAbPFJIQBM1hSS7sSwwdYAkoxYIdbsvgbAgfnh0XFJKYkhUZnZELkw+UUwWBnl+n5VQaGRsQnJqQAsrTl5Nt1YLay+ALoOA0aScDCw1IwBBWgBMAAeVmqakq7unviQR4fHJ8pnClon+IGKCkomZhaqdYGXzOaQBALndRvbQVSSgtAwADu1ysQ2CAAMACTAAAiGEY+DQtERalY6Kys06NgA-GUgX5rh40HB8HAZFBzDBlNtdvtHqc1ABqEJZGJZBHItyA2F-TlWCXXT4BemsemggBOPUhl10AwMEDAKh5MD2MAORwF6i0AFoQupdX4GW4mSy2RyLNydia+Rbnqosnb6Y7ZRYrLY7H4APSRyRoACuUCgkgCtHgaGsUmR6oA1nDaOrNXsoABPWHLAaq3y+TXEOPq-QOvwANwgSOCF2hPj1fiwymshFKWWA9Go7uzwXEtFg+CgtAA5uwbABlL17az+2EGXvWABGceIxHorWHaFH5nHYICi+sgvXFE3km3xrXQ4fjvocZkAXxVOUwBTWCsFCWiNo6YF5syU4wDO859hAvqIK0AGsquPpPKob5gZO06znOfZNhgUBxp0SG0Fg+AEURMAYd24H9OB76noQGBoHOVKWNCwAhhxkjQcQGDqmxxAUYRxH0QxBiUcRE6mJy960X44ngYytxYLILyaJhW59ip6avgp4FSVSHyBPJEmOs++zBCZEI-L8skWGZ5mLh8lIbgZkjueBXlgdue4HkeQ4jmOwSaoBWTWNad4Pso3GSNSj59jImqtAAUkuADyAByrLEOq8FzgaxaxQ5MDigmUBZGkqg0eZYHBNuCatLpLJqTIGnQtuHKtK57SwDVNVOQYKxOZWaBjXo5FYLQcYMMoKbUHGOAMPgO60AExZZLIMjSmglA0GRMjQDA6p4DuGA7js+2WS6eCTBEiAxGwHAgJgOB4Pg1BwAIB3CMwPBQBdOzaMmEBuhgxbBDus7ULmrBsCNIAcmg2YICgnDvTwWDtIQ+XkFQdbkDwJDEDIcCINGs0yNmc6fWRkbY8QuPQPtxDFjI3AgHA1D5W4COsEAA)). So I guess things are being updated, just not how you want them to be updated. A redraw is therefore not needed, just point the `select` to the right element. To be clear: you can of course use any workaround you prefer, but I think this is a limitation of the `select` element, rather than a fault in Mithril's redraw. And yes, I could be horribly wrong.

**Comment by LeXofLeviafan** [comment]
@osban Again, _pay attention when reading_. The value _is_ empty, but it's not _propagated_ to DOM/UI on the first render… Even though doing a redraw _without_ changing any data (which means generating the same VDOM) _will_ propagate it; thus, the issue is that it's not rendered as defined in the first run – and at the very least, the same VDOM is supposed to produce the same DOM, by definition.

**Comment by CreaturesInUnitards** [comment]
@LeXofLeviafan 

Yup, this is a bug, but it's more about browser implementations of `select`, which we all know to be immensely problematic. [Here's proof](https://flems.io/#0=N4Igxg9gdgzhA2BTEAucD4EMAONEBMQAaEAMwEskZUBtUKTAW2TQDoALAF0fmPSk6IBqECAC+RekxYhWAK2olIAoZxHKYnAAQRsnctBhaAvFpoAdKFq3At5fCi0BGIlv2ckjgOTlBjJ15aEpbWtvaOAEyu7p5aPn4RgcFWNnYOWgDM0b6x8YiMGUlElgC6lpYa2jjYJloA+gBuUBD4iCYAfDYhWkjaeEhggvi1UACu8PDdvVr4AE66+BAA7lAA8thCtaSY8Hjd1t2VWv2IgwQAklCtAB61ABQAlB1a+zp6BrCsFFeXN3cQzwBxmBx0QAyGD26h0MVXww1MdTaxk6wFeR3st1MJzO+F+iGujy0AGpnK9sUNamF0gARTCCVjNJaPbIeRDeAD8SVeun0hlYMGw8HIYEQdwxrgADK5yQRISkxFCUkdZvlaojnqiUtYeR8YPzBcLRTLcVd8cznHLrNZjbUvF5ugqoN0VZxRrMrJqrVoGuREEtHI1nhYtVbGHcvKxqvaQ17XGGvAAjUacTjQLyuWzQMBCsAAa0cmDhQVcXiJXktXqtcfDrDmC2WUGjlcrGZ0UGzwvz9SRKJm82wixW602pgAhHWBw3h1YxI7m7GtPGsAmwenQeCCFp2evTkNWDE2t5y69m64J4O1hsrAAya+Lms6wxN+cLx+fRg4f7vaDPE8v+8Rm+a62H+-5aLmiAAJ6OG+rD2K4oH-g0OyjGyby8lAxQxmBbYdnmAY9qkNqmG+QSIc2EjoR8+45IgFZgfR86MV6zFVgBSYpmmrZZjmXYqowxZxAAtMe2GsdKYK7puiHbvG2AqmuABSADKqwAHL8pwszkFAADm5CkJBX4YXq3z4P8gJwfCILGg8rhjBMrgRA8rHWI48bjGub56h+2AWciAFCl5NGsi5jFlPKliOpYjCsIwECjAIdyLGAozMAIrAJi0kGuNUDx8JAjDYJQiCzCICaYCuvAkOSuoiE4ACcKARE44iSCADDMCIrBgDAij8IIwhoAAVKkWXXEJMDkAAXjpumOFlsytLMQnjWRTpQJG2DYK4y5gl0KT4OQApYNBWikEg1wANzdDs5C6VAQm+PkMCOCKKizDdUDRZt54Ngd1hHSdmBnTpQpQIgq3wBAeZfdY2AQFNGGOCqWD6A0iBw1oSz2Jw7COE4ACsErYNd3SLctBOk8cCD2FoADEcL4FF5RQHt8AA9juP484EoSgApFj7CIPdXCOBkJNkyk2CFkdemOBKvOk19P2sN5nMI0jHwFgmcDwMmmPdKm2AE3zgtTIgpCcArWM4-geOmwLWMVXmunzIl6RLOwz3OxAS2lVTtx63TjNwizG1q9+HpaDLcJzY4hPU46kcYcSWijbYFOlUJxuBzTQrDKHwyq2+KDsBAGOzGNmCu+7VyOEXQR8LVhgiAALM1ETiCUJDg7m1AoHQHXSCIjC+Ow2nVSAbq8GgXCcLgKAAPRL4l2C5rpPUQIwS9j3jk98JwkEbCIMBgNpejd2IQA). Works like a charm! There are good reasons why everyone's implementing their own `select` widgets.

Your best workaround is this:
```
onupdate: v => { requestAnimationFrame(m.redraw) }`
```

In truth, I'd recommend against fixing this. I'd also recommend _not_ being rude to people who are trying to help you 🤷‍♂

**Comment by osban** [comment]
@CreaturesInUnitards thanks for clearing that up!
