### ISSUE TITLE
pathname routing strategy is broken

### ISSUE THREAD

**Issue by reubano** [MithrilJS/mithril.js#2577]
**Mithril version:**
2.0.4

**Browser and OS:**
macOS 10.13.6 
Chrome 80.0.3987.122
Firefox 72.0.2 

**Project:**

## Code

```coffeescript
m = require 'mithril'

Application = view: (vnode) -> m 'p', 'Hello', vnode.children

routes = (app) ->
  '/': render: (vnode) ->
    m app, vnode.attrs, m('p', 'Home')

  '/:page': render: (vnode) ->
    m app, vnode.attrs, m('p', vnode.attrs.page)

  '/:page/:id': render: (vnode) ->
    m app, vnode.attrs, m('p', vnode.attrs.id)

m.route.prefix = ''

location = document.getElementById 'container'
m.route location, '/', routes Application

```

## Steps to Reproduce

1. visit http://127.0.0.1:3333/page
2. visit http://127.0.0.1:3333/page/id
3. See console errors

## Expected Behavior

No errors

## Current Behavior

```
Navigated to http://127.0.0.1:3333/page/id
DevTools failed to parse SourceMap: chrome-extension://lfbajboiahaecepobmkcpadfeojchmmf/js/db.min.js.map
Resource interpreted as Stylesheet but transferred with MIME type text/html: "http://127.0.0.1:3333/page/stylesheets/app.css".
Uncaught SyntaxError: Unexpected token '<'
Uncaught SyntaxError: Unexpected token '<'
```

## Context

Commenting out `m.route.prefix = ''` and visiting http://127.0.0.1:3333/#!page/id works as expected.

**Comment by isiahmeadows** [comment]
Could you post a full self-contained example, and not just the script part? [I'm having trouble reproducing it.](https://flems.io/#0=N4IgzgpgNhDGAuEAmIBcIB0sD2AzXEEIANCLgJYxhoDaoAdgIYC2R6GAFvM1CSDvUSC0IADxJyANwAE5JAF4AOv2yDG5ehABOygHyiA9BMm6+kGAnKrq6AAyoATLZABfYgxZtMOfIT4CheBEAYmlmaXlpLQgARwBXcmjpAHJmcngOLUpkxXpcgHcNJGx8jFUAB2xysHhGRAjpAFpdXOlpaAhwyOLYONZBLGi6iABRGH74FLBYLPL4HPo2juYMMC1YBuSueGrUAwM4+nKAawBzLGxmAzSMrKgAAQcMWwwAFmv0zMoMNPoMACswAsluMyvQoNhGEgGqoIVDWtIen0IAMOBAoRhGOVyiikABhDiUaHLXK5ACC2Kg5FgdSsi0iknIEHyqGkAApJPRsEgIABKJq6MIpcrJYgpAAS0AhouknO5ECwhKgSGieTVWmwcUQYAabKx5X5zQRyQMyVZqp5WlZHK5PMNLUWbSF+rFcp5mPg8C0YDFzDZyRFYuS4suEGSvNJjpNqHKjFOYfNuO01rdfIFCLa4RdsttCrqXp9YX9gZz8o9BYwsfjEbVbWjVYgBlQcjNUSTVvZqftGed2NdufL3t9xZlqcHYAwchruVhkOhkSNjpWGq1CvK0QoAA9NsDpBCafA6Q0kRMMPH4GNOij4AAhACeAElockAupNFpd8vNfV97TVEHTTFFdtWkClyipA86UjQkamwLQ7wwaJwMYWAIAAZVqep6DiKAoDFbDcIAhsDBbXIYPgOCEPKOIwA4DDhmkAi8MYnDmJNBZyMojAACMUOONleX8S5ykobQRB8AgiFIcw4EPawRAcABWVBXgcVx3BAJhWBELAwGoUgAmvERXAAXRcIA)

**Comment by reubano** [comment]
https://github.com/reubano/mithril-pathname-bug

```
npm install
npm start
```

**Comment by reubano** [comment]
Just making sure you saw the update @isiahmeadows

**Comment by dontwork** [comment]
Are you sure you are serving your index.html on every response from your server?

**Comment by isiahmeadows** [comment]
Your `javascripts/vendor.js` as requested [here](https://github.com/reubano/mithril-pathname-bug/blob/master/app/assets/index.html#L45) is returning HTML, specifically the same data as your main HTML route. (You get the same issue with your `javascripts/app.js`, too, BTW.) You may want to investigate your build configuration and/or server configuration, and you may wish to consider changing [these two scripts](https://github.com/reubano/mithril-pathname-bug/blob/master/app/assets/index.html#L45-L46) to be absolute paths:

```html
<script src="/page/javascripts/vendor.js"></script>
<script src="/page/javascripts/app.js"></script>
```

What's happening is that when you visit `http://localhost:3333/page/`, your code loads `/page/javascripts/vendor.js` and `/page/javascripts/app.js`, but when you visit `http://localhost:3333/page/id/`, it requests `/page/id/javascripts/vendor.js` and `/page/id/javascripts/vendor.js`. This all boils down to your `document.baseURI`, which is initially set to `/page/` in the first case and `/page/id/` in the second case.

Relative paths are things you *really* should try to avoid just in general for SPAs with pathname-based routing. The issue is you could be loaded from anywhere, and you don't know where that path will be just by looking at it - you would only know at runtime.

(If you really *do* want to keep using relative URLs, stick a `<base href="/page/">` in the `<head>`. This is useless 99% of the time, though, and about the only legitimate use case I can think of is with cases where you can't run JS for reasons, but you still need to modify the base URI, like with cached results in search engines.)

**Comment by reubano** [comment]
Thanks! I changed all the paths in `index.html` to be absolute and it's working great now! 

```js
...
<script src="/javascripts/vendor.js"></script>
...
```

Just weird since I recall it working before with relative paths in v1...
