### ISSUE TITLE
How to include elements created with m() as children of contenteditable div?

### ISSUE THREAD

**Issue by sidmani** [MithrilJS/mithril.js#2583]
**Mithril version:** 2.0.4

**Browser and OS:** Firefox, Arch Linux

## Code

```javascript
m('div', { contentEditable: true }, m(CustomComponent));
```

## Context

I understand from the error that `m.trust` is required here, but it only takes a string, and I want to render a custom component inside the contenteditable. How can I do this? I understand the security implications and am sanitizing on the backend, so I just need to get around this check somehow.

**Comment by fuzetsu** [comment]
@sidmani You could get around it by using `m.render` in the `oncreate` for the `div`:

```js
m.mount(document.body, {
  view: () =>
    m('div[contenteditable]', {
      oncreate: ({ dom }) => m.render(dom, m('h1', 'Hello World'))
    })
})
```
[flems](https://flems.io/#0=N4IgZglgNgpgziAXAbVAOwIYFsZJAOgAsAXLKEAGhAGMB7NYmBvEAXwvW10QICsEqdBk2J4s+LLQCuDABQATWtSk4G+AEa15ATwoACYAB00evQDcIMAO6I9sgJR6AvAD5jp01lkByeRDPIQozCfsQY6rAAut76wHr01ABOMBiMtrJxilh6rI6ueuLJaPIwiQq0WPpe3oQAjDF63gASMFBQtHoA6rSJUPLe9o65xsNolCBwrTDUxBD0CDwADIiLALQALCtsHCCYOHj41HACNPTBojxskVRQEGgA1guou1xiEMSEidDjUr14JMQAA5wRAAelBMkB9wA5ocKqCsO9PtAAAIAJnwi3w6wRSK+UAkd3w-HGxG0gO4EySEEBolYkVYQA)

Just have to be a bit more explicit about when you're rendering.

Makes more sense to change the content in a lifecycle hook imo, since Mithril can't really diff against user input in the `contenteditable`.

**Comment by sidmani** [comment]
Thank you!
