### ISSUE TITLE
Mithril stream.end(true) ends other dependent streams as well

### ISSUE THREAD

**Issue by dontwork** [MithrilJS/mithril.js#2601]
**Mithril version: 2.0.4

**Browser and OS:** Windows 10, Chrome Version 83.0.4103.61

**Project:**

[mithril stream](https://flems.io/#0=N4IgZglgNgpgziAXAbVAOwIYFsZJAOgAsAXLKEAGhAGMB7NYmBvEAXwvW10QICsEqdBk2J4hcYgAIATjDCy4hCGgDmkgLySs+CbOwAKAJQAdNKfFTaARg0y5CpavxYMAB30A3DQD5J7gOTWdtQwEB4wACb+FJIehiZmaBaSAO4YEMTKapqy8vCOKs5u+p4YUIY+ksCmkn76-mkZWcGh4VExHmUJtRBgkqVQGuqaYGVwMBXVaLW1jZlOTBH6xNIArhM1MwFzzYuR-t2SrKasCeb0EpK0AEy2uQ5ZRe5e6r4BNy1h+x3xpqb3+SyyzWGzQAMUQNGUHGCXBBXqWFosgOpkoNFoWFc0Bg0jwACMMHiYOQqONYNRMhc8FYAOyIAAMbA4IEwODw+GocAE6OEzB4bAAulQoMoANYIFCcNk8LAZQjSaBo1bScg8EjEVxwRAAem1qzQrlFhToWG1suI8ugAAFrvh6fgACxmuUKqDOZT4fho4gAT1c3BAcGoCtconYUoD5stUAAtLoYNglSq8OrNTq9QajRyMc6La64ysE1gbXa7dr49hPdzff68EGQ2GBawgA) vs [flyd stream](https://flems.io/#0=N4IgtglgJlA2CmIBcB2ArAGhAMwggzsgNqgB2AhmIkiAHQBWhWAxgPakAu8nyIbp+DgAIATvGxj8ACwikA5kIC8Q7LACeUWoLGUAFAEoAOqWP9BQ1gEYlo8ZJnzaYcgAddANyUA+IW4DkVrbM8BDu8FB+GELu+kYmpGbCAO7kEByyCspiEvDSGU6uuh7ksPreQsDGQr66filpGUEhYRFR7iVx1RDYQsWwSorK2CX48GWVpNXV9emO3FC6HCIArmNVU-4zjfPhfp1CAL7GB3Gm7OasAEw22fb5zm6eij7+V02hu22xxsa3uQ5yRYrNakP55eS6YawUZxMEA2pgVhiPbGEAHAC6WFgsgA1oQkCQQBQqLxVBoQFhliJYLwpBwOC58EgAPTM5akFw4uS0NhgZlkqAAAQADLRLrQABz89SaRgUkAcNQuaggfDMEQQFwcNHog5AA)

credit to @foxdonut for the reproduction

notice in the mithril example how o2 doesn't receive the false value
but using the same example with flyd, o2 does receive the false value

The code I was writing was this:

```
    if (auth.refreshing()) {
      const waiting = auth.refreshing.map((val) => {
        if (val === false) {
          resolve(token())
          waiting.end(true)
        }
      })
    }
```

The unexpected behaviour i experience is that when there were X numbers of `waiting` streams the code `waiting.end(true)` seemed to end ALL of them

**Comment by isiahmeadows** [comment]
Could you provide a fuller repo of this? Ideally a Flems? It'd be much easier to figure out if it's by design or a proper bug - every stream library's behavior is just the sum of a ton of subtlety.

**Comment by foxdonut** [comment]
@isiahmeadows the two links above ("mithril stream" and "flyd stream") are Flems showing the issue.

**Comment by isiahmeadows** [comment]
Yeah, that's a nasty bug. `o1` and `o2` should either both end or both continue. I'll look into it.

Didn't pay close attention to the links. Sorry!

**Comment by isiahmeadows** [comment]
Just for clarity, here's a minimal example that doesn't involve nesting: [link](https://flems.io/#0=N4IgZglgNgpgziAXAbVAOwIYFsZJAOgAsAXLKEAGhAGMB7NYmBvEAXwvW10QICsEqdBk2J4hcYgAI4tAK4AnajEkBeSVnwT5MbAAoAlAB00x8VNoBGVdLmKY+LBgAOugG6qAfJJcByS5O0lCFcYABMfCklXfSM0M0lGCWsZBSUHZ103DCh9T29dHwB3DAhiCDQAcwCYIJDwyNdsmNN6JNoAJmTbNMcXdxUvXw7q2rCIqOaTNBS7Ash5CR9YxOJ8JlDdYnlZGH0AbnyikrLKyXWx2JmlAqxabSXjShpaLCdoGHk8ACMML5hyKhwf41MqtPAATkQAAY2BwQJgcHh8NQ4AJnsJmDw2ABdKhQcoAawQKE4iJ4WFKhHk0CeCnIPBIxCccEQAHpWbI0E4CRVkS9WRTiFToAABdr4KH4AAsAsp1KgDnK+H4T2IAE8nNwQHBqNSnKJ2KStYLhVAALRaHRYWnyekgRnMtkcrk8vlYWVC+UWrZWsUSiWsy3YZVo9WavA6vUG7GsIA)

**Comment by foxdonut** [comment]
No worries!

The minimal example doesn't expose the bug though... does it?

**Comment by isiahmeadows** [comment]
@foxdonut It prints the same thing as your Mithril link. I just removed some unnecessary printing.

**Comment by foxdonut** [comment]
@isiahmeadows Please have a closer look because it's not the same thing and it does not expose the bug. In my Mithril link, notice that o2 doesn't receive the `false` value, only o1. That is the bug. In the Flyd link, both o1 and o2 receive the `false` value.

**Comment by isiahmeadows** [comment]
Oh, whoops. You're right, my bad. 🤦‍♀️

**Comment by jaydh** [comment]
I'm pretty sure this has to do with ending a stream within a dependent stream's map. What's really going is better illustrated [here](https://flems.io/#0=N4IgZglgNgpgziAXAbVAOwIYFsZJAOgAsAXLKEAGhAGMB7NYmBvEAXwvW10QICsEqdBk2J4hcYgAIATjDCy4hCGgDmkgLySs+CbOwAKAJQAdNKfFTaARg0y5CpavxYMAB30A3DQD5J7gOTWdtQwEB4wACb+FJIehiZmaBaSAO4YEMTKapqy8vCOKs5u+p4YUIY+ksCmkn76-mkZWcGh4VExHmUJtRBgkqVQGuqaYGVwMBXVaLW11vhMEfrE0gCuEzUzAUELkf7dkqymrAnm9BKStABMtrkOWUXuXuq+W9eyIWG7HfGnaOe0AGYbvZ8vcXI9Klsge9Wl9Yj8kmdLAAWYF5RRg4pPF71WiomGfdrwhLJWgAVjRdyc4M8kNxFIJbWixNMpluoNUS1W6zQ7IxnNGUHGCT5BXqWFosj2pkoNFoWFc0Bg0jwACMMKqYOQqONYNRMmc8FYyYgAQB2NgcECYHB4fDUOACOXCZg8NgAXSoUGUAGsEChOLaeFgMoRpNBZStpOQeCRiK44IgAPRJlZoVw+wp0LBJkPEMPQAACl3wAAZ8Mjc6Hw1BnMp8PxZcQAJ6ubggODUcOuUTsQPtvMFqAAWl0MGwkejeDjCeTqfTmft8qr+Zro+W46wxbLZaTY+wDadLbbeE73d77tYQA). Note that after o1 gets ended, o2 is missing but o3-5 show results. This is because as the parent stream is executing, the end call unregisters the child and splices the dependent streams/dependent functions _during_ the iteration which causes the skip.

I agree this isn't ideal behavior and probably the simple fix is to mark stream removal, check for stream removal before fn execution, unregister all marked for removal streams _after_ the execution calls. 

Thoughts?

**Comment by isiahmeadows** [comment]
@jaydh The actual issue is much simpler: it's skipping all remaining children, even ones that *weren't* ended, even though they remain subscribed - note that in the subsequent emit after that one, it's still received by both streams. I suspect a `return` is used where a `continue` or similar should be used instead.

**Comment by jaydh** [comment]
@isiahmeadows That is not what is happening [here](https://flems.io/#0=N4IgZglgNgpgziAXAbVAOwIYFsZJAOgAsAXLKEAGhAGMB7NYmBvEAXwvW10QICsEqdBk2J4hcYgAIATjDCy4hCGgDmkgLySs+CbOwAKAJQAdNKfFTaARg0y5CpavxYMAB30A3DQD5J7gOTWdtQwEB4wACb+FJIehiZmaBaStABMtrLy8I4qzm76nhhQhj6SwKaSfvqB6bIhYZHRsUUJlRBgkoVQGuqaYEVwMCXlaJWV1vhMEfrE0gCuQxVjAUFTja2SrKasCeb0EikAzBn22cq5Lu5e6r4rx3Wh4VExcQnJtAAsJ1mK53lXpRWXweDWesXiezQB1oAFZvg4-pdPIDqrDgo9Gi8IYlMgjVPp+lBBglKDRaFhXNAYNI8AAjDC0mDkKiDWDUYgQfZ4KwAdkQAAYALT8gVsDggTA4PD4ahwARk4TMHhsAC6VCgygA1ggUJwpTwsBBiIRpNBSXNpOQeCRiK44IgAPQOuZoVya3J0LAOw3G01QAACqXw-PwH29RpN0Gcynw-FJxAAnq5uCA4NRTa5ROw9SmfZGoILdDBsObLXgbXbHc7Xe6ZeTw77oIXZsWsIHg8GHUXsLH5Ynk3g0xmsyrWEA). Note that after o1 gets ended in the execution of o2, o3 gets skipped, but o4 and o5 still print results.

This behavior is explained in the [source](https://github.com/MithrilJS/mithril.js/blob/next/stream/stream.js), when invoking `refreshing(false)` we have the parent stream with 

`dependentStreams = [o1, o2, o3, o4, o5]`
and we run through

 `dependentStreams.forEach(function(s, i) { s(dependentFns[i](value)) })`
o1 runs (index 0),
o2 runs (index 1), but now we call `_unregisterChild(o1)` which mutates depedentStreams to look like `[o2, o3, o4, o5]`
and now we're on index 2, which now points to o4 which is why o3 gets skipped and o5 still prints.

**Comment by isiahmeadows** [comment]
Now that I look closer, that's even weirder.
