### ISSUE TITLE
Bidirectional textarea loses keyboard events

### ISSUE THREAD

**Issue by fidian** [MithrilJS/mithril.js#2792]
**Mithril.js version:** 2.2.2
**Browser and OS:** Chrome 102.0.5005.115 on Ubuntu 22.04 jammy

## Code
[flems.io example](https://flems.io/#0=N4IgZglgNgpgziAXAbVAOwIYFsZJAOgCsEAaEAYwHs0AXGWvcqDOOAAgEk0AHAVxoCCAJxgY2wADpo2bAG4QYAdwAUstJQAmMAJTipMmSJq8h0rMokg6ADxoYRGSyT3SDM7s3IwAFpShahRDYAcgBRWhghNhsaNm9ImGCSfTc5DCheGCC1TRh8DBoaITh8WXTM5Nc3agBrGABPXm4g5R02AF4APhdUgxytfMLi0vKYDrY8uyEAcxgaEYyYAG4UtwBfVbY17RXXDbR9qSx8LEpeWmUNSnJeHFp8ACNNeudJKrYIHn4ARiDgNMWQWCwS2lTcnz4NAATH8AZkgVwIDQIOkQWswX0FIogmBzuRkdRlLo3r1DHMTGZlMENBBZEk2MhNr1zFxIcJRM4aN4ICUIT9tBjSWxzMFuPSuTz8HyaN8FpkBUzUiyvoIHJzubyVVCFe9mVSxerJdKoXKdILSSKDT0hQZqEwIOQai1dF1rTaDBLNZDZWVFuNggAlUIAZVCABVgrt3W5PVKtab-UHQxGo9H9u70SEAMJQB01aKUNgB+BzYLaRUyAC6O02+22UhAZDgMFg+Ig1AQiBAAAZEN2ALQAZl73ZAa0rZFzaBqndQIEwODwWCR3iE0EbIBMUDw3kK3DgiAA9IfztwatN8FQsIfl1y11AAAIm583lf3k6fIikKz1bi4LtwOQa7cDQY6VmsQA)

## Steps to Reproduce
Go to a textarea and alternate very fast between a letter and the space bar. It helps if you use two hands or two fingers on the same hand.

## Expected Behavior
Letters and spaces should show up.

## Current Behavior
Sometimes letters are dropped. The events are not firing.

## Context
I have a website that I'm porting over from Angular. It's a simple cipher site, where the user can type in whatever text and it gets encoded. On some of the pages I have buttons that will alter what you typed in, converting everything to uppercase or removing spaces, or other manipulations. So, I need a bidirectional textarea that allows the user to type in data. My typing speed is fairly fast, so it is easy for me to trigger it by typing in a sentence, but it does not show up if I repeatedly type in "asdfasdfasdf". Spaces appear to the the trigger for this behavior.

If there's another way to implement a bidirectional textarea, I'm totally open to ideas.

The example shows the following that must be able to work in some fashion.

1. Allowing initial data to populate the textarea. One textarea uses a placeholder because it has no initial data and the other does have initial data.
2. Allowing the textarea's value to be sent up to the mounted component so it can be used elsewhere. I put the data into a paragraph right below the textarea.
3. Allowing the value to be changed from outside the InputArea class. This example has a reset that can be triggered.

**Comment by osban** [comment]
I've tested this (using the flems) in Chrome, Firefox, and Edge, but can't repro the issue.

**Comment by barneycarroll** [comment]
Also finding it very difficult to reproduce - including on latest Ubuntu Chrome.
I think the problem is this though: [I set up a little test sandbox](https://flems.io/#0=N4IgzgxgTg9gNnEAuA2gBgDRoLoZAMwEs4BTMZFUAOwEMBbE5EAOgCty8IYqAXE3plypgeAAhIA3fjzCiAvKJQAdKqMUBybgGsSATwAOUMmHUZRACknSzYEjwCU8gHyjbPS1N7Mdu0fdwqaiiaVD4Arvqmamoe1q52jnIubrFePn4BqhrchFT6YTxR0ak8NgnO8e5WXgAmNDw0-hgq2IGizHQ0+ubmKNU8tAxmABY0VDWkUGY0EBBhdGFw9YTc8qLqURI0cGEkaxvYiS7mwG1q-YMkZmeio+OTSOIVp1nRols7ewokzA1QAOZ2ZgfXY3NR3CYkKCWMwADwqMzmCyWPBWqgA1ApYfYbgBfa6vUSAsSI+aLZbccz2F5vNRGHhhKCqUnIilUPHNQnE97bXZUmm0+mM1Qgkgctq4+w49lUIQiVy0fRgYYwGRrFCtGV0DowMK8cw1GBI6TMABGMBqujMAu4ppI+BgRgidT4-JuYEVytVYGY+WV5jB4k8Mg6XR6wAu9CuohZ5NR3DMoslFROgfOwcuBNp0VjKLRWezPM+nOzkulb3LonxbQkhBIAHdHlSKspCXRzOphgAmKLqACSeQK6nsJei7fUfFhfxINHUN3R6xQ+iWEBIKrgNShciUIAAKlBfGB9PQ6Ll-qIIKMoDM+FBRLl8mrcqJr-pCDUY3Bb7R46p64QeGGURAL2I8Zj2U0aCgHdsDnQkF3UFARF0UhtxAf8akAx4AGY0BIOgAG5bhIQh-mGHhHgARjwwiYKiQMAHlTVYEgIB4Zh8FgOgAFFeCgOswBKH1Om6E5IyGW4xkhKBkySRRxOjCFJkOSs1BHG4bnHbtewYgpH2HUc1E0jsGlNUhTEDccQJoGoomAW17UdEhnXqEgmyOUR8G2Wxq0JN4rKgKJ+mEsMAH0Kis4YUC4OAwKoOQu1gsxQuYBSpXUvyxxMwKzGC0NunCuTglzNlewgLoGSMD9RXUbB8vMQqXEiqJQvSjLs3a2lAw9LovRDIwpCgWwqXq4KKjTUQAoszK3jykTwxK39E15EhZJcFBFvzItdjq+bGsmkzbOS9KJtU6Izs6zVJRAPBbFINi0XIJAQAADiQLtsJAXFcBAOBci0J7KBAS4mFPQD+MQPBGUQZ7yJ4JUkAAekRvV9C0f5mC4OhEbB4YIYAAS7Zgia7HGALx4gOlyNgOBAHgDEYZ7IH4-QeC+7BcSAA) to capture a variety of input events on a textarea and, for each, captured both what the event described in its own metadata, using an accumulation of this to produce a representation; and the captured element value at the time the event handler resolved.

Then on each redraw, a snapshot is saved with a rasterisation of that data for each such event, and displayed as a table. The results are informative:

1. `keypress` resolves before its inferred effect is persisted to the DOM value (accumulation is always ahead of value)
2. `keyup` values accumulate out of sync with un-mediated DOM value persistence (the accumulation has spaces and characters out of order with the value)
3. `input` is the only robust capture that represents the latest input

What I infer from this is that whichever keyboard event you use, there's a risk that it captures DOM value before the native 'input sequence' has resolved; this value is persisted to the application data model; Mithril queues a redraw as a result of event handler resolution; by the time the redraw resolves, the native DOM input sequence has resolved, and the DOM value is in its 'correct', up-to-date state; Mithril reads the (now stale) value capture from the point of event resolution, compares it to the current DOM value, and (against our assumption) deems the DOM value to be out-of-date, persisting the stored value.

I think by using `oninput` you ought to be able to guarantee that the captured `vnode.dom.value` is always the latest. [Can you reproduce the error with that modification](https://flems.io/#0=N4IgZglgNgpgziAXAbVAOwIYFsZJAOgCsEAaEAYwHs0AXGWvcqDOOAAgEk0AHAVxoCCAJxgY2wADpo2bAG4QYAdwAUstJQAmMAJTipMmSJq8h0rMokg6ADxoYRGSyT3SDM7s3IwAFpShahRDYAcgBRWhghNhsaNm9ImGCSfTc5DCheGCC1TRh8DBoaITh8WXTM5Nc3aggefiDlHTYAXgA+F1SDHK18wuLS8pgWtjy7IQBzGBoBjJgAbhS3AF9FtiXtBdcVtG2pLHwsSl5aZQ1Kcl4cWnwAI00AT2dJKrZavhoARiDgNNmg4OCa0qbje-AATN9fpl-lwIDQIOlAUtgV0FIogmBjuR4dRlLpnp1DFMTGZlMENBBZEk2MhVp1zFx3sJRM4aN4ICVQZ9tCjCWxzMFuNS2Rz8FyPjNMjy6akGXVBA5WezOfKwdKXvSyUKlaKuWDJTpeYSBdqOnyDNQmBByABrBq6Npm80GEUq94SsqzYbBABKoQAyqEACrBTbOtyusWqg3ev2BkNh8PbZ3IkIAYSg1pt0UobB98CmwW0MpkAF0NqttuspCAyHAYLBsRBqAhECAAKyID4AZhAS1LZEzaBtrdQIEwODwWDh3iE0FrIBMUDw3kK3DgiAA9JvjtwbeN8FQsJvp2y51AAAL668nmfng61IikKz3bi4Ntwchz7g0PulpZAA) @fidian?

**Comment by fidian** [comment]
That works like a charm. Is there a place in the documentation for tips like this one?

Closing because my issue is resolved.
