### ISSUE TITLE
Leftover DOM elements when switching between fragment and element

### ISSUE THREAD

**Issue by 17dec** [MithrilJS/mithril.js#2842]
**Mithril.js version:** v2.0.4-156-gad9aa97d

**Browser and OS:** Firefox on Linux.

**Project:**

## Code

```javascript
var toggle = true;
m.mount(document.body, {
    view: function() {
        return m('div', { onclick: () => toggle = !toggle },
          toggle ? 'text' : [ 'fragment', 'b' ],
          m('br') // extra element is needed to trigger the issue
         )
    }
})
```

[Flems](https://flems.io/#0=N4IgZglgNgpgziAXAbVAOwIYFsZJAOgAsAXLKEAGhAGMB7NYmBvEAXwvW10QICsEqdBk2J4AbhgBOAAmK0A5vNjSAvLMkBXGAG4AOmiz4stDQwAUAE1rUNOBvgBGtCwE8K04PunfpYiDAB3RGkwU2piCHozAEoPLx8EyRhiDUk0aSwzAHILCDEs92BpemooCGoAa2CY1QA+WQUlGFVpAEI5RWV2eISEjqbpAH5pLMYAD2Is6WDkEbBJDHk7SfcshymAXQoe3u9Mtcks2IB6Y+kYCYXz2GXpCDhpNBgYCxeG9QhFGBliQmb7uBaHa9aI7Vj6VjRSggOAwWDhSJoBA8AAciAATABaAAMiGxbA4IEwODw+GocAENHojGYPDYWxAZTQFWRqCJXDwWAgv0k0AAAk8JtDUuQeCRiAAHOCIU6mCUVeRk2hYY5cnn8gDM+Gx2sxguI+AAjABWVXcwi8qBGCBofD8aHEFwS7gw6i8iWiVgbVhAA)

## Steps to Reproduce

1. Load above code
2. Click a few times on the `<div>`
3. Observe that the `'b'` element from the fragment remains in the DOM after switching back to the non-fragment version.

**Comment by j314h** [comment]
hi it's because of the <br> .

I find the funny approach of putting a <br> after a simple text hahaha.

the problem in this example is that each piece of text is considered as a pseudo element node

in the first you have "text" then <br> in the second you have
"fragment" then "b" then <br> when it switches for the first time it removes the first node and displays the two nodes "fragment" then "b" then when you switch for the second time it removes the first node but it leave the second because for him we replace only by a node (the first) and therefore the "b" remains.

to avoid this problem, you must surround your text with a <div> or other tag or you can also delete the <br> tag in this case it will replace all the text inside the parent <div>

**Comment by pygy** [comment]
This is indeed a bug, thanks for the report. I'll look into this.

**Comment by sonkwl** [comment]
working properl.
![image](https://github.com/MithrilJS/mithril.js/assets/18347766/744deb8a-1f1a-44b0-b079-58f84353c28f)
clicked!
![image](https://github.com/MithrilJS/mithril.js/assets/18347766/ff762a58-e22c-4371-ba0f-ed6eba0a7cfa)
Second click!
![image](https://github.com/MithrilJS/mithril.js/assets/18347766/3b68f95c-fe1e-4420-ab96-c5e0b024b05b)

**Comment by kfule** [comment]
This issue appears to be caused by a combination of the mangling of the internal bundler and the parameter destructuring of domFor().

https://github.com/MithrilJS/mithril.js/blob/cfa890f68571df1ab8543097f7fa61c34ee93683/mithril.js#L157

The member `domSize` (and `generation`) of the parameter object has been mangled unintentionally.
Fixing the parameter mangling seems to resolve the issue for now.
