### ISSUE TITLE
"m.mount(document.body, null)" wipes dom in presence of "onunload" doing "e.preventDefault()"

### ISSUE THREAD

**Issue by robinei** [MithrilJS/mithril.js#759]
This happens in "next", and not in "0.2.0".  "onunload" is run (and does call e.preventDefault()), but the dom is wiped regardless.

**Comment by 2is10** [comment]
This fiddle illustrates the issue using v0.2.5.
https://jsfiddle.net/0ymqp0od/

**Comment by isiahmeadows** [comment]
@2is10 If you're feeling adventurous, could you verify whether it's a rewrite bug or not as well?

**Comment by 2is10** [comment]
I looked through the rewrite branch for the first time last week and didn’t see any way to cancel anything in any of the lifecycle methods. I assumed the capability to cancel unloading was intentionally removed in the rewrite branch, which would make this issue irrelevant there.

**Comment by isiahmeadows** [comment]
@2is10 That would be correct (I haven't read the docs very well). But IMHO preventing a full unload like that is odd and error-prone, anyways, since especially in larger apps, it begins to get harder to reason when the root will or won't be unmounted because of spooky-action-at-a-distance issues. I'm not sure if it *should* be fixed, but the rewrite's relevant hook, [`onbeforeremove`](https://github.com/lhorie/mithril.js/blob/rewrite/docs/lifecycle-methods.md#onbeforeremove), is merely asynchronous.

**Comment by 2is10** [comment]
@isiahmeadows I’m fine with the “cancel unload” feature being absent in the rewrite branch.

**Comment by isiahmeadows** [comment]
I think the docs should be updated for this, then.

**Comment by 2is10** [comment]
How about using a separate issue to track documenting the removal of the “cancel unload” feature from the rewrite branch? That’s only tangentially related to this issue.

**Comment by isiahmeadows** [comment]
@2is10 Sorry, I meant for 0.2.x (i.e. `next`)

**Comment by isiahmeadows** [comment]
Closing - last v0.2 release has been cut.
